# Converted from SSG source: ARCHIFORMAT
# Generated by SsgConverter
param([string[]]$Parameters)

# Pour date table, null et cl�
# Embedded content (unconverted):
#   #
#   #delete,c     [filein,1,1,1].   
#   #asg,up       [filein,1,1,1].,f/0/pos/4000  
#   #brkpt        print$,[filein,1,1,1].
#   #dd,e    ,,udssrc   
#   report table [table,1,1,2] for schema [table,1,1,1].
#   process table [table,1,1,2] for schema [table,1,1,1] report.
#   exit
#   #brkpt        print$
#   #sym          print$,,nega/u
#   #free         [filein,1,1,1].   
#   @ . Pour description des champs
#   #
#   #delete,c     [filein,1,2,1].   
#   #asg,up       [filein,1,2,1].,f/0/pos/4000  
#   @ . 
#   #
#   #xqt,e        sys$lib$*rsa.rsac-coivp   
#   begin thread for udssrc read;
#   use default qualifier [table,1,1,1];
#   unload to file "[filein,1,2,1]"
#   select *
#   from [table,1,1,2]
#   format internal
#   with description only;
#   end thread;
#   exit;
#   #free         [filein,1,2,1].   
#   @ . 
#   #
#   #asg,a        [filein,1,1,1].   
#   #asg,a        [filein,1,2,1].   
$A = (2 + ((GetSgsValue ("key,1,1,3")) + ((GetSgsValue ("rsz,1,1,1")) + (GetSgsValue ("table,1,2,1")))))
$B = ((GetSgsValue ("key,1,1,3")) + ((GetSgsValue ("rsz,1,1,1")) + (1 + (GetSgsValue ("table,1,2,1")))))
$C = (2 + ((GetSgsValue ("key,1,1,3")) + (GetSgsValue ("rsz,1,1,1"))))
$D = (1 + ((GetSgsValue ("key,1,1,3")) + (GetSgsValue ("rsz,1,1,1"))))
$E = ((GetSgsValue ("key,1,1,3")) + (GetSgsValue ("rsz,1,1,1")))
# @ucob is .archiformat,.archiformat  
Call-ExternalProgram "ucob" "I, S" ("\archiformat")
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: ***                    -- archiformat --                       ***
# Orphaned data line: ***            Foramt donn�es pour archivage                   ***
# Orphaned data line: ***                        == UCS ==                           ***
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: * Type     :                                                     *
# Orphaned data line: * Analyste :                                 (INITIALES)         *
# Orphaned data line: * Auteur   : N�ga  NEGA SERGE                (INITIALES  NM PN)  *
# Orphaned data line: * Ecrit le : 13 mars 2002                    (dd/mm/ccyy)        *
# Orphaned data line: * Release  :                                 (99)                *
# Orphaned data line: * Version  :                                 (999)               *
# Orphaned data line: *----------------------------------------------------------------*
# Orphaned data line: * Modifications :                                                *
# Orphaned data line: * Qui ?  Quand ?     Quoi ?                             Projet/Ph*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: *                       DESCRIPTION                              *
# Orphaned data line: *                       ===========                              *
# Orphaned data line: *                                                                *
# Orphaned data line: *    INPUT : [filein,1,1,1] : report de la table                 *
# Orphaned data line: *    INPUT : [filein,1,2,1] : description de la table            *
# Orphaned data line: *    INPUT : [filein,1,3,1] : donn�es unload�es archiv�es        *
# Orphaned data line: *    OUTPUT: [fileout,1,1,1] : donn�es au  format  archive       *
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: Identification division.
# Orphaned data line: *========================*
# Orphaned data line: program-id.  archiformat.
# Orphaned data line: Environment division.
# Orphaned data line: *====================*
# Orphaned data line: Configuration section.
# Orphaned data line: *----------------------*
# Orphaned data line: source-computer.  unisys-2200.
# Orphaned data line: object-computer.  unisys-2200 MEMORY 3 MODULES.
# Orphaned data line: special-names.
# Orphaned data line: printer       printer.
# Orphaned data line: Input-output section.
# Orphaned data line: *---------------------*
# Orphaned data line: file-control.
# Orphaned data line: select fic-report assign to disc      [filein,1,1,1].
# Orphaned data line: select fic-descript assign to disc    [filein,1,2,1].
# Orphaned data line: select fic-unload assign to disc      [filein,1,3,1].
# Orphaned data line: select fic-format assign to disc      [fileout,1,1,1].
# Orphaned data line: i-o-control.
# Orphaned data line: Data division.
# Orphaned data line: *==============*
# Orphaned data line: File section.
# Orphaned data line: *-------------*
# Orphaned data line: * Fichier du report
# Orphaned data line: FD  fic-report.
# Orphaned data line: 1  lgn-rep               pic x(132).
# Orphaned data line: * Fichier de description
# Orphaned data line: FD  fic-descript.
# Orphaned data line: 1  lgn-des               pic x(132).
# Orphaned data line: * Fichier d'unload des donn�es archiv�es
# Orphaned data line: FD  fic-unload.
# Orphaned data line: 1  lgn-unl               pic x([*b]).
# Orphaned data line: * Fichier format� pour l'archivage
# Orphaned data line: FD  fic-format.
# Orphaned data line: 1  lgn-for               pic x([*a]).
# Orphaned data line: Working-storage section.
# Orphaned data line: *------------------------*
# Orphaned data line: *enregistrement type 0
# Orphaned data line: 1 ws-don-0.
# Orphaned data line: 3 ws-0-typ           pic x value "0".
# Orphaned data line: 3 ws-0-nm-base       pic x(6) value "[table,1,1,3]".
# Orphaned data line: 3 ws-0-nm-table      pic x(30) value "[table,1,1,2]".
# Orphaned data line: 3 ws-0-dt-ach        pic 9(8).
# Orphaned data line: 3 ws-0-dt-maj.
# Orphaned data line: 5 ws-0-dt-maj-ss    pic 99.
# Orphaned data line: 5 ws-0-dt-maj-aa    pic 99.
# Orphaned data line: 5 ws-0-dt-maj-mm    pic 99.
# Orphaned data line: 5 ws-0-dt-maj-jj    pic 99.
# Orphaned data line: *enregistrement type 1
# Orphaned data line: 1 ws-don-1.
# Orphaned data line: 3 ws-1-typ           pic x value "1".
# Orphaned data line: 3 ws-1-nm-cle        pic x(30) value "[key,1,1,1]".
# Orphaned data line: 3 ws-1-cle.
# Orphaned data line: 5 ws-1-typ-cle      pic x value "[key,1,1,2]".
# Orphaned data line: 5 ws-1-lg-cle       pic 99.99.
# Orphaned data line: *enregistrement type 2
# Orphaned data line: 1 ws-don-2.
# Orphaned data line: 3 ws-2-typ           pic x value "2".
# Orphaned data line: 3 ws-2-nm-chp        pic x(30).
# Orphaned data line: 3 ws-2-typ-chp       pic x(7).
# Orphaned data line: 3 ws-2-lg-chp        pic x(10).
# Orphaned data line: 3 ws-2-null          pic x(8).
# Orphaned data line: *enregistrement type 3
# Orphaned data line: 1 ws-don-3.
# Orphaned data line: 3 ws-3-typ           pic x value "3".
# Orphaned data line: 3 ws-3-nm-idx        pic x(30).
# Orphaned data line: 3 ws-3-nm-chp        pic x(30).
# Orphaned data line: 3 ws-3-tri           pic x(8).
# Orphaned data line: *enregistrement type 4
# Orphaned data line: 1 ws-don-4.
# Orphaned data line: 3 ws-4-typ           pic xx value "4A".
# Orphaned data line: 3 ws-4-don           pic x([*b]).
# Orphaned data line: *    3 ws-4-cle           pic x([key,1,1,3]).
# Orphaned data line: *enregistrement type 9
# Orphaned data line: 1 ws-don-9.
# Orphaned data line: 3 ws-9-typ           pic x value "9".
# Orphaned data line: 3 ws-9-nm-base       pic x(6) value "[table,1,1,3]".
# Orphaned data line: 3 ws-9-nm-table      pic x(30) value "[table,1,1,2]".
# Orphaned data line: 3 ws-9-dt-ach        pic 9(8).
# Orphaned data line: 3 ws-9-cpt-ach       pic s9(11) sign leading separate.
# Orphaned data line: 3 ws-9-cpt-5         pic x(12) value "+00000000000".
# Orphaned data line: 1 unloadf              pic 9 value 0.
# Orphaned data line: 88 fin-unload        value 1.
# Orphaned data line: 1 table-null.
# Orphaned data line: 3 tnull              pic x occurs 70 times.
# Orphaned data line: 77 i                    pic 99.
# Orphaned data line: 77 i-buf                pic 99.
# Orphaned data line: 77 i-tot                pic 99.
# Orphaned data line: *------------------ flag ---------------------------
# Orphaned data line: 77 fl-null              pic 9.
# Orphaned data line: *---------------------------------------------------
# Orphaned data line: *---------------- compteur -------------------------
# Orphaned data line: 77 cpt-char             pic 999.
# Orphaned data line: 77 cpt-ach              pic 9(11).
# Orphaned data line: 77 cpt-lu               pic 9(11).
# Orphaned data line: 77 cpt-achf             pic z(10)9.
# Orphaned data line: 77 cpt-luf              pic z(10)9.
# Orphaned data line: *----------------------------------------------------
# Orphaned data line: *------------------ POUR LA DATE ---------------------
# Orphaned data line: 1 dt-i.
# Orphaned data line: 3 aa-i               pic 9(4).
# Orphaned data line: 3 mm-i               pic 99.
# Orphaned data line: 3 jj-i               pic 99.
# Orphaned data line: 1 dt-fr.
# Orphaned data line: 3 jj-fr              pic 99.
# Orphaned data line: 3   pic x value '/'.
# Orphaned data line: 3 mm-fr              pic 99.
# Orphaned data line: 3   pic x value '/'.
# Orphaned data line: 3 aa-fr              pic 9(4).
# Orphaned data line: *------------------------------------------------------
# Orphaned data line: PROCEDURE DIVISION.
# Orphaned data line: *-------------------
# Orphaned data line: 000-main.
# Orphaned data line: open input fic-report fic-descript fic-unload
# Orphaned data line: output fic-format
# Orphaned data line: perform 100-type0 thru 100-exit
# Orphaned data line: perform 101-type1 thru 101-exit
# Orphaned data line: perform 102-type2 thru 102-exit
# Orphaned data line: perform 103-type3 thru 103-exit
# Orphaned data line: perform 104-type4 thru 104-exit
# Orphaned data line: perform 105-type9 thru 105-exit
# Orphaned data line: perform 106-tot thru 106-exit
# Orphaned data line: close fic-report fic-descript fic-unload fic-format
# Orphaned data line: stop run
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 0 ----------------
# Orphaned data line: 100-type0.
# Orphaned data line: accept ws-0-dt-ach from date yyyymmdd
# Orphaned data line: *recherche de la date de cr�ation de la table
# Orphaned data line: perform 200-lec-report thru 200-exit until lgn-rep(4:21)
# Orphaned data line: = 'DD-PROCESS-TIME-STAMP'
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: move lgn-rep(7:2) to ws-0-dt-maj-aa
# Orphaned data line: if ws-0-dt-maj-aa > 90
# Orphaned data line: move 19 to ws-0-dt-maj-ss
# Orphaned data line: else
# Orphaned data line: move 20 to ws-0-dt-maj-ss
# Orphaned data line: end-if
# Orphaned data line: move lgn-rep(10:2) to ws-0-dt-maj-mm
# Orphaned data line: move lgn-rep(13:2) to ws-0-dt-maj-jj
# Orphaned data line: write lgn-for from ws-don-0
# Orphaned data line: 100-exit.
# Orphaned data line: exit.
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 1 -----------------
# Orphaned data line: 101-type1.
# Orphaned data line: move [key,1,1,3] to ws-1-lg-cle
# Orphaned data line: write lgn-for from ws-don-1
# Orphaned data line: 101-exit.
# Orphaned data line: exit.
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 2 -----------------
# Orphaned data line: 102-type2.
# Orphaned data line: perform until lgn-rep(1:7) = 'Columns'
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: end-perform
# Orphaned data line: perform 200-lec-report thru 200-exit 2 times
# Orphaned data line: *localisation de l'emplacement de yes/no pour NULL
# Orphaned data line: move 0 to cpt-char
# Orphaned data line: inspect lgn-rep tallying cpt-char
# Orphaned data line: for characters
# Orphaned data line: before initial 'Allowed'
# Orphaned data line: move cpt-char to i-buf
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: perform 201-lec-descript thru 201-exit 2 times
# Orphaned data line: *localisation du nom du champ
# Orphaned data line: move 0 to cpt-char
# Orphaned data line: inspect lgn-des tallying cpt-char
# Orphaned data line: for characters
# Orphaned data line: before initial 'TION.'
# Orphaned data line: add 6 to cpt-char
# Orphaned data line: perform [table,1,2,1] times
# Orphaned data line: *chargement du nom et de la description des champs
# Orphaned data line: move lgn-des(cpt-char:30) to ws-2-nm-chp
# Orphaned data line: move lgn-des(6:7) to ws-2-typ-chp
# Orphaned data line: move lgn-des(13:10) to ws-2-lg-chp
# Orphaned data line: move lgn-rep to table-null
# Orphaned data line: add 3 to i-buf giving i
# Orphaned data line: move 0 to fl-null
# Orphaned data line: add 2 to i giving i-tot
# Orphaned data line: *recherche [Y] et ensuite [E] pour NULL
# Orphaned data line: perform until i >= i-tot
# Orphaned data line: if tnull(i) = 'Y'
# Orphaned data line: add 1 to i
# Orphaned data line: if tnull(i) = 'E'
# Orphaned data line: move 1 to fl-null
# Orphaned data line: end-if
# Orphaned data line: end-if
# Orphaned data line: add 1 to i
# Orphaned data line: end-perform
# Orphaned data line: if fl-null = 1
# Orphaned data line: move 'NULL' to ws-2-null
# Orphaned data line: else
# Orphaned data line: move space to ws-2-null
# Orphaned data line: end-if
# Orphaned data line: write lgn-for from ws-don-2
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: perform 201-lec-descript thru 201-exit
# Orphaned data line: end-perform
# Orphaned data line: 102-exit.
# Orphaned data line: exit.
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 3 -----------------
# Orphaned data line: 103-type3.
# Orphaned data line: perform until lgn-rep(1:13) = 'Primary Key :'
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: end-perform
# Orphaned data line: *localisation de la cl�
# Orphaned data line: move 0 to cpt-char
# Orphaned data line: inspect lgn-rep tallying cpt-char
# Orphaned data line: for characters
# Orphaned data line: before initial 'PK_'
# Orphaned data line: add 1 to cpt-char
# Orphaned data line: move lgn-rep(cpt-char:30) to ws-3-nm-idx
# Orphaned data line: perform 200-lec-report thru 200-exit 2 times
# Orphaned data line: perform until lgn-rep(1:10) = space
# Orphaned data line: move 0 to cpt-char
# Orphaned data line: inspect lgn-rep tallying cpt-char
# Orphaned data line: for characters
# Orphaned data line: before initial ','
# Orphaned data line: subtract 4 from cpt-char
# Orphaned data line: *chargement du nom de la cl�
# Orphaned data line: move lgn-rep(5:cpt-char) to ws-3-nm-chp
# Orphaned data line: add 7 to cpt-char
# Orphaned data line: *chargement de l'ordre de tri
# Orphaned data line: move lgn-rep(cpt-char:3) to ws-3-tri
# Orphaned data line: write lgn-for from ws-don-3
# Orphaned data line: perform 200-lec-report thru 200-exit
# Orphaned data line: end-perform
# Orphaned data line: 103-exit.
# Orphaned data line: exit.
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 4 -----------------
# Orphaned data line: 104-type4.
# Orphaned data line: perform until fin-unload
# Orphaned data line: perform 202-lec-unload thru 202-exit
# Orphaned data line: if not fin-unload
# Orphaned data line: *chargement de la cl� d'archivage
# Orphaned data line: *d�j� r�p�t� via la jointure!!!!!
# Orphaned data line: *        move lgn-unl ([key,1,1,4]:[key,1,1,3]) to ws-4-cle
# Orphaned data line: write lgn-for from ws-don-4
# Orphaned data line: add 1 to cpt-ach
# Orphaned data line: end-if
# Orphaned data line: end-perform
# Orphaned data line: 104-exit.
# Orphaned data line: exit.
# Orphaned data line: *------------ ENREGISTREMENT DE TYPE 9 -----------------
# Orphaned data line: 105-type9.
# Orphaned data line: accept ws-9-dt-ach from date yyyymmdd
# Orphaned data line: *comteur du nombre d'enregistrement de type 4
# Orphaned data line: move cpt-ach to ws-9-cpt-ach
# Orphaned data line: write lgn-for from ws-don-9
# Orphaned data line: 105-exit.
# Orphaned data line: exit.
# Orphaned data line: *----------------- RAPPORT  -----------------
# Orphaned data line: 106-tot.
# Orphaned data line: move cpt-ach to cpt-achf
# Orphaned data line: move cpt-lu to cpt-luf
# Orphaned data line: move ws-0-dt-ach to dt-i
# Orphaned data line: move aa-i to aa-fr
# Orphaned data line: move mm-i to mm-fr
# Orphaned data line: move jj-i to jj-fr
# Orphaned data line: display "ARCHIFORMAT          RAPPORT          "
# Orphaned data line: dt-fr upon printer
# Orphaned data line: display "Enregistrements lus:" cpt-luf upon printer
# Orphaned data line: display "Enregistrements 4 �crits:" cpt-achf upon printer
# Orphaned data line: 106-exit.
# Orphaned data line: exit.
# Orphaned data line: *--------------- LECTURE DU REPORT --------------
# Orphaned data line: 200-lec-report.
# Orphaned data line: read fic-report
# Orphaned data line: at end
# Orphaned data line: display "fin du report" upon printer
# Orphaned data line: end-read
# Orphaned data line: 200-exit.
# Orphaned data line: exit.
# Orphaned data line: *--------------- LECTURE DU DESCRIPT ------------
# Orphaned data line: 201-lec-descript.
# Orphaned data line: read fic-descript
# Orphaned data line: at end
# Orphaned data line: display "fin de la description" upon printer
# Orphaned data line: end-read
# Orphaned data line: 201-exit.
# Orphaned data line: exit.
# Orphaned data line: *--------------- LECTURE DE L'UNLOAD --------------
# Orphaned data line: 202-lec-unload.
# Orphaned data line: read fic-unload
# Orphaned data line: at end
# Orphaned data line: move 1 to unloadf
# Orphaned data line: not at end
# Orphaned data line: move lgn-unl(1:[*e]) to ws-4-don(1:[*e])
# Orphaned data line: move lgn-unl([*c]:[table,1,2,1])
# Orphaned data line: to ws-4-don([*d]:[table,1,2,1])
# Orphaned data line: add 1 to cpt-lu
# Orphaned data line: end-read
# Orphaned data line: 202-exit.
# Orphaned data line: exit.
Fin
