# Converted from SSG source: CFH-COPY
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("                     06 FILLER PIC  X(" + ($FILLCTR) + ").  ")
  }
}
$Rgv_CASE = 1
# para y2k fixe pos,num,lg 
# para def fixe pos,1  
$YPV = "<"
For ([Int32]$A = 1; $A -le (GetSgsValue ("Y2K")); $A++) { 
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,1,1")) "EqualTo" "FIXE")) {
    $MAXY = (GetSgsValue ("FIXE"))
    For ([Int32]$C = 1; $C -le $MAXY; $C++) { 
      $PAR = "FIXE "
      $NCHA = 1
      For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,$A")); $B++) { 
        $YLG = 4
        $YCH = 1
        If ((CompareTypeSafe (GetSgsValue ("y2k,$a,$B,2")) "GreaterThan" 0)) {
          $YCH = (GetSgsValue ("y2k,$a,b,2"))
        }
        $YPOS = (GetSgsValue ("y2k,$a,$B,1"))
        $YNR = ($ych - 1)
        For ([Int32]$D = $NCHA; $D -le $YNR; $D++) { 
          $PAR = $par + " " + (GetSgsValue ("FIXE,$c,d,1")) + "," + (GetSgsValue ("FIXE,$c,d,2")) + "," + (GetSgsValue ("FIXE,$c,d,3")) + " "
          $NCHA = ($ncha + 1)
        }
        $YTR = (GetSgsValue ("FIXE,$c,ych,3,substr$,$ypos,ylg"))
        If ((CompareTypeSafe $ylg "EqualTo" 2)) {
          If ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 0)) {
            $YAN = "*" + (GetSgsValue ("*ytr,substr$,2,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 1)) {
            $YAN = "_" + (GetSgsValue ("*ytr,substr$,2,1"))
          } else {
            $YAN = $ytr
          }
        } elseif ((CompareTypeSafe $ylg "EqualTo" 4)) {
          If ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 200)) {
            $YAN = $ypv + (GetSgsValue ("*ytr,substr$,4,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 201)) {
            $YAN = "_" + (GetSgsValue ("*ytr,substr$,4,1"))
          } else {
            $YAN = (GetSgsValue ("$YTR,substr$,3,2"))
          }
        }
        $YLS = ($ypos - 1)
        If ((CompareTypeSafe $yls "EqualTo" 0)) {
          $YTR = $yan
        } else {
          $YTR = (GetSgsValue ("FIXE,$c,ych,3,substr$,1,$yls")) + $yan
        }
        $YLS = ($ylg + $YPOS)
        $YLG1 = ((GetSgsValue ("FIXE,$C,$YCH,3,len$")) - ($yls + 1))
        If ((CompareTypeSafe $ylg1 "GreaterThan" 0)) {
          $YTR = $YTR + (GetSgsValue ("FIXE,$c,ych,3,substr$,$yls,ylg1"))
        }
        $PAR = $par + " " + (GetSgsValue ("FIXE,$c,ych,1")) + "," + (GetSgsValue ("FIXE,$c,ych,2")) + "," + $YTR
        $NCHA = ($ncha + 1)
      }
      For ([Int32]$D = $NCHA; $D -le (GetSgsValue ("FIXE,$C")); $D++) { 
        $PAR = $par + " " + (GetSgsValue ("FIXE,$c,d,1")) + "," + (GetSgsValue ("FIXE,$c,d,2")) + "," + (GetSgsValue ("FIXE,$c,d,3")) + " "
      }
      AddTo-SgsList $PAR
    }
    RemoveFrom-SgsList "FIXE" 1 $MAXY
  }
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. 'CFH-COPY'.  ")
DataLineOrNoStatement ("       AUTHOR. MICHEL REVISED BY BOURDEAUD HUY. ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN  TO  CARD-READER. ")
} else {
  DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN  TO  UNISERVO " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
}
If (((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "CARDPUNCH") -or (CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER"))) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
    DataLineOrNoStatement ("           SELECT   TAPEOUT  ASSIGN  TO  PRINTER.   ")
  } else {
    DataLineOrNoStatement ("           SELECT  TAPEOUT  ASSIGN  TO  CARD-PUNCH. ")
  }
} else {
  DataLineOrNoStatement ("           SELECT  TAPEOUT  ASSIGN  TO  MASS-STORAGE " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".")
}
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           SELECT PRINTOUT ASSIGN TO PRINTER.   ")
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("       FD  PRINTOUT ")
    DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
    DataLineOrNoStatement ("           DATA RECORD IS LISTE.")
    DataLineOrNoStatement ("       01  LISTE PIC X(132).")
  }
}
DataLineOrNoStatement ("       FD  TAPEIN   ")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("           REC1" + ($I) + " ")
    }
    DataLineOrNoStatement ("           RECIN.   ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECIN.   ")
  }
  If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
    DataLineOrNoStatement ("       01  RECIN  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").")
  } else {
    DataLineOrNoStatement ("       01  RECIN  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ") DISP-1. ")
  }
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC1" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDIN,1,$I,1")))
      DataLineOrNoStatement ("           06 ZONE" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").  ")
    }
  }
} else {
  DataLineOrNoStatement ("           LABEL  RECORD  STANDARD  ")
  DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "  RECORDS")
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("           REC1" + ($I) + " ")
    }
    DataLineOrNoStatement ("           RECIN.   ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECIN.   ")
  }
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("       01     REC1" + ($I) + ". ")
      DEFINE_FILER ((GetSgsValue ("FIELDIN,1,$I,1")))
      DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").   ")
    }
  }
  DataLineOrNoStatement ("       01  RECIN   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
}
DataLineOrNoStatement ("       FD  TAPEOUT  ")
If (((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "CARDPUNCH") -or (CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER"))) {
  DataLineOrNoStatement ("           LABEL  RECORD OMITTED")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("           REC2" + ($I) + " ")
    }
    If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
        DataLineOrNoStatement ("           REC3" + ($I) + " ")
      }
    }
    If ((CompareTypeSafe (GetSgsValue ("REPRISE")) "GreaterThan" 0)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("REPRISE,1")); $I++) { 
        DataLineOrNoStatement (":         REPRISE-A" + ($I) + " ")
      }
    }
    DataLineOrNoStatement ("           RECOUT.  ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECOUT.  ")
  }
  If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
    DataLineOrNoStatement ("       01  RECOUT  PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
  } else {
    DataLineOrNoStatement ("       01  RECOUT  PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ") DISP-1.   ")
  }
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC2" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
      DataLineOrNoStatement ("           06 ZONO" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "). ")
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("REPRISE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("REPRISE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REPRISE-A" + ($I) + ".   ")
      DEFINE_FILER ((GetSgsValue ("REPRISE,1,$I,1")))
      DataLineOrNoStatement ("           06 REPRISE-AA" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,2"))) + ").")
      DataLineOrNoStatement ("           06 REPRISE-AA1" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,3"))) + ").   ")
      If ((CompareTypeSafe (GetSgsValue ("REPRISE,1,$I,4")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("           06 REPRISE-AA2" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,4"))) + ").   ")
      }
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC3" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIXE,1,$I,1")))
      DataLineOrNoStatement ("           06 FIXDATA" + ($I) + " PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ").  ")
    }
  }
} else {
  DataLineOrNoStatement ("           LABEL  RECORD STANDARD   ")
  DataLineOrNoStatement ("           BLOCK  CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + "  RECORDS  ")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("           REC2" + ($I) + " ")
    }
    If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
        DataLineOrNoStatement ("           REC3" + ($I) + " ")
      }
      If ((CompareTypeSafe (GetSgsValue ("REPRISE")) "GreaterThan" 0)) {
        For ([Int32]$I = 1; $I -le (GetSgsValue ("REPRISE,1")); $I++) { 
          DataLineOrNoStatement ("           REPRISE-A" + ($I))
        }
      }
    }
    DataLineOrNoStatement ("           RECOUT.  ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECOUT.  ")
  }
  DataLineOrNoStatement ("       01  RECOUT   PIC   X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC2" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
      DataLineOrNoStatement ("           06 ZONO" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "). ")
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("REPRISE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("REPRISE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REPRISE-A" + ($I) + ".   ")
      DEFINE_FILER ((GetSgsValue ("REPRISE,1,$I,1")))
      DataLineOrNoStatement ("           06 REPRISE-AA" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,2"))) + ").")
      DataLineOrNoStatement ("           06 REPRISE-AA1" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,3"))) + ").   ")
      If ((CompareTypeSafe (GetSgsValue ("REPRISE,1,$I,4")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("           06 REPRISE-AA2" + ($I) + " PIC X(" + ((GetSgsValue ("REPRISE,1,$I,4"))) + ").   ")
      }
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC3" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIXE,1,$I,1")))
      DataLineOrNoStatement ("           06 FIXDATA" + ($I) + " PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ").  ")
    }
  }
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  NB-LUS   PIC   9(10)  COMP  VALUE 0. ")
If ((GetSgsValue ("MAXCOPY"))) {
  DataLineOrNoStatement ("       01  COPY-LIMIT         PIC 9(10) VALUE " + ((GetSgsValue ("MAXCOPY,1,1,1"))) + ".  ")
}
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("       01  TITLE-LINE         USAGE DISP-1. ")
  } else {
    DataLineOrNoStatement ("       01  TITLE-LINE.  ")
  }
  DataLineOrNoStatement ("           03  FILLER         PIC X(4) VALUE 'H,,,'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(5)  VALUE SPACES.   ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(12) VALUE '" + ((GetSgsValue ("INPUT,1,1,1"))) + "'.  ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(13) VALUE ' TO PRINTER '.   ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  # '.  
  DataLineOrNoStatement ("           03  FILLER         PIC X(5)  VALUE '12")
}
If ((CompareTypeSafe (GetSgsValue ("SUPCOM")) "EqualTo" 0)) {
} else {
  DataLineOrNoStatement ("       01  RECW.")
  DataLineOrNoStatement ("           02 RECW1   PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + "). ")
  DataLineOrNoStatement ("           02 RECW2  REDEFINES RECW1.   ")
  DataLineOrNoStatement ("               03  RECW3  OCCURS " + ((GetSgsValue ("INPUT,1,1,2"))) + ". ")
  DataLineOrNoStatement ("                    04  RECW4  PICTURE X.   ")
}
If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
    DataLineOrNoStatement ("       01  TAB1" + ($I) + ".")
    If ((CompareTypeSafe (GetSgsValue ("FIXE,1,$I,3")) "EqualTo" "SPACES ;")) {
      DataLineOrNoStatement ("               OR  " + ((GetSgsValue ("FIXE,1,$I,3"))) + "  =  SPACE   ")
      DataLineOrNoStatement ("           06  FIXED" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ")  VALUE SPACES.   ")
    } else {
      If ((CompareTypeSafe (GetSgsValue ("FIXE,1,$I,3")) "EqualTo" "ZEROES ;")) {
        DataLineOrNoStatement ("               OR  " + ((GetSgsValue ("FIXE,1,$I,3"))) + "  =  ZERO ;  ")
        DataLineOrNoStatement ("               OR  " + ((GetSgsValue ("FIXE,1,$I,3"))) + "  =  ZEROS   ")
        DataLineOrNoStatement ("           06  FIXED" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ")  VALUE ZEROES.   ")
      } else {
        DataLineOrNoStatement ("           06  FIXED" + ($I) + " PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ")")
        DataLineOrNoStatement ("           VALUE '" + ((GetSgsValue ("FIXE,1,$I,3"))) + "'.")
      }
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("FIXE,1,1,3")) "EqualTo" "NUM")) {
  DataLineOrNoStatement ("       01  COUNT.   ")
  DataLineOrNoStatement ("           03 COUNTING PIC S9(" + ((GetSgsValue ("FIXE,1,1,2"))) + ")  VALUE 0.   ")
  DataLineOrNoStatement ("           03 COUNTER PIC S9(" + ((GetSgsValue ("FIXE,1,1,2"))) + ") VALUE " + ((GetSgsValue ("FIXE,1,1,4"))) + ".  ")
}
DataLineOrNoStatement ("       01   SWITCHES.   ")
DataLineOrNoStatement ("           03  REC-SKIPPED  PIC  S9(6) VALUE ZEROES.")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   ")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           OPEN OUTPUT  PRINTOUT.   ")
  }
}
DataLineOrNoStatement ("           OPEN INPUT TAPEIN.   ")
DataLineOrNoStatement ("           OPEN  OUTPUT  TAPEOUT.   ")
DataLineOrNoStatement ("       LECT.")
DataLineOrNoStatement ("           MOVE SPACES TO RECOUT.   ")
DataLineOrNoStatement ("           READ  TAPEIN  AT  END  GO TO  FINW.  ")
If ((CompareTypeSafe (GetSgsValue ("SUPCOM")) "EqualTo" 0)) {
} else {
  DataLineOrNoStatement ("           MOVE  RECIN  TO RECW.")
  DataLineOrNoStatement ("           IF  RECW4 (7) = '*' GO TO LECT.  ")
}
If ((CompareTypeSafe (GetSgsValue ("REPSIM")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       REPSIM.  ")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
} else {
  DataLineOrNoStatement ("           MOVE RECIN TO RECOUT.")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
    DataLineOrNoStatement ("           MOVE                ZONE" + ($I) + " TO ZONO" + ($I) + ".")
  }
}
If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("FIXE,1,1,3")) "EqualTo" "NUM")) {
    DataLineOrNoStatement ("           ADD COUNTER TO COUNTING. ")
    DataLineOrNoStatement ("           MOVE COUNTING TO FIXED" + ((GetSgsValue ("*1"))) + ".  ")
  }
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
    If ((CompareTypeSafe (GetSgsValue ("FIXE,1,$I,3")) "EqualTo" "ZONE")) {
      DataLineOrNoStatement ("           ENTER  SST60  SUBROUTINE REFERENCING '-' FIXDATA" + ($I) + ".")
    } else {
      DataLineOrNoStatement ("           MOVE                  FIXED" + ($I) + " TO FIXDATA" + ($I) + ".  ")
      DataLineOrNoStatement ("           EXAMINE FIXDATA" + ($I) + " REPLACING ALL '<' BY ';'.")
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           WRITE LISTE  FROM RECOUT.")
  }
}
DataLineOrNoStatement ("           ADD 1  TO NB-LUS.")
If ((CompareTypeSafe (GetSgsValue ("STARTFIELD")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  ZONE2  <  " + ((GetSgsValue ("STARTFIELD,1,1,1"))) + " ")
  DataLineOrNoStatement ("           ADD 1  TO REC-SKIPPED")
  DataLineOrNoStatement ("           GO TO LECT.  ")
}
If ((CompareTypeSafe (GetSgsValue ("STARTREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  NB-LUS  <  " + ((GetSgsValue ("STARTREC,1,1,1"))) + "  ")
  DataLineOrNoStatement ("           ADD 1  TO REC-SKIPPED")
  DataLineOrNoStatement ("           GO TO LECT.  ")
}
If ((CompareTypeSafe (GetSgsValue ("REPRISE")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("REPRISE,1")); $I++) { 
    If ((CompareTypeSafe (GetSgsValue ("REPRISE,1,$I,4")) "GreaterThan" 0)) {
      DataLineOrNoStatement ("           IF REPRISE-AA1" + ($I) + "  = SPACES MOVE SPACES TO REPRISE-AA2" + ($I) + ". ")
    }
    DataLineOrNoStatement ("           IF REPRISE-AA1" + ($I) + " = SPACES MOVE SPACES TO REPRISE-AA" + ($I) + ".   ")
  }
}
DataLineOrNoStatement ("           WRITE RECOUT.")
If ((GetSgsValue ("MAXCOPY"))) {
  DataLineOrNoStatement ("           IF  NB-LUS  NOT <  COPY-LIMIT  GO TO FINW.   ")
}
If ((CompareTypeSafe (GetSgsValue ("REPSIM")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  NB-LUS  =  " + ((GetSgsValue ("REPSIM,1,1,1"))))
  DataLineOrNoStatement ("           GO TO FINW   ")
  DataLineOrNoStatement ("           ELSE  GO TO REPSIM.  ")
}
DataLineOrNoStatement ("           GO TO LECT.  ")
DataLineOrNoStatement ("       FINW.")
DataLineOrNoStatement ("           DISPLAY  '*CFH-COPY  FIN*'  UPON  PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY  '*NB-ENREG-LUS ='  NB-LUS  UPON  PRINTER.   ")
DataLineOrNoStatement ("           CLOSE  TAPEIN.   ")
DataLineOrNoStatement ("           CLOSE  TAPEOUT.  ")
DataLineOrNoStatement ("           DISPLAY  REC-SKIPPED  UPON  PRINTER. ")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           CLOSE PRINTOUT.  ")
  }
}
DataLineOrNoStatement ("           STOP RUN.")
# @MAP N     ASSURFED*UTILITTEST.MAP,TPF$.CFH-COPY
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITTEST\MAP")
Fin
