# Converted from SSG source: CONDIS2_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

#............................................  
#  VERIFICATION DES CARTES SGS 
#............................................  
$FLAGABORT = 0
$NOCASE = 0
$NOOTHER = 0
$NOMOVE = 0
$NOCONST = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE")) {
    $NOCASE = ($NOCASE + 1)
    If (((CompareTypeSafe $NOCASE "NotEqualTo" 1) -and ((CompareTypeSafe $NOMOVE "EqualTo" 0) -and (CompareTypeSafe $NOCONST "EqualTo" 0)))) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   UNE CARTE PG du genre CASE (condition)     -") '([LogMessageType]::Information)'
      Log-Message ("   DOIT ETRE TOUJOURS ETRE SUIVIE             -") '([LogMessageType]::Information)'
      Log-Message ("   D UNE CARTE PG DU GENRE                    -") '([LogMessageType]::Information)'
      Log-Message ("             - MOVE                           -") '([LogMessageType]::Information)'
      Log-Message ("     (et/ou) - CONST                          -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    } else {
      $NOMOVE = 0
      $NOCONST = 0
    }
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "OTHERWISE")) {
    $NOOTHER = ($NOOTHER + 1)
    If ((CompareTypeSafe $CASE "EqualTo" 0)) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   IL FAUT DES CARTES CASE AVANT UNE CARTE    -") '([LogMessageType]::Information)'
      Log-Message ("             OTHERWISE                        -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    }
    If ((CompareTypeSafe $NOOTHER "GreaterThan" 1)) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ON NE PEUT AVOIR QU UNE CARTE PG GU GENRE  -") '([LogMessageType]::Information)'
      Log-Message ("             OTHERWISE                        -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    }
    If (((CompareTypeSafe $NOMOVE "EqualTo" 0) -and (CompareTypeSafe $NOCONST "EqualTo" 0))) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   UNE CARTE PG du genre CASE (condition)     -") '([LogMessageType]::Information)'
      Log-Message ("   DOIT ETRE TOUJOURS ETRE SUIVIE             -") '([LogMessageType]::Information)'
      Log-Message ("   D UNE CARTE PG DU GENRE                    -") '([LogMessageType]::Information)'
      Log-Message ("             - MOVE                           -") '([LogMessageType]::Information)'
      Log-Message ("     (et/ou) - CONST                          -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    }
    $NOMOVE = 0
    $NOCONST = 0
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "MOVE")) {
    $NOMOVE = ($NOMOVE + 1)
    If ((CompareTypeSafe $NOMOVE "GreaterThan" 1)) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   IL Y A PLUS D UNE CARTE PG DU GENRE        -") '([LogMessageType]::Information)'
      Log-Message ("             - MOVE                           -") '([LogMessageType]::Information)'
      Log-Message ("   APRES UNE CONDITION  (CASE OU OTHERWISE)   -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    }
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CONST")) {
    $NOCONST = ($NOCONST + 1)
    If ((CompareTypeSafe $NOCONST "GreaterThan" 1)) {
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      Log-Message ("   IL Y A PLUS D UNE CARTE PG DU GENRE        -") '([LogMessageType]::Information)'
      Log-Message ("             - CONST                          -") '([LogMessageType]::Information)'
      Log-Message ("   APRES UNE CONDITION  (CASE OU OTHERWISE)   -") '([LogMessageType]::Information)'
      Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
      $FLAGABORT = 1
    }
  } else {
    Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
    Log-Message ("   ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR  -") '([LogMessageType]::Information)'
    Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
    Log-Message ("   UNE CARTE PG CONTIENT UNE CLAUSE AUTRE QUE -") '([LogMessageType]::Information)'
    Log-Message ("             - CASE                           -") '([LogMessageType]::Information)'
    Log-Message ("             - MOVE                           -") '([LogMessageType]::Information)'
    Log-Message ("             - CONST                          -") '([LogMessageType]::Information)'
    Log-Message ("             - OTHERWISE                      -") '([LogMessageType]::Information)'
    Log-Message ("-----------------------------------------------") '([LogMessageType]::Information)'
    $FLAGABORT = 1
  }
}
If ((GetSgsValue ("ASCII"))) {
  # @ACOB IE  condis2,.condis2  
  Call-ExternalProgram "ACOB" "I, E" ("condis2")
  Fin
} else {
  # @ACOB ITE  condis2,.condis2 
  Call-ExternalProgram "ACOB" "I, T, E" ("condis2")
  Fin
}
DataLineOrNoStatement ("      ***------------------------------------------------------------***")
DataLineOrNoStatement ("      ***                    -- CONDIS2 --  ")
DataLineOrNoStatement ("      ***              UTILITAIRE - CFH-COPY CONDITIONNEL            ***")
DataLineOrNoStatement ("      ***------------------------------------------------------------***")
DataLineOrNoStatement ("      * Type     : UTILITAIRE TRANSFERT DE ZONES CONDITIONNEL          *")
DataLineOrNoStatement ("      * Analyste : SABLON                          (INITIALES)         *")
DataLineOrNoStatement ("      * Auteur   : SABLON                                              *")
DataLineOrNoStatement ("      * Release  : 01                              (99)                *")
DataLineOrNoStatement ("      * VersIon  : 001                             (999)               *")
DataLineOrNoStatement ("      *----------------------------------------------------------------*")
DataLineOrNoStatement ("      * ModIfIcatIons :                                                *")
DataLineOrNoStatement ("      * QuI ?  Quand ?     QuoI ?                             Projet/Ph*")
DataLineOrNoStatement ("      * _____  __/__/____  _________________________________  ______/__*")
DataLineOrNoStatement ("      * _____  __/__/____  _________________________________  ______/__*")
DataLineOrNoStatement ("      * _____  __/__/____  _________________________________  ______/__*")
DataLineOrNoStatement ("      * _____  __/__/____  _________________________________  ______/__*")
DataLineOrNoStatement ("      ***------------------------------------------------------------***")
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("      **************************")
DataLineOrNoStatement ("       PROGRAM-ID.  CONDIS2.")
DataLineOrNoStatement ("      *-----------* ")
DataLineOrNoStatement ("      / ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("      **********************")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("      *======================*  ")
DataLineOrNoStatement ("       SOURCE-COMPUTER.  UNIVAC-1110.   ")
DataLineOrNoStatement ("      *----------------*")
DataLineOrNoStatement ("       OBJECT-COMPUTER.  UNIVAC-1110.   ")
DataLineOrNoStatement ("      *----------------*")
DataLineOrNoStatement ("       SPECIAL-NAMES.   ")
DataLineOrNoStatement ("           PRINTER IS PRINER.   ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT FILEIN ASSIGN TO DISC FILEIN. ")
DataLineOrNoStatement ("           SELECT FILEOUT ASSIGN TO DISC FILEOUT.   ")
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("      ****************  ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("      *------------*")
DataLineOrNoStatement ("       FD  FILEIN   ")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("FILEIN,1,1,2"))) + " RECORDS")
DataLineOrNoStatement ("               RECORD CONTAINS " + ((GetSgsValue ("FILEIN,1,1,1"))) + " CHARACTERS")
DataLineOrNoStatement ("               LABEL RECORD STANDARD")
DataLineOrNoStatement ("               DATA RECORD IS FSINPUT.  ")
DataLineOrNoStatement ("       01  FSINPUT. ")
DataLineOrNoStatement ("            02   FILLER    PIC X(" + ((GetSgsValue ("FILEIN,1,1,1"))) + ").   ")
DataLineOrNoStatement ("       FD  FILEOUT  ")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("FILEOUT,1,1,2"))) + " RECORDS   ")
DataLineOrNoStatement ("               RECORD CONTAINS " + ((GetSgsValue ("FILEOUT,1,1,1"))) + " CHARACTERS   ")
DataLineOrNoStatement ("               LABEL RECORD STANDARD")
DataLineOrNoStatement ("               DATA RECORD IS FSOUTPUT. ")
DataLineOrNoStatement ("       01  FSOUTPUT.")
DataLineOrNoStatement ("           02   FILLER     PIC X(" + ((GetSgsValue ("FILEOUT,1,1,1"))) + ").  ")
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("      ************************* ")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22A-200X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22A-201X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22A-202X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22A-203X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22B-200X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22B-201X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22B-202X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-22B-203X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66A-200X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66A-201X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66A-202X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66A-203X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66B-200X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66B-201X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66B-202X      PIC X.")
DataLineOrNoStatement ("       01  WS-RECORD-TRANSFORME-66B-203X      PIC X.")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22A-200X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22A-201X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22A-202X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22A-203X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22B-200X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22B-201X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22B-202X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-22B-203X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66A-200X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66A-201X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66A-202X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66A-203X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66B-200X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66B-201X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66B-202X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-TRANSFORME-66B-203X      PIC 9(6).")
DataLineOrNoStatement ("       01  NB-REC-LU                PIC 9(6).   ")
DataLineOrNoStatement ("       01  NB-REC-ECRIT             PIC 9(6).   ")
DataLineOrNoStatement ("       01  NB-REC-OTHER             PIC 9(6).   ")
DataLineOrNoStatement ("       01  NB-REC-NONECRIT          PIC 9(6).   ")
DataLineOrNoStatement ("       01  WS-A6.   ")
DataLineOrNoStatement ("           02 WS-A6-YY. ")
DataLineOrNoStatement ("              03 WS-A6-Y1           PIC X(01).  ")
DataLineOrNoStatement ("              03 WS-A6-Y2           PIC X(01).  ")
DataLineOrNoStatement ("           02 WS-A6-MM              PIC X(02).  ")
DataLineOrNoStatement ("           02 WS-A6-JJ              PIC X(02).  ")
DataLineOrNoStatement ("       01  WS-A8.   ")
DataLineOrNoStatement ("           02 WS-A8-YYY.")
DataLineOrNoStatement ("              03 WS-A8-SS           PIC X(02).  ")
DataLineOrNoStatement ("              03 FILLER             PIC X(01).  ")
DataLineOrNoStatement ("           02 WS-A8-Y4              PIC X(01).  ")
DataLineOrNoStatement ("           02 WS-A8-MM              PIC X(02).  ")
DataLineOrNoStatement ("           02 WS-A8-JJ              PIC X(02).  ")
DataLineOrNoStatement ("       01  WS-A8-BIS REDEFINES WS-A8.   ")
DataLineOrNoStatement ("           02 ws-a8-yy              pic x(02).  ")
DataLineOrNoStatement ("           02 ws-a8-yymmjj          PIC X(06).  ")
DataLineOrNoStatement ("       01  WS-A4.   ")
DataLineOrNoStatement ("           02 WS-A4-SS              PIC X(02).  ")
DataLineOrNoStatement ("           02 WS-A4-AA. ")
DataLineOrNoStatement ("              03 WS-A4-A1           PIC X(01).  ")
DataLineOrNoStatement ("              03 WS-A4-A2           PIC X(01).  ")
DataLineOrNoStatement ("       01  WS-A2.   ")
DataLineOrNoStatement ("              03 WS-A2-A1           PIC X(01).  ")
DataLineOrNoStatement ("              03 WS-A2-A2           PIC X(01).  ")
DataLineOrNoStatement ("       01  NB-REC-CASE-0            PIC 9(6).   ")
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE")) {
    $NOCASE = ($NOCASE + 1)
    DataLineOrNoStatement ("       01  NB-REC-CASE-" + ($NOCASE) + "    PIC 9(6).   ")
  }
}
DataLineOrNoStatement ("       01  ENR-INPUT.   ")
DataLineOrNoStatement ("              03  FILLER                PIC X(" + ((GetSgsValue ("FILEIN,1,1,1"))) + ").  ")
#----------------------------------------------------------------- 
# enregistrement input 
#----------------------------------------------------------------- 
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  #  
  # cas du case  
  #  
  If (((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE") -or (CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "OTHERWISE"))) {
    $NOCASE = ($NOCASE + 1)
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("       01  ENR-CASE-" + ($NOCASE) + "-" + ($K) + "       REDEFINES ENR-INPUT.   ")
      $L1 = ((GetSgsValue ("PG,$I,$J,1")) - 1)
      If ((CompareTypeSafe $L1 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L1) + ").")
      }
      DataLineOrNoStatement ("           03 CASE-" + ($NOCASE) + "-" + ($K) + "  PIC X(" + ((GetSgsValue ("PG,$I,$J,2"))) + ").   ")
      $L2 = ((GetSgsValue ("FILEIN,1,1,1")) - ((GetSgsValue ("PG,$I,$J,1")) - ((GetSgsValue ("PG,$I,$J,2")) + 1)))
      If ((CompareTypeSafe $L2 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L2) + ").")
      }
    }
    #  
    # cas du move  
    #  
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "MOVE")) {
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("       01  ENRIN-MOVE-" + ($NOCASE) + "-" + ($K) + "   REDEFINES ENR-INPUT. ")
      $L1 = ((GetSgsValue ("PG,$I,$J,1")) - 1)
      If ((CompareTypeSafe $L1 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L1) + ").")
      }
      If ((GetSgsValue ("PG,$I,$J,4"))) {
        If (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D42") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 4))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(04).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D24") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D86") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 8))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(08).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D68") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).   ")
        } else {
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          Log-Message ("  ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR     ") '([LogMessageType]::Information)'
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          Log-Message (" CONTRADICTION ENTRE LA LONGUEUR DuUNE ZONE     ") '([LogMessageType]::Information)'
          Log-Message ("  ET SA DECLARATION EN DATE                     ") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D42 ---> la date input est en 4 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D24 ---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D22A---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D22B---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D68 ---> la date input est en 6 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D86 ---> la date input est en 8 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D66A---> la date input est en 6 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D66B---> la date input est en 6 pos") '([LogMessageType]::Information)'
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          $FLAGABORT = 1
        }
      } else {
        DataLineOrNoStatement ("           03 MOVEIN-" + ($NOCASE) + "-" + ($K) + "  PIC X(" + ((GetSgsValue ("PG,$I,J,2"))) + "). ")
      }
      $L2 = ((GetSgsValue ("FILEIN,1,1,1")) - ((GetSgsValue ("PG,$I,$J,1")) - ((GetSgsValue ("PG,$I,$J,2")) + 1)))
      If ((CompareTypeSafe $L2 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L2) + ").")
      }
    }
  }
}
DataLineOrNoStatement ("       01  ENR-OUTPUT.  ")
DataLineOrNoStatement ("              03  FILLER                PIC X(" + ((GetSgsValue ("FILEOUT,1,1,1"))) + "). ")
#  
# enregistrement output
#  
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  #  
  # cas du case  
  #  
  If (((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE") -or (CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "OTHERWISE"))) {
    $NOCASE = ($NOCASE + 1)
    #  
    # cas du move  
    #  
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "MOVE")) {
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("       01  ENROUT-MOVE-" + ($NOCASE) + "-" + ($K) + "   REDEFINES ENR-OUTPUT.   ")
      $L1 = ((GetSgsValue ("PG,$I,$J,3")) - 1)
      If ((CompareTypeSafe $L1 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L1) + ").")
      }
      If ((GetSgsValue ("PG,$I,$J,4"))) {
        If (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D42") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 4))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "       PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D24") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "       PIC X(04).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "       PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "       PIC X(02).   ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).  ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).  ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D86") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 8))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "    PIC X(06).  ")
        } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D68") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
          DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "    PIC X(08).  ")
        } else {
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          Log-Message ("  ERREUR ERREUR ERREUR ERREUR ERREUR ERREUR     ") '([LogMessageType]::Information)'
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          Log-Message (" CONTRADICTION ENTRE LA LONGUEUR D'UNE"), ("ZONE"), ("") '([LogMessageType]::Information)'
          Log-Message ("  ET SA DECLARATION EN DATE                     ") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D42 ---> la date input est en 4 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D24 ---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D22A---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("  SI PARAM = D22B---> la date input est en 2 pos") '([LogMessageType]::Information)'
          Log-Message ("------------------------------------------------") '([LogMessageType]::Information)'
          $FLAGABORT = 1
        }
      } else {
        DataLineOrNoStatement ("           03 MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  PIC X(" + ((GetSgsValue ("PG,$I,J,2"))) + ").")
      }
      If (((CompareTypeSafe (GetSgsValue ("PG,$I,$J,4")) "EqualTo" "D42") -and (CompareTypeSafe (GetSgsValue ("PG,$I,$J,2")) "EqualTo" 4))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (2 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D24") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (4 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (2 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 2))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (2 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66A") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (6 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66B") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (6 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D86") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 8))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (6 + 1)))
      } elseif (((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D68") -and (CompareTypeSafe (GetSgsValue ("PG,$I,J,2")) "EqualTo" 6))) {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - (8 + 1)))
      } else {
        $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,J,3")) - ((GetSgsValue ("PG,$I,J,2")) + 1)))
      }
      If ((CompareTypeSafe $L2 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L2) + ").")
      }
    }
    #  
    # cas du const 
    #  
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CONST")) {
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("       01  ENROUT-CONST-" + ($NOCASE) + "-" + ($K) + "   REDEFINES ENR-OUTPUT.  ")
      $L1 = ((GetSgsValue ("PG,$I,$J,1")) - 1)
      If ((CompareTypeSafe $L1 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L1) + ").")
      }
      DataLineOrNoStatement ("           03 CONST-" + ($NOCASE) + "-" + ($K) + "  PIC X(" + ((GetSgsValue ("PG,$I,$J,2"))) + ").  ")
      $L2 = ((GetSgsValue ("FILEOUT,1,1,1")) - ((GetSgsValue ("PG,$I,$J,1")) - ((GetSgsValue ("PG,$I,$J,2")) + 1)))
      If ((CompareTypeSafe $L2 "GreaterThan" 0)) {
        DataLineOrNoStatement ("           03 FILLER                   PIC X(" + ($L2) + ").")
      }
    }
  }
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("      ********************  ")
DataLineOrNoStatement ("       DEBUT.   ")
DataLineOrNoStatement ("           OPEN INPUT  FILEIN   ")
DataLineOrNoStatement ("                OUTPUT FILEOUT. ")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-LU. ")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-ECRIT.  ")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-NONECRIT.   ")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22A-200X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22A-201X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22A-202X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22A-203X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22B-200X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22B-201X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22B-202X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-22B-203X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66A-200X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66A-201X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66A-202X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66A-203X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66B-200X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66B-201X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66B-202X.")
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-TRANSFORME-66B-203X.")
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE")) {
    $NOCASE = ($NOCASE + 1)
    DataLineOrNoStatement ("           MOVE 0 TO NB-REC-CASE-" + ($NOCASE) + ". ")
  }
}
DataLineOrNoStatement ("           MOVE 0 TO NB-REC-OTHER.  ")
DataLineOrNoStatement ("       TRT. ")
DataLineOrNoStatement ("           READ FILEIN INTO ENR-INPUT AT END GO TO FIN-TRT. ")
DataLineOrNoStatement ("           MOVE SPACES TO ENR-OUTPUT.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22A-200X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22A-201X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22A-202X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22A-203X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22B-200X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22B-201X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22B-202X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-22B-203X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66A-200X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66A-201X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66A-202X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66A-203X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66B-200X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66B-201X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66B-202X.   ")
DataLineOrNoStatement ("           MOVE 'N' TO WS-RECORD-TRANSFORME-66B-203X.   ")
DataLineOrNoStatement ("           ADD 1 TO NB-REC-LU.  ")
#  
# les conditions   
#  
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  #  
  # cas du case  
  #  
  If ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE")) {
    $NOCASE = ($NOCASE + 1)
    If ((CompareTypeSafe $NOCASE "NotEqualTo" 1)) {
      $K = ($NOCASE - 1)
      DataLineOrNoStatement ("              ADD 1 TO NB-REC-CASE-" + ($K) + " ")
      DataLineOrNoStatement ("              PERFORM WRITE-REC-OUTPUT THRU WRITE-REC-OUTPUT-EXIT   ")
      DataLineOrNoStatement ("              GO TO TRT.")
    }
    DataLineOrNoStatement ("       CASE-" + ($NOCASE) + ".  ")
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("           IF CASE-" + ($NOCASE) + "-" + ($K) + " = '" + ((GetSgsValue ("PG,$I,$J,3"))) + "'")
    }
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "OTHERWISE")) {
    $NOCASE = ($NOCASE + 1)
    If ((CompareTypeSafe $NOCASE "NotEqualTo" 1)) {
      $K = ($NOCASE - 1)
      DataLineOrNoStatement ("              ADD 1 TO NB-REC-CASE-" + ($K) + " ")
      DataLineOrNoStatement ("              PERFORM WRITE-REC-OUTPUT THRU WRITE-REC-OUTPUT-EXIT   ")
      DataLineOrNoStatement ("              GO TO TRT.")
    }
    DataLineOrNoStatement ("       OTHER.   ")
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "MOVE")) {
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      If ((GetSgsValue ("PG,$I,$J,4"))) {
        If ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D24")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A2   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-2-4  THRU TRANSFO-DATE-2-4-EXIT  ")
          DataLineOrNoStatement ("              MOVE WS-A4 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D42")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A4   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-4-2 THRU TRANSFO-DATE-4-2-EXIT   ")
          DataLineOrNoStatement ("              MOVE WS-A2 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22A")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A2   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-22A THRU TRANSFO-DATE-22A-EXIT   ")
          DataLineOrNoStatement ("              MOVE WS-A2 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D22B")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A2   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-22B THRU TRANSFO-DATE-22B-EXIT   ")
          DataLineOrNoStatement ("              MOVE WS-A2 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66A")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A6   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-66A THRU TRANSFO-DATE-66A-EXIT   ")
          DataLineOrNoStatement ("              MOVE WS-A6 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D66B")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A6   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-66B THRU TRANSFO-DATE-66B-EXIT   ")
          DataLineOrNoStatement ("              MOVE WS-A6 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D68")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A6   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-68  THRU TRANSFO-DATE-68-EXIT")
          DataLineOrNoStatement ("              MOVE WS-A8 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,J,4")) "EqualTo" "D86")) {
          DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO WS-A8   ")
          DataLineOrNoStatement ("              PERFORM TRANSFO-DATE-86 THRU TRANSFO-DATE-86-EXIT ")
          DataLineOrNoStatement ("              MOVE WS-A6 TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
        }
      } else {
        DataLineOrNoStatement ("              MOVE MOVEIN-" + ($NOCASE) + "-" + ($K) + " TO MOVEOUT-" + ($NOCASE) + "-" + ($K) + "  ")
      }
    }
  } elseif ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CONST")) {
    For ([Int32]$J = 2; $J -le (GetSgsValue ("PG,$I")); $J++) { 
      $K = ($J - 1)
      DataLineOrNoStatement ("              MOVE '" + ((GetSgsValue ("PG,$I,$J,3"))) + "' TO CONST-" + ($NOCASE) + "-" + ($K) + " ")
    }
  }
}
# -----------------------------------------------------
If ((CompareTypeSafe $NOOTHER "EqualTo" 0)) {
  DataLineOrNoStatement ("              ADD 1 TO NB-REC-CASE-" + ($NOCASE))
  DataLineOrNoStatement ("              PERFORM WRITE-REC-OUTPUT THRU WRITE-REC-OUTPUT-EXIT   ")
  DataLineOrNoStatement ("              GO TO TRT.")
} else {
  DataLineOrNoStatement ("              ADD 1 TO NB-REC-OTHER ")
  DataLineOrNoStatement ("              PERFORM WRITE-REC-OUTPUT THRU WRITE-REC-OUTPUT-EXIT   ")
  DataLineOrNoStatement ("              GO TO TRT.")
}
DataLineOrNoStatement ("       CASE-NON-PREVU.  ")
DataLineOrNoStatement ("      *    pas d'ecriture sur le fichier de sortie .....")
DataLineOrNoStatement ("           GO TO TRT.   ")
DataLineOrNoStatement ("       FIN-TRT. ")
DataLineOrNoStatement ("           DISPLAY 'NB ENREGISTREMENTS LUS    = ' NB-REC-LU ")
DataLineOrNoStatement ("                                UPON PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY 'NB ENREGISTREMENTS ECRITS = ' NB-REC-ECRIT  ")
DataLineOrNoStatement ("                                UPON PRINTER.   ")
DataLineOrNoStatement ("           SUBTRACT NB-REC-ECRIT FROM NB-REC-LU GIVING NB-REC-NONECRIT. ")
DataLineOrNoStatement ("           IF NB-REC-NONECRIT > 0   ")
DataLineOrNoStatement ("              DISPLAY '*******************************' UPON PRINTER")
DataLineOrNoStatement ("              DISPLAY '*   attention                 *' UPON PRINTER")
DataLineOrNoStatement ("              DISPLAY '*   certains records ne       *' UPon printer")
DataLineOrNoStatement ("              DISPLAY '*   respectent aucun case     *' UPON PRInter")
DataLineOrNoStatement ("              DISPLAY '*   et ne figurent donc pas   *' UPON PRInter")
DataLineOrNoStatement ("              DISPLAY '*   sur le fichier output     *' UPON PRInter")
DataLineOrNoStatement ("              DISPLAY '*******************************' UPON PRINTER.   ")
$NOCASE = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("PG")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("PG,$I,1,1")) "EqualTo" "CASE")) {
    $NOCASE = ($NOCASE + 1)
    DataLineOrNoStatement ("           DISPLAY 'NB ENREGISTREMENTS CONDITION NO " + ($NOCASE) + " = '   ")
    DataLineOrNoStatement ("                   NB-REC-CASE-" + ($NOCASE) + "   UPON PRINTER.")
  }
}
DataLineOrNoStatement ("           DISPLAY 'NB ENREGISTREMENTS OTHER = ' NB-REC-OTHER   ")
DataLineOrNoStatement ("                                                UPON PRINTER.   ")
DataLineOrNoStatement ("           display ' ' upon printer.")
DataLineOrNoStatement ("           display ' ' upon printer.")
DataLineOrNoStatement ("           display ' ' upon printer.")
DataLineOrNoStatement ("           display ' ' upon printer.")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22A) 0X --> ;X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22A-200X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22A) 1X --> _X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22A-201X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22A) 2X --> |X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22A-202X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22A) 3X --> ~X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22A-203X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22B) ;X --> 0X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22B-200X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22B) _X --> 1X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22B-201X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22B) |X --> 2X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22B-202X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (22B) ~X --> 3X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-22B-203X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66A) 0X --> ;X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66A-200X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66A) 1X --> _X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66A-201X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66A) 2X --> |X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66A-202X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66A) 3X --> ~X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66A-203X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66B) ;X --> 0X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66B-200X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66B) _X --> 1X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66B-201X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66B) |X --> 2X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66B-202X UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NB RECORDS AYANT SUBI TRANSFO (66B) ~X --> 3X    = '")
DataLineOrNoStatement ("                   NB-REC-TRANSFORME-66B-203X UPON PRINTER. ")
DataLineOrNoStatement ("           CLOSE FILEIN FILEOUT.")
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       TRANSFO-DATE-4-2.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           MOVE WS-A4-AA TO WS-A2.  ")
DataLineOrNoStatement ("           IF ((WS-A4 > '1999') AND (WS-A4 < '2010'))   ")
DataLineOrNoStatement ("              MOVE ';' TO WS-A2-A1. ")
DataLineOrNoStatement ("           IF ((WS-A4 > '2009') AND (WS-A4 < '2020'))   ")
DataLineOrNoStatement ("              MOVE '_' TO WS-A2-A1. ")
DataLineOrNoStatement ("           IF ((WS-A4 > '2019') AND (WS-A4 < '2030'))   ")
DataLineOrNoStatement ("              MOVE '|' TO WS-A2-A1. ")
DataLineOrNoStatement ("           IF ((WS-A4 > '2029') AND (WS-A4 < '2040'))   ")
DataLineOrNoStatement ("              MOVE '~' TO WS-A2-A1. ")
DataLineOrNoStatement ("       TRANSFO-DATE-4-2-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-2-4.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           IF WS-A2 = '00'  ")
DataLineOrNoStatement ("              MOVE '0000' TO WS-A4  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2 = '  '  ")
DataLineOrNoStatement ("              MOVE '    ' TO WS-A4  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = ';'")
DataLineOrNoStatement ("              MOVE '20' TO WS-A4-SS ")
DataLineOrNoStatement ("              MOVE '0'  TO WS-A4-A1 ")
DataLineOrNoStatement ("              MOVE WS-A2-A2  TO WS-A4-A2")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '_'")
DataLineOrNoStatement ("              MOVE '20' TO WS-A4-SS ")
DataLineOrNoStatement ("              MOVE '1'  TO WS-A4-A1 ")
DataLineOrNoStatement ("              MOVE WS-A2-A2  TO WS-A4-A2")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '|'")
DataLineOrNoStatement ("              MOVE '20' TO WS-A4-SS ")
DataLineOrNoStatement ("              MOVE '2'  TO WS-A4-A1 ")
DataLineOrNoStatement ("              MOVE WS-A2-A2  TO WS-A4-A2")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '~'")
DataLineOrNoStatement ("              MOVE '20' TO WS-A4-SS ")
DataLineOrNoStatement ("              MOVE '3'  TO WS-A4-A1 ")
DataLineOrNoStatement ("              MOVE WS-A2-A2  TO WS-A4-A2")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-2-4-EXIT.  ")
DataLineOrNoStatement ("           MOVE '19'     TO WS-A4-SS.   ")
DataLineOrNoStatement ("           MOVE WS-A2    TO WS-A4-AA.   ")
DataLineOrNoStatement ("           GO TO TRANSFO-DATE-2-4-EXIT. ")
DataLineOrNoStatement ("       TRANSFO-DATE-2-4-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-22A.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           IF WS-A2-A1 = '0'")
DataLineOrNoStatement ("              MOVE ';'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-22A-200X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '1'")
DataLineOrNoStatement ("              MOVE '_'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-22A-201X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '2'")
DataLineOrNoStatement ("              MOVE '|'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-22A-202X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '3'")
DataLineOrNoStatement ("              MOVE '~'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-22A-203X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22A-EXIT.  ")
DataLineOrNoStatement ("       TRANSFO-DATE-22A-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-66A.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           IF WS-A6 NOT NUMERIC ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF ((WS-A6-MM > '15') or (WS-A6-MM = '00'))  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF ((WS-A6-JJ > '35') or (WS-A6-JJ = '00'))  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '0'")
DataLineOrNoStatement ("              MOVE ';'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66A-200X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '1'")
DataLineOrNoStatement ("              MOVE '_'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66A-201X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '2'")
DataLineOrNoStatement ("              MOVE '|'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66A-202X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '3'")
DataLineOrNoStatement ("              MOVE '~'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66A-203X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66A-EXIT.  ")
DataLineOrNoStatement ("       TRANSFO-DATE-66A-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-66B.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           IF WS-A6-Y1 = ';'")
DataLineOrNoStatement ("              MOVE '0'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66B-200X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '_'")
DataLineOrNoStatement ("              MOVE '1'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66B-201X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '|'")
DataLineOrNoStatement ("              MOVE '2'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66B-202X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '~'")
DataLineOrNoStatement ("              MOVE '3'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE 'Y' TO WS-RECORD-TRANSFORME-66B-203X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-66B-EXIT.  ")
DataLineOrNoStatement ("       TRANSFO-DATE-66B-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-68. ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           MOVE WS-A6 TO WS-A8-YYMMJJ.  ")
DataLineOrNoStatement ("           MOVE '19'  to WS-A8-YY.  ")
DataLineOrNoStatement ("           IF WS-A6 = '      '  ")
DataLineOrNoStatement ("              MOVE '        ' to WS-A8  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A6 = '000000'  ")
DataLineOrNoStatement ("              MOVE '00000000' to WS-A8  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = ';'")
DataLineOrNoStatement ("              MOVE '200'    TO WS-A8-YYY")
DataLineOrNoStatement ("              MOVE WS-A6-Y2 TO WS-A8-Y4 ")
DataLineOrNoStatement ("              MOVE WS-A6-MM TO WS-A8-MM ")
DataLineOrNoStatement ("              MOVE WS-A6-JJ TO WS-A8-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '_'")
DataLineOrNoStatement ("              MOVE '201'    TO WS-A8-YYY")
DataLineOrNoStatement ("              MOVE WS-A6-Y2 TO WS-A8-Y4 ")
DataLineOrNoStatement ("              MOVE WS-A6-MM TO WS-A8-MM ")
DataLineOrNoStatement ("              MOVE WS-A6-JJ TO WS-A8-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '|'")
DataLineOrNoStatement ("              MOVE '202'    TO WS-A8-YYY")
DataLineOrNoStatement ("              MOVE WS-A6-Y2 TO WS-A8-Y4 ")
DataLineOrNoStatement ("              MOVE WS-A6-MM TO WS-A8-MM ")
DataLineOrNoStatement ("              MOVE WS-A6-JJ TO WS-A8-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A6-Y1 = '~'")
DataLineOrNoStatement ("              MOVE '203'    TO WS-A8-YYY")
DataLineOrNoStatement ("              MOVE WS-A6-Y2 TO WS-A8-Y4 ")
DataLineOrNoStatement ("              MOVE WS-A6-MM TO WS-A8-MM ")
DataLineOrNoStatement ("              MOVE WS-A6-JJ TO WS-A8-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-68-EXIT.   ")
DataLineOrNoStatement ("       TRANSFO-DATE-68-EXIT.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-86. ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           MOVE WS-A8-YYMMJJ TO WS-A6.  ")
DataLineOrNoStatement ("           IF WS-A8 NOT NUMERIC ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF ((WS-A8-MM > '15') or (WS-A8-MM = '00'))  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF ((WS-A8-JJ > '35') or (WS-A8-JJ = '00'))  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A8-YYY = '200' ")
DataLineOrNoStatement ("              MOVE ';'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE WS-A8-Y4 TO WS-A6-Y2 ")
DataLineOrNoStatement ("              MOVE WS-A8-MM TO WS-A6-MM ")
DataLineOrNoStatement ("              MOVE WS-A8-JJ TO WS-A6-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A8-YYY = '201' ")
DataLineOrNoStatement ("              MOVE '_'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE WS-A8-Y4 TO WS-A6-Y2 ")
DataLineOrNoStatement ("              MOVE WS-A8-MM TO WS-A6-MM ")
DataLineOrNoStatement ("              MOVE WS-A8-JJ TO WS-A6-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A8-YYY = '202' ")
DataLineOrNoStatement ("              MOVE '|'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE WS-A8-Y4 TO WS-A6-Y2 ")
DataLineOrNoStatement ("              MOVE WS-A8-MM TO WS-A6-MM ")
DataLineOrNoStatement ("              MOVE WS-A8-JJ TO WS-A6-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A8-YYY = '203' ")
DataLineOrNoStatement ("              MOVE '~'      TO WS-A6-Y1 ")
DataLineOrNoStatement ("              MOVE WS-A8-Y4 TO WS-A6-Y2 ")
DataLineOrNoStatement ("              MOVE WS-A8-MM TO WS-A6-MM ")
DataLineOrNoStatement ("              MOVE WS-A8-JJ TO WS-A6-JJ ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("           IF WS-A8-SS = '19'   ")
DataLineOrNoStatement ("              MOVE WS-A8-YYMMJJ   TO WS-A6  ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-86-EXIT.   ")
DataLineOrNoStatement ("       TRANSFO-DATE-86-EXIT.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       TRANSFO-DATE-22B.")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           IF WS-A2-A1 = ';'")
DataLineOrNoStatement ("              MOVE '0'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              move 'Y' TO WS-RECORD-TRANSFORME-22B-200X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '_'")
DataLineOrNoStatement ("              MOVE '1'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              move 'Y' TO WS-RECORD-TRANSFORME-22B-201X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '|'")
DataLineOrNoStatement ("              MOVE '2'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              move 'Y' TO WS-RECORD-TRANSFORME-22B-202X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22B-EXIT.  ")
DataLineOrNoStatement ("           IF WS-A2-A1 = '~'")
DataLineOrNoStatement ("              MOVE '3'      TO WS-A2-A1 ")
DataLineOrNoStatement ("              move 'Y' TO WS-RECORD-TRANSFORME-22B-203X ")
DataLineOrNoStatement ("              GO TO TRANSFO-DATE-22B-EXIT.  ")
DataLineOrNoStatement ("       TRANSFO-DATE-22B-EXIT.   ")
DataLineOrNoStatement ("      ******************")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("       WRITE-REC-OUTPUT.")
DataLineOrNoStatement ("      *******************   ")
DataLineOrNoStatement ("           ADD 1 TO NB-REC-ECRIT.   ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22A-200X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22A-200X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22A-201X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22A-201X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22A-202X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22A-202X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22A-203X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22A-203X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22B-200X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22B-200X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22B-201X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22B-201X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22B-202X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22B-202X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-22B-203X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-22B-203X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66A-200X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66A-200X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66A-201X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66A-201X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66A-202X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66A-202X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66A-203X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66A-203X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66B-200X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66B-200X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66B-201X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66B-201X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66B-202X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66B-202X.  ")
DataLineOrNoStatement ("           IF WS-RECORD-TRANSFORME-66B-203X = 'Y'   ")
DataLineOrNoStatement ("              ADD 1 TO NB-REC-TRANSFORME-66B-203X.  ")
DataLineOrNoStatement ("           WRITE FSOUTPUT FROM ENR-OUTPUT.  ")
DataLineOrNoStatement ("       WRITE-REC-OUTPUT-EXIT.   ")
DataLineOrNoStatement ("      ************************  ")
DataLineOrNoStatement ("           EXIT.")
# @MAP N  ASSURFED*UTILITASCII.MAP,TPF$.CONDIS2   
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
Fin
If ((CompareTypeSafe $FLAGABORT "EqualTo" 1)) {
  Exit
}
