# Converted from SSG source: FUSBA2_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filladd {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLADD") {
    Return
  }

  $FILLCTR = ($Parameters[0] + 1)
}
Function Define_fillsub {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLSUB") {
    Return
  }

  $FILLCTR = (0 - $Parameters[0])
}
Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLERCTR = ($Parameters[0] - 1)
  If ($FILLERCTR) {
    DataLineOrNoStatement ("           06  FILLER  PIC X(" + ($FILLERCTR) + "). ")
  }
}
Function Define_limpara {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_LIMPARA") {
    Return
  }

  $PARALIM = ($Parameters[0] - 1)
}
Function Define_setstart {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SETSTART") {
    Return
  }

  $START = ($Parameters[0] + 1)
}
Function Define_setcval {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SETCVAL") {
    Return
  }

  $C = ($Parameters[0] + 1)
}
Function Define_add {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_ADD") {
    Return
  }

  $Parameters[0] = ($Parameters[1] + $Parameters[2])
}
If ((CompareTypeSafe (GetSgsValue ("TRACE")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("TRACE,1,1")) "EqualTo" 1)) {
    AddTo-SgsList ("TRACE2" + (GetSgsValue ("TRACE,1,1,1")))
    RemoveFrom-SgsList "TRACE" 1 1
    AddTo-SgsList ("TRACE  0," + (GetSgsValue ("TRACE2,1,1,1")))
  }
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID.  FUSION-" + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".  ")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY PIERRE.")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1100-60. ")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1100-60. ")
DataLineOrNoStatement ("       SPECIAL-NAMES.     PRINTER   IS   LISTE. ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
For ([Int32]$INPUTCT = 1; $INPUTCT -le (GetSgsValue ("INPUT,1")); $INPUTCT++) { 
  DataLineOrNoStatement ("           SELECT  TAPEIN" + ($INPUTCT) + "  ASSIGN  TO ")
  If ((CompareTypeSafe (GetSgsValue ("INPUT,1,$INPUTCT")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                              UNISERVO  " + ((GetSgsValue ("INPUT,1,$INPUTCT,1"))) + ".")
  } else {
    If ((CompareTypeSafe (GetSgsValue ("INPUT,1,$INPUTCT,1")) "EqualTo" "CARDREADER")) {
      DataLineOrNoStatement ("           CARD-READER. ")
    } else {
      DataLineOrNoStatement ("                    DISC  " + ((GetSgsValue ("INPUT,1,$INPUTCT,1"))) + ".  ")
    }
  }
}
For ([Int32]$OUTPUTCT = 1; $OUTPUTCT -le (GetSgsValue ("OUTPUT,1")); $OUTPUTCT++) { 
  DataLineOrNoStatement ("           SELECT  TAPEOUT" + ($OUTPUTCT) + "  ASSIGN  TO   ")
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,$OUTPUTCT")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                              UNISERVO  " + ((GetSgsValue ("OUTPUT,1,$OUTPUTCT,1"))) + ".  ")
  } else {
    DataLineOrNoStatement ("                    DISC  " + ((GetSgsValue ("OUTPUT,1,$OUTPUTCT,1"))) + ".")
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
$FILLCTR = 0
For ([Int32]$IMP = 1; $IMP -le (GetSgsValue ("INPUT,1")); $IMP++) { 
  DataLineOrNoStatement ("       FD  TAPEIN" + ($IMP) + " ")
  If ((CompareTypeSafe (GetSgsValue ("INPUT,1,$IMP,1")) "EqualTo" "CARDREADER")) {
    DataLineOrNoStatement ("                    LABEL RECORD OMITTED")
  } else {
    DataLineOrNoStatement ("                    LABEL RECORD IS STANDARD")
    DataLineOrNoStatement ("                   BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,$IMP,3"))) + " RECORDS   ")
  }
  DataLineOrNoStatement ("                   RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,$IMP,2"))) + " CHARACTERS   ")
  If (((CompareTypeSafe $IMP "EqualTo" 1) -and (CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0))) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("                   REC-IN-1-" + ($I))
    }
    DataLineOrNoStatement ("           REC-IN-" + ($IMP) + ".   ")
  } else {
    DataLineOrNoStatement ("                    DATA RECORD  IS REC-IN-" + ($IMP) + ".  ")
  }
  DataLineOrNoStatement ("       01  REC-IN-" + ($IMP) + ".   ")
  If (((CompareTypeSafe $IMP "EqualTo" 1) -and (CompareTypeSafe (GetSgsValue ("UPDATE")) "GreaterThan" 0))) {
    $FILLCTR = 0
    $INDICLNGTH = 0
    For ([Int32]$CH = 1; $CH -le (GetSgsValue ("INPUT,1,$IMP,2")); $CH++) { 
      For ([Int32]$COL = 1; $COL -le (GetSgsValue ("UPDATE,1")); $COL++) { 
        If ((CompareTypeSafe ("VALUE OF" + (GetSgsValue ("UPDATE,1,$COL,1"))) "EqualTo" $CH)) {
          If ($FILLCTR) {
            DataLineOrNoStatement ("           03  FILLER  PIC  X(" + ($FILLCTR) + ").  ")
          }
          DataLineOrNoStatement ("           03 COMPARE-FILE-" + ($IMP) + "-FIELD-" + ($COL) + "  ")
          DataLineOrNoStatement ("                   PIC  X(" + ((GetSgsValue ("UPDATE,1,$COL,2"))) + ").")
          DEFINE_ADD ($INDICLNGTH) ($INDICLNGTH) ((GetSgsValue ("UPDATE,1,$COL,2")))
          DEFINE_FILLSUB ((GetSgsValue ("UPDATE,1,$COL,2")))
        }
      }
      DEFINE_FILLADD ($FILLCTR)
    }
    If ($FILLCTR) {
      DataLineOrNoStatement ("           03 FILLER   PIC X(" + ($FILLCTR) + ").   ")
    }
  } else {
    $FILLCTR = 0
    $INDICLNGTH = 0
    For ([Int32]$CH = 1; $CH -le (GetSgsValue ("INPUT,1,$IMP,2")); $CH++) { 
      For ([Int32]$COL = 1; $COL -le (GetSgsValue ("KEYS,1")); $COL++) { 
        If ((CompareTypeSafe ("VALUE OF" + (GetSgsValue ("KEYS,1,$COL,1"))) "EqualTo" $CH)) {
          If ($FILLCTR) {
            DataLineOrNoStatement ("           03  FILLER                   PIC  X(" + ($FILLCTR) + "). ")
          }
          DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($IMP) + "-FIELD-" + ($COL) + "   PIC  X(" + ((GetSgsValue ("KEYS,1,$COL,2"))) + ").   ")
          DEFINE_ADD ($INDICLNGTH) ($INDICLNGTH) ((GetSgsValue ("KEYS,1,$COL,2")))
          DEFINE_FILLSUB ((GetSgsValue ("KEYS,1,$COL,2")))
        }
      }
      DEFINE_FILLADD ($FILLCTR)
    }
    If ($FILLCTR) {
      DataLineOrNoStatement ("           03  FILLER                   PIC  X(" + ($FILLCTR) + "). ")
    }
  }
  If (((CompareTypeSafe $IMP "EqualTo" 1) -and (CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0))) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC-IN-1-" + ($I) + ".   ")
      DEFINE_FILER ((GetSgsValue ("FIELDIN,1,$I,1")))
      DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").   ")
    }
  }
}
For ([Int32]$OUTPCT = 1; $OUTPCT -le (GetSgsValue ("OUTPUT,1")); $OUTPCT++) { 
  DataLineOrNoStatement ("       FD  TAPEOUT" + ($OUTPCT) + " ")
  DataLineOrNoStatement ("                    LABEL RECORD IS STANDARD")
  DataLineOrNoStatement ("                    BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,$OUTPCT,3"))) + " RECORDS  ")
  DataLineOrNoStatement ("                    RECORD CONTAINS " + ((GetSgsValue ("OUTPUT,1,$OUTPCT,2"))) + " CHARACTERS  ")
  If (((CompareTypeSafe $OUTPCT "EqualTo" 1) -and (CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0))) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("               REC-OUT-1" + ($I))
    }
    DataLineOrNoStatement ("           REC-OUT-" + ($OUTPCT) + ".   ")
  } else {
    DataLineOrNoStatement ("                    DATA RECORD IS REC-OUT-" + ($OUTPCT) + ".   ")
  }
  DataLineOrNoStatement ("       01  REC-OUT-" + ($OUTPCT) + "           PIC X(" + ((GetSgsValue ("OUTPUT,1,$OUTPCT,2"))) + ").  ")
  If (((CompareTypeSafe $OUTPCT "EqualTo" 1) -and (CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0))) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC-OUT-1" + ($I) + ".   ")
      DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
      DataLineOrNoStatement ("           06  ZONO" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + ").  ")
    }
  }
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
For ([Int32]$INC = 1; $INC -le (GetSgsValue ("INPUT,1")); $INC++) { 
  DataLineOrNoStatement ("       77  TAPE-" + ($INC) + "-CT                PIC 9(10)  COMP VALUE 0.   ")
}
DataLineOrNoStatement ("       77  INPUT-CT           PIC 9(10)  COMP  VALUE 0. ")
For ([Int32]$OUTC = 1; $OUTC -le (GetSgsValue ("OUTPUT,1")); $OUTC++) { 
  DataLineOrNoStatement ("       77  TAPE-" + ($OUTC) + "-OUT-CT            PIC 9(10)  COMP  VALUE 0. ")
  DataLineOrNoStatement ("       77  TAPE-" + ($OUTC) + "-MAJ-CT            PIC 9(10)  COMP  VALUE 0. ")
}
DataLineOrNoStatement ("       77  OUTPUT-CT                PIC 9(10)  COMP  VALUE 0.   ")
If ((CompareTypeSafe (GetSgsValue ("TRACE")) "GreaterThan" 0)) {
  For ([Int32]$MCT = 1; $MCT -le (GetSgsValue ("TRACE,1")); $MCT++) { 
    DataLineOrNoStatement ("       77  TRACE-LOW-" + ($MCT) + "   PIC 9(10)  COMP  VALUE " + ((GetSgsValue ("TRACE,1,$MCT,1"))) + ".   ")
    DataLineOrNoStatement ("       77  TRACE-HIGH-" + ($MCT) + "  PIC 9(10)  COMP  VALUE " + ((GetSgsValue ("TRACE,1,$MCT,2"))) + ".   ")
  }
}
For ([Int32]$FL = 1; $FL -le (GetSgsValue ("INPUT,1")); $FL++) { 
  DataLineOrNoStatement ("       01  COMPARE-" + ($FL) + ".   ")
  If (((CompareTypeSafe (GetSgsValue ("UPDATE")) "GreaterThan" 0) -and (CompareTypeSafe $FL "EqualTo" 1))) {
    For ([Int32]$CF = 1; $CF -le (GetSgsValue ("UPDATE,1")); $CF++) { 
      DataLineOrNoStatement ("           03 COMPARE-FILE-" + ($FL) + "-FIELD-" + ($CF))
      DataLineOrNoStatement ("                 PIC X(" + ((GetSgsValue ("UPDATE,1,$CF,2"))) + ").")
    }
  } else {
    For ([Int32]$CF = 1; $CF -le (GetSgsValue ("KEYS,1")); $CF++) { 
      DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($FL) + "-FIELD-" + ($CF) + "   PIC X(" + ((GetSgsValue ("KEYS,1,$CF,2"))) + ").   ")
    }
  }
}
For ([Int32]$FL = 1; $FL -le (GetSgsValue ("INPUT,1")); $FL++) { 
  DataLineOrNoStatement ("       01  PREC-COMPARE-" + ($FL) + ".  ")
  If (((CompareTypeSafe (GetSgsValue ("UPDATE")) "GreaterThan" 0) -and (CompareTypeSafe $FL "EqualTo" 1))) {
    For ([Int32]$CF = 1; $CF -le (GetSgsValue ("UPDATE,1")); $CF++) { 
      DataLineOrNoStatement ("           03 PREC-COMPARE-FILE-" + ($FL) + "-FIELD-" + ($CF) + "   ")
      DataLineOrNoStatement ("                 PIC X(" + ((GetSgsValue ("UPDATE,1,$CF,2"))) + ").")
    }
  } else {
    For ([Int32]$CF = 1; $CF -le (GetSgsValue ("KEYS,1")); $CF++) { 
      DataLineOrNoStatement ("           03 PREC-COMPARE-FILE-" + ($FL) + "-FIELD-" + ($CF) + " PIC X(" + ((GetSgsValue ("KEYS,1,$CF,2"))) + "). ")
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "GreaterThan" 0)) {
  If (((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YES") -or ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "OUI") -or (CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YA")))) {
    For ([Int32]$FSQ = 1; $FSQ -le (GetSgsValue ("INPUT,1")); $FSQ++) { 
      If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("       01  SNAP-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + ".")
      } else {
        DataLineOrNoStatement ("       01  SNAP-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + ".")
      }
      DataLineOrNoStatement ("           03  M-CONTROL-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + ".   ")
      DataLineOrNoStatement ("               05  DISP-FLAG-" + ($FSQ) + "     PIC 9(2)     VALUE 1")
      If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("                                        USAGE COMP. ")
      } else {
        DataLineOrNoStatement ("                                        USAGE COMP-2.   ")
      }
      DataLineOrNoStatement ("               05  MESS-LNGTH-" + ($FSQ) + "    PIC 99    VALUE 2   ")
      If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("                                        USAGE COMP-4.   ")
      } else {
        DataLineOrNoStatement ("                                        USAGE COMP. ")
      }
      DataLineOrNoStatement ("           03  DUMP-LNGTH-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + "         PIC 9(5)  ")
      If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
        DataLineOrNoStatement ("                    VALUE  " + ($INDICLNGTH) + "     USAGE COMP-4.  ")
      } else {
        DataLineOrNoStatement ("                    VALUE  " + ($INDICLNGTH) + "     USAGE COMP.")
      }
      DataLineOrNoStatement ("           03  SNAP-IDENT-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + "         PIC X(6)  ")
      DataLineOrNoStatement ("                   VALUE '" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + "'. ")
      DataLineOrNoStatement ("           03  MESS-" + ((GetSgsValue ("INPUT,1,$FSQ,1"))) + "               PIC X(12) ")
      DataLineOrNoStatement ("                   VALUE ' OLD SEQ. '.  ")
      DataLineOrNoStatement ("       01  FILE-" + ($FSQ) + "-SEQ-ERROR-CT     PIC 9(5)  COMP  VALUE 0.")
      DataLineOrNoStatement ("       01  SEQ-COMPARE-" + ($FSQ) + ".  ")
      If (((CompareTypeSafe (GetSgsValue ("UPDATE")) "GreaterThan" 0) -and (CompareTypeSafe $FSQ "EqualTo" 1))) {
        For ([Int32]$SQ = 1; $SQ -le (GetSgsValue ("UPDATE,1")); $SQ++) { 
          DataLineOrNoStatement ("              03  COMPARE-FILE-" + ($FSQ) + "-FIELD-" + ($SQ) + "   ")
          DataLineOrNoStatement ("                   PIC  X(" + ((GetSgsValue ("UPDATE,1,$SQ,2"))) + "). ")
        }
      } else {
        For ([Int32]$SQ = 1; $SQ -le (GetSgsValue ("KEYS,1")); $SQ++) { 
          DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($FSQ) + "-FIELD-" + ($SQ) + "    PIC X(" + ((GetSgsValue ("KEYS,1,$SQ,2"))) + "). ")
        }
        # 
      }
    }
    DataLineOrNoStatement ("       01  ABORT-IND                    PIC 9(5)  COMP. ")
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
      DataLineOrNoStatement ("       01  SEQ-ERR-LINE                          USAGE DISPLAY-1.   ")
    } else {
      DataLineOrNoStatement ("       01  SEQ-ERR-LINE.")
    }
    DataLineOrNoStatement ("           03  SEQ-FNAME                PIC X(12).  ")
    DataLineOrNoStatement ("           03  FILLER                   PIC X(36)   ")
    DataLineOrNoStatement ("               VALUE  ' HAS SEQUENCE ERROR BETWEEN RECORD '.")
    DataLineOrNoStatement ("           03  SEQ-REC-1                PIC Z(11)9. ")
    DataLineOrNoStatement ("           03  FILLER                   PIC X(12)   ")
    DataLineOrNoStatement ("               VALUE  ' AND RECORD '.   ")
    DataLineOrNoStatement ("           03  SEQ-REC-2                PIC Z(11)9. ")
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
      DataLineOrNoStatement ("       01  SEQ-ERR-L2                            USAGE  DISPLAY-1.  ")
    } else {
      DataLineOrNoStatement ("       01  SEQ-ERR-L2.  ")
    }
    DataLineOrNoStatement ("           03  FILLER                   PIC X(9)")
    DataLineOrNoStatement ("               VALUE  'INDICATIF'.  ")
    DataLineOrNoStatement ("           03  SEQ-REC-L2               PIC Z(11)9. ")
    DataLineOrNoStatement ("           03  FILLER                   PIC X(6)")
    DataLineOrNoStatement ("               VALUE  '  :-  '. ")
    DataLineOrNoStatement ("           03  COMPARE-L2               PIC X(105). ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  DISPLAY-LINE   USAGE DISPLAY-1   VALUE SPACES.   ")
} else {
  DataLineOrNoStatement ("       01  DISPLAY-LINE   VALUE SPACES. ")
}
DataLineOrNoStatement ("               03  DISP-MESSAGE        PIC X(24).   ")
DataLineOrNoStatement ("               03  DISP-FNAME          PIC X(16).   ")
DataLineOrNoStatement ("               03  DISP-CT             PIC Z(11)9.  ")
DataLineOrNoStatement ("               03  FILLER              PIC X(28).   ")
If ((CompareTypeSafe (GetSgsValue ("UPDATE")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  SWITCHES.")
  DataLineOrNoStatement ("           03 SWITCHA PIC X.")
  DataLineOrNoStatement ("           03  SWITCHB  PIC  X  VALUE 0.")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       MERGE-" + ((GetSgsValue ("INPUT,1"))) + "-FILES  SECTION.  ")
DataLineOrNoStatement ("       OPEN-AND-FIRST-READ. ")
For ([Int32]$INP = 1; $INP -le (GetSgsValue ("INPUT,1")); $INP++) { 
  DataLineOrNoStatement ("           OPEN  INPUT  TAPEIN" + ($INP) + ".   ")
}
For ([Int32]$OUTP = 1; $OUTP -le (GetSgsValue ("OUTPUT,1")); $OUTP++) { 
  DataLineOrNoStatement ("           OPEN  OUTPUT  TAPEOUT" + ($OUTP) + ".")
}
For ([Int32]$RD = 1; $RD -le (GetSgsValue ("INPUT,1")); $RD++) { 
  DataLineOrNoStatement ("           PERFORM READ-FILE-" + ($RD) + ". ")
}
DataLineOrNoStatement ("       COMPARE-FILES.   ")
DataLineOrNoStatement ("           IF  COMPARE-1 <  COMPARE-2   ")
DataLineOrNoStatement ("               PERFORM DISPLAY-FILE-1   ")
DataLineOrNoStatement ("               PERFORM READ-FILE-1  ")
DataLineOrNoStatement ("               GO TO COMPARE-FILES. ")
DataLineOrNoStatement ("           IF  COMPARE-1 >  COMPARE-2   ")
DataLineOrNoStatement ("               MOVE REC-IN-2 TO REC-OUT-1   ")
DataLineOrNoStatement ("               PERFORM WRITE-FROM-FILE  ")
DataLineOrNoStatement ("               PERFORM READ-FILE-2  ")
DataLineOrNoStatement ("               GO TO COMPARE-FILES. ")
DataLineOrNoStatement ("           IF  COMPARE-1 =  COMPARE-2  AND  ")
DataLineOrNoStatement ("               COMPARE-1 =  HIGH-VALUES ")
DataLineOrNoStatement ("               GO TO PRINT-FILE-TOT.")
DataLineOrNoStatement ("           MOVE REC-IN-2 TO REC-OUT-1.  ")
DataLineOrNoStatement ("           MOVE ZONE1 TO ZONO1. ")
DataLineOrNoStatement ("           PERFORM WRITE-FROM-FILE. ")
DataLineOrNoStatement ("           ADD 1 TO TAPE-1-MAJ-CT.  ")
DataLineOrNoStatement ("           PERFORM READ-FILE-2. ")
DataLineOrNoStatement ("           IF  COMPARE-2 >  PREC-COMPARE-2  ")
DataLineOrNoStatement ("               PERFORM READ-FILE-1. ")
DataLineOrNoStatement ("           GO TO COMPARE-FILES. ")
For ([Int32]$RD = 1; $RD -le (GetSgsValue ("INPUT,1")); $RD++) { 
  DataLineOrNoStatement ("       READ-FILE-" + ($RD) + ". ")
  DataLineOrNoStatement ("           MOVE  COMPARE-" + ($RD) + "  TO  PREC-COMPARE-" + ($RD) + ". ")
  DataLineOrNoStatement ("           READ  TAPEIN" + ($RD))
  DataLineOrNoStatement ("                    AT END  MOVE  HIGH-VALUE  TO  REC-IN-" + ($RD) + ". ")
  DataLineOrNoStatement ("           MOVE  CORRESPONDING  REC-IN-" + ($RD) + "   TO  COMPARE-" + ($RD) + ".   ")
  DataLineOrNoStatement ("           ADD 1 TO TAPE-" + ($RD) + "-CT.  ")
}
DataLineOrNoStatement ("       WRITE-FROM-FILE. ")
DataLineOrNoStatement ("           WRITE REC-OUT-1. ")
DataLineOrNoStatement ("           ADD 1 TO TAPE-1-OUT-CT.  ")
DataLineOrNoStatement ("       DISPLAY-FILE-1.  ")
If (-not (GetSgsValue ("NOLIST"))) {
  DataLineOrNoStatement ("           MOVE  'MATR./POLICENNON TROUVE '  TO  DISP-MESSAGE.  ")
  DataLineOrNoStatement ("           MOVE  COMPARE-1 TO  DISP-FNAME.  ")
  DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
  DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
}
DataLineOrNoStatement ("       PRINT-FILE-TOT.  ")
For ([Int32]$INP = 1; $INP -le (GetSgsValue ("INPUT,1")); $INP++) { 
  DataLineOrNoStatement ("           SUBTRACT  1  FROM  TAPE-" + ($INP) + "-CT.   ")
  DataLineOrNoStatement ("           MOVE  '     RECORDS  READ FROM '  TO  DISP-MESSAGE.  ")
  DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("INPUT,1,$INP,1"))) + "'  TO  DISP-FNAME. ")
  DataLineOrNoStatement ("           MOVE  TAPE-" + ($INP) + "-CT  TO  DISP-CT.   ")
  DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
  DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
  DataLineOrNoStatement ("           ADD  TAPE-" + ($INP) + "-CT  TO  INPUT-CT.   ")
  DataLineOrNoStatement ("           CLOSE    TAPEIN" + ($INP) + ".   ")
}
DataLineOrNoStatement ("           MOVE  '   TOTAL RECORDS READ   '  TO  DISP-MESSAGE.  ")
DataLineOrNoStatement ("           MOVE  INPUT-CT  TO  DISP-CT. ")
DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
For ([Int32]$OUTP = 1; $OUTP -le (GetSgsValue ("OUTPUT,1")); $OUTP++) { 
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,$OUTP")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("           MOVE ALL '" + ((GetSgsValue ("OUTPUT,1,$OUTP,4"))) + "'  TO  REC-OUT-" + ($OUTP) + ".   ")
    DataLineOrNoStatement ("           WRITE  REC-OUT-" + ($OUTP) + ".  ")
    DataLineOrNoStatement ("           ADD  1  TO  TAPE-" + ($OUTP) + "-OUT-CT. ")
  }
  DataLineOrNoStatement ("           MOVE  '    RECORDS WRITTEN TO  '  TO  DISP-MESSAGE.  ")
  DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("OUTPUT,1,$OUTP,1"))) + "'  TO  DISP-FNAME.   ")
  DataLineOrNoStatement ("           MOVE  TAPE-" + ($OUTP) + "-OUT-CT  TO  DISP-CT.  ")
  DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
  DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
  DataLineOrNoStatement ("           CLOSE    TAPEOUT" + ($OUTP) + ". ")
  DataLineOrNoStatement ("           ADD  TAPE-" + ($OUTP) + "-OUT-CT  TO  OUTPUT-CT. ")
}
DataLineOrNoStatement ("           MOVE  '   TOTAL RECORDS WRITTEN'  TO  DISP-MESSAGE.  ")
DataLineOrNoStatement ("           MOVE  OUTPUT-CT  TO  DISP-CT.")
DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
DataLineOrNoStatement ("           MOVE  '    RECORDS OUTPUT MAJ. '  TO  DISP-MESSAGE.  ")
DataLineOrNoStatement ("           MOVE  TAPE-1-MAJ-CT  TO  DISP-CT.")
DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       ABORT-ROUTINES SECTION.  ")
DataLineOrNoStatement ("       SEQUENCE-ERRORS. ")
If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           GO  TO   ")
  For ([Int32]$FC = 1; $FC -le (GetSgsValue ("INPUT,1")); $FC++) { 
    DataLineOrNoStatement ("                   FILE-" + ($FC) + "-SEQ-ERROR ")
  }
  DataLineOrNoStatement ("              DEPENDING  ON  ABORT-IND. ")
  For ([Int32]$PARA = 1; $PARA -le (GetSgsValue ("INPUT,1")); $PARA++) { 
    DataLineOrNoStatement ("       FILE-" + ($PARA) + "-SEQ-ERROR.  ")
    DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("INPUT,1,$PARA,1"))) + "'  TO  SEQ-FNAME. ")
    DataLineOrNoStatement ("           SUBTRACT  1  FROM  TAPE-" + ($PARA) + "-CT  GIVING  SEQ-REC-1,   ")
    DataLineOrNoStatement ("                              SEQ-REC-L2.   ")
    DataLineOrNoStatement ("           MOVE  TAPE-" + ($PARA) + "-CT  TO  SEQ-REC-2.")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-LINE  TO  DISPLAY-LINE.")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  COMPARE-" + ($PARA) + "   TO   COMPARE-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-L2        TO   DISPLAY-LINE.   ")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  TAPE-" + ($PARA) + "-CT   TO   SEQ-REC-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-COMPARE-" + ($PARA) + "   TO   COMPARE-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-L2         TO   DISPLAY-LINE.  ")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
    DataLineOrNoStatement ("           MOVE  ' OLD SEQ. '  TO  MESS-" + ((GetSgsValue ("INPUT,1,$PARA,1"))) + ".   ")
    DataLineOrNoStatement ("           CALL 'SNAP' USING   SNAP-" + ((GetSgsValue ("INPUT,1,$PARA,1"))))
    DataLineOrNoStatement ("                   COMPARE-" + ($PARA) + ". ")
    DataLineOrNoStatement ("           MOVE  ' NEW SEQ. '  TO  MESS-" + ((GetSgsValue ("INPUT,1,$PARA,1"))) + ".   ")
    DataLineOrNoStatement ("           CALL 'SNAP' USING   SNAP-" + ((GetSgsValue ("INPUT,1,$PARA,1"))))
    DataLineOrNoStatement ("                   SEQ-COMPARE-" + ($PARA) + ". ")
    If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1")) "GreaterThan" 1)) {
      DataLineOrNoStatement ("           ADD  1  TO  FILE-" + ($PARA) + "-SEQ-ERROR-CT.   ")
      DataLineOrNoStatement ("           IF  FILE-" + ($PARA) + "-SEQ-ERROR-CT  >  " + ((GetSgsValue ("SEQERROR,1,1,2"))) + "   ")
      DataLineOrNoStatement ("               CALL  'ABORT'.   ")
      DataLineOrNoStatement ("           GO  TO  MOVE-REC-" + ($PARA) + ".")
    } else {
      DataLineOrNoStatement ("           CALL  'ABORT'.   ")
    }
  }
}
DataLineOrNoStatement ("           STOP RUN.")
# @MAP N    ASSURFED*UTILITASCII.MAP,TPF$.FUSBA   
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
SetC "" "0/T1"
Hdg "N"
Fin
