# Converted from SSG source: LOADIS_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("           02  FILLER  PIC  X(" + ($FILLCTR) + ").  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB IE  .LOADIS/ASCII,.LOADIS/ASCII   
  Call-ExternalProgram "ACOB" "I, E" ("\LOADIS\ASCII")
  Fin
} else {
  # @ACOB IET .LOADIS/ASCII,.LOADIS/ASCII   
  Call-ExternalProgram "ACOB" "I, E, T" ("\LOADIS\ASCII")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. LOADIS-ASCII.")
DataLineOrNoStatement ("       AUTHOR BOURDEAUD HUY 17/12/79.   ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
If ((CompareTypeSafe (GetSgsValue ("VIDE")) "GreaterThan" 0)) {
} else {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INPUT,1")); $I++) { 
    DataLineOrNoStatement ("           SELECT  BDE" + ($I) + "  ASSIGN TO   ")
    If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1")) "GreaterThan" 3)) {
      DataLineOrNoStatement ("               UNISERVO " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
    } else {
      DataLineOrNoStatement ("               DISC " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
    }
  }
}
DataLineOrNoStatement ("           SELECT DISQ ASSIGN TO DISC  " + ((GetSgsValue ("OUTPUT,1,1,1"))) + "   ")
DataLineOrNoStatement ("           ORGANIZATION IS INDEXED  ")
DataLineOrNoStatement ("           RESERVE 5 AREAS  ")
DataLineOrNoStatement ("           ACCESS  MODE IS SEQUENTIAL RECORD KEY IS CLEF")
DataLineOrNoStatement ("           FILE STATUS IS IO-STAT.  ")
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
If ((CompareTypeSafe (GetSgsValue ("VIDE")) "GreaterThan" 0)) {
} else {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INPUT,1")); $I++) { 
    DataLineOrNoStatement ("       FD  BDE" + ($I) + "  ")
    DataLineOrNoStatement ("           LABEL RECORD STANDARD")
    DataLineOrNoStatement ("             BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "   RECORDS ")
    DataLineOrNoStatement ("           RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,1,2"))) + " CHARACTERS ")
    DataLineOrNoStatement ("           DATA RECORD IS  Z" + ($I) + ".   ")
    DataLineOrNoStatement ("       01  Z" + ($I) + "   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
  }
}
DataLineOrNoStatement ("       FD  DISQ   LABEL RECORD STANDARD ")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + " RECORDS")
DataLineOrNoStatement ("           RECORD  CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " CHARACTERS   ")
DataLineOrNoStatement ("             DATA RECORD IS ZDISQ CLEF. ")
DataLineOrNoStatement ("       01  ZDISQ  PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").   ")
DataLineOrNoStatement ("       01  CLEFA.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").  ")
  DataLineOrNoStatement ("           02 CLEF PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
} else {
  DataLineOrNoStatement ("           02 CLEF PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  FF  PIC  9(10)  COMP  VALUE 1.   ")
DataLineOrNoStatement ("       77  CTRIN  PIC  9(10)  COMP  VALUE  0.   ")
DataLineOrNoStatement ("       01  WREC.")
DataLineOrNoStatement ("           02 FILLER  PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").   ")
DataLineOrNoStatement ("       01  WREC1     REDEFINES  WREC.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER   PIC  X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").   ")
  DataLineOrNoStatement ("           02 KEYA PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
} else {
  DataLineOrNoStatement ("           02 KEYA PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  IO-STAT. ")
  DataLineOrNoStatement ("           02 IO-FS1     PIC X VALUE '9'.   ")
  DataLineOrNoStatement ("           02 IO-FS2     PIC X VALUE '9'.   ")
} else {
  DataLineOrNoStatement ("       01  IO-STAT DISP-1.  ")
  DataLineOrNoStatement ("           02 IO-FS1     PIC X VALUE '9' DISP-1.")
  DataLineOrNoStatement ("           02 IO-FS2     PIC X VALUE '9' DISP-1.")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   ")
If ((CompareTypeSafe (GetSgsValue ("VIDE")) "GreaterThan" 0)) {
} else {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INPUT,1")); $I++) { 
    DataLineOrNoStatement ("           OPEN INPUT  BDE" + ($I) + ". ")
  }
}
DataLineOrNoStatement ("           OPEN  OUTPUT  DISQ.  ")
If ((CompareTypeSafe (GetSgsValue ("VIDE")) "GreaterThan" 0)) {
} else {
  DataLineOrNoStatement ("       LECT.")
  DataLineOrNoStatement ("           GO TO LECT1 FINB  DEPENDING  ON FF.  ")
  DataLineOrNoStatement ("       LECT1.   ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INPUT,1")); $I++) { 
    DataLineOrNoStatement ("           MOVE SPACES TO Z" + ($I) + ".")
  }
  DataLineOrNoStatement ("           READ  BDE1  INTO  WREC  AT END ADD 1 TO FF  GO TO LECT.  ")
  DataLineOrNoStatement ("           GO TO CONT.  ")
  DataLineOrNoStatement ("       CONT.")
  DataLineOrNoStatement ("           MOVE KEYA     TO  CLEF.  ")
  DataLineOrNoStatement ("           ADD  1  TO  CTRIN.   ")
  DataLineOrNoStatement ("           WRITE ZDISQ FROM WREC INVALID KEY GO TO  ERRDISQ.")
  DataLineOrNoStatement ("           MOVE SPACES TO WREC WREC1 ZDISQ. ")
  DataLineOrNoStatement ("           GO TO LECT.  ")
  DataLineOrNoStatement ("       FINB.")
  DataLineOrNoStatement ("           DISPLAY 'NB.RECORDS ECRITS'  CTRIN  UPON PRINTER.")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INPUT,1")); $I++) { 
    DataLineOrNoStatement ("           CLOSE  BDE" + ($I) + ".  ")
  }
}
DataLineOrNoStatement ("           CLOSE  DISQ. ")
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       ERRDISQ. ")
DataLineOrNoStatement ("           DISPLAY 'IS.ERROR         : '  CLEF  UPON  PRINTER.  ")
DataLineOrNoStatement ("           DISPLAY 'STATUS           : ' IO-FS1 IO-FS2 UPON  PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY 'RECORD EN ERREUR : ' CTRIN ' EME'  UPON PRINTER.")
DataLineOrNoStatement ("           ENTER ASM 'ABORT'.   ")
# @MAP S    ASSURFED*UTILITASCII.MAP,TPF$.LOADIS  
Call-ExternalProgram "MAP" "S" ("ASSURFED\UTILITASCII\MAP")
Hdg "N"
Fin
