# Converted from SSG source: RECAP
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("                     06 FILLER PIC  X(" + ($FILLCTR) + ").  ")
  }
}
Function Define_fila2 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILA2") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    If ((CompareTypeSafe (GetSgsValue ("Y2K")) "EqualTo" 0)) {
      DataLineOrNoStatement ("                     06 FILLER PIC  X(" + ($FILLCTR) + ").  ")
    } else {
      $FILLCTR = ($Parameters[0] - 3)
      If ($FILLCTR) {
        DataLineOrNoStatement ("                     06 FILLER      PIC  X(" + ($FILLCTR) + "). ")
      }
      DataLineOrNoStatement ("                     06 SIECLE-" + ($I) + " PIC XX. ")
    }
  }
}
$Rgv_CASE = 1
AddTo-SgsList "SCHEMA DEV DBREP"
AddTo-SgsList "SCHEMA TST AFLINC"
AddTo-SgsList "SCHEMA TEMPBEF EU1"
AddTo-SgsList "SCHEMA TEMPEUR EU2"
$SCHNAME = "AFLINC"
For ([Int32]$ASCH = 1; $ASCH -le (GetSgsValue ("SCHEMA")); $ASCH++) { 
  Log-Message ((GetSgsValue ("info$,1,3,1")) + " = " + (GetSgsValue ("schema,$asch,1,1"))) '([LogMessageType]::Information)'
  If ((CompareTypeSafe (GetSgsValue ("info$,1,3,1")) "EqualTo" (GetSgsValue ("schema,$ASCH,1,1")))) {
    $SCHNAME = (GetSgsValue ("schema,$asch,2,1"))
    Exit
  }
}
Log-Message ("schema = " + $schname) '([LogMessageType]::Information)'
If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
  # @ACOB IEPY    .RECAP,.RECAP 
  Call-ExternalProgram "ACOB" "I, E, P, Y" ("\RECAP")
  Fin
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 1)) {
  # @ACOB IEPY    .RECAP,.RECAP 
  Call-ExternalProgram "ACOB" "I, E, P, Y" ("\RECAP")
  Fin
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
  # @COB SEBRFMCI .RECAP,.RECAP 
  Call-ExternalProgram "COB" "S, E, B, R, F, M, C, I" ("\RECAP")
  Fin
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 0)) {
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
      Msg "N" ("CARTE COMPILATEUR MANQUANTE")
      Msg "N" ("RELIRE ATTENTIVEMENT MODE D EMPLOI RECAP")
      Fin
    }
  }
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. 'RECAP'. ")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY 13/10/82.  ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1108.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN  TO   ")
If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   DISC  " + ((GetSgsValue ("INPUT,1,1,1"))) + ". ")
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   DISC  " + ((GetSgsValue ("INPUT,1,1,1"))) + ". ")
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   MASS-STORAGE " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
}
DataLineOrNoStatement ("           SELECT TAPEOUT ASSIGN TO ")
If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   DISC  " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".")
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   DISC  " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".")
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
  DataLineOrNoStatement ("                   MASS-STORAGE " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ". ")
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  TAPEIN   ")
DataLineOrNoStatement ("           LABEL  RECORD  STANDARD  ")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "  RECORDS")
DataLineOrNoStatement ("           DATA RECORD IS   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
  DataLineOrNoStatement ("           REC1" + ($I) + " ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  DataLineOrNoStatement ("           RECTOT" + ($I) + "   ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
  DataLineOrNoStatement ("           INDICATIF" + ($I))
}
DataLineOrNoStatement ("           RECIN.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
    DataLineOrNoStatement ("       01     REC1" + ($I) + "  DISP-1. ")
  } else {
    DataLineOrNoStatement ("       01     REC1" + ($I) + ". ")
  }
  DEFINE_FILA2 ((GetSgsValue ("FIELDIN,1,$I,1")))
  DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").   ")
}
If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
  DataLineOrNoStatement ("       01  RECIN   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ")  DISP-1.   ")
} else {
  DataLineOrNoStatement ("       01  RECIN   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
    DataLineOrNoStatement ("       01  RECTOT" + ($I) + " DISP-1.   ")
  } else {
    DataLineOrNoStatement ("       01  RECTOT" + ($I) + ".  ")
  }
  DEFINE_FILER ((GetSgsValue ("TOTIN,1,$I,1")))
  DataLineOrNoStatement ("               06 TOTAL" + ($I) + " PIC S9(" + ((GetSgsValue ("TOTIN,1,$I,2"))) + ").  ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
    DataLineOrNoStatement ("       01  INDICATIF" + ($I) + "   DISP-1.  ")
  } else {
    DataLineOrNoStatement ("       01  INDICATIF" + ($I) + ".   ")
  }
  DEFINE_FILER ((GetSgsValue ("INDIC,1,$I,1")))
  DataLineOrNoStatement ("               06 LIND" + ($I) + "  PIC  X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").  ")
}
DataLineOrNoStatement ("       FD  TAPEOUT  ")
DataLineOrNoStatement ("           LABEL RECORD STANDARD")
DataLineOrNoStatement ("           BLOCK  CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + "  RECORDS  ")
DataLineOrNoStatement ("           DATA RECORD IS   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
  DataLineOrNoStatement ("           REC2" + ($I) + " ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  DataLineOrNoStatement ("           RECTOT-O" + ($I) + " ")
}
DataLineOrNoStatement ("           RECOUT.  ")
If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
  DataLineOrNoStatement ("       01  RECOUT   PIC   X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ")  DISP-1.")
} else {
  DataLineOrNoStatement ("       01  RECOUT   PIC   X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
    DataLineOrNoStatement ("       01  REC2" + ($I) + "  DISP-1.")
  } else {
    DataLineOrNoStatement ("       01  REC2" + ($I) + ".")
  }
  DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
  DataLineOrNoStatement ("           06 ZONO" + ($I) + ". ")
  $A2 = ((GetSgsValue ("FIELDOUT,1,$I,2")) - 1)
  DataLineOrNoStatement ("              08  ANNEE-" + ($I) + "      PIC X.")
  DataLineOrNoStatement ("              08  FILLER          PIC X(" + ($A2) + "). ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 1)) {
    DataLineOrNoStatement ("       01  RECTOT-O" + ($I) + "   DISP-1.   ")
  } else {
    DataLineOrNoStatement ("       01  RECTOT-O" + ($I) + ".")
  }
  DEFINE_FILER ((GetSgsValue ("TOTOUT,1,$I,1")))
  DataLineOrNoStatement ("               06 TOTAL-O" + ($I) + " PIC S9(" + ((GetSgsValue ("TOTOUT,1,$I,2"))) + ").   ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  TEST-SIECLE  PIC X.  ")
DataLineOrNoStatement ("       77  TESTFIN  PIC   9 VALUE 0.")
DataLineOrNoStatement ("       77  NB-LUS   PIC   9(6)   VALUE 0.   ")
DataLineOrNoStatement ("       77  NB-ECR   PIC   9(6)   VALUE 0.   ")
DataLineOrNoStatement ("       77  ERREUR   PIC   9 VALUE 0.")
DataLineOrNoStatement ("       77  PREMIER     PIC   9(10) COMP VALUE  0.   ")
DataLineOrNoStatement ("       01  TOTAL.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  DataLineOrNoStatement ("           03  MONT" + ($I) + "   PIC  S9(18)  VALUE  ZEROES.   ")
  DataLineOrNoStatement ("           03 FILLER PIC X. ")
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  W-INDIC. ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           02  IND" + ($I) + "    PIC  X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").")
  }
  DataLineOrNoStatement ("       01  W-INDIC-OLD. ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           02  IND" + ($I) + "     PIC  X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
  }
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  DataLineOrNoStatement ("       01  TOTAL-OUT" + ($I) + " PIC S9(" + ((GetSgsValue ("TOTOUT,1,$I,2"))) + ") VALUE ZEROES.   ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  DataLineOrNoStatement ("       01  TOTAL-LU" + ($I) + " PIC S9(18) VALUE ZEROES.")
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  DataLineOrNoStatement ("       01  EUW002.  ")
  DataLineOrNoStatement ("           03  WS-PTR-ENE.  ")
  DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-ENE.  ")
  DataLineOrNoStatement ("                   07  MT-ENE              PIC S9(17).  ")
  DataLineOrNoStatement ("                   07  MT-ENE-SGN          PIC X(01).   ")
  DataLineOrNoStatement ("                   07  MT-ENE-CHI          PIC 9(02).   ")
  DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-SRT.  ")
  DataLineOrNoStatement ("                   07  LG-MAX-MON-SRT      PIC 9(03).   ")
  DataLineOrNoStatement ("                   07  CD-FMT-MON-SRT      PIC X(01).   ")
  DataLineOrNoStatement ("                   07  WS-PTR-FAC-MON-SRT.  ")
  DataLineOrNoStatement ("                       09  FL-IMP-APO      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-EUR      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-BEF      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-PLT-SGN      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-TRD-SGN      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-SGN-FIX      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-SGN-VUE      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-CAD-PRC      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-CAD-CNV      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-PNT      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-000          PIC X(01).   ")
  DataLineOrNoStatement ("                       09  CD-DET-MON      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FILLER          PIC X(19).   ")
  DataLineOrNoStatement ("           03  WS-PTR-SRT.  ")
  DataLineOrNoStatement ("               05  WS-MON-SRT-001.  ")
  DataLineOrNoStatement ("                   07  MT-SRT              PIC X(100).  ")
  DataLineOrNoStatement ("               05  WS-MON-SRT-002.  ")
  DataLineOrNoStatement ("                   07  MT-SRT-PRC          PIC X(50).   ")
  DataLineOrNoStatement ("                   07  MT-SRT-CNV          PIC X(50).   ")
  DataLineOrNoStatement ("                   07  TL-PTH-GCH          PIC X(01).   ")
  DataLineOrNoStatement ("                   07  TL-PTH-DRT          PIC X(01).   ")
  DataLineOrNoStatement ("               05  LG-MON-SRT              PIC 9(02).   ")
  DataLineOrNoStatement ("               05  LB-DVI-PRC              PIC X(03).   ")
  DataLineOrNoStatement ("               05  LB-DVI-CNV              PIC X(03).   ")
  DataLineOrNoStatement ("           03  WS-PTR-ENE-SRT.  ")
  DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
  DataLineOrNoStatement ("           03  WS-IFN-EUR.  ")
  DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
  DataLineOrNoStatement ("       01  WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           03  NM-PGM-APL               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-ENV               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-COP               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-DEM               PIC X(08).  ")
  DataLineOrNoStatement ("           03  VL-CDE-RET               PIC S9(04). ")
  DataLineOrNoStatement ("           03  VL-MOT-CDE               PIC S9(04). ")
  DataLineOrNoStatement ("           03  LB-MSG-RET               PIC X(30).  ")
  DataLineOrNoStatement ("           03  CD-DBG-PRG               PIC X(1).   ")
  DataLineOrNoStatement ("           03  FILLER                   PIC X(7).   ")
  DataLineOrNoStatement ("           03  VL-CHP-TSF               PIC X(3922).")
  DataLineOrNoStatement ("       01  RDMS-QUALIFIER                        PIC X(12). ")
  DataLineOrNoStatement ("       01  RDMS-IND                              PIC 9(2).  ")
  DataLineOrNoStatement ("       01  RDMS-STATUS                           PIC 9999  VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-SAV-STATUS                       PIC 9999  VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-ROLLB                            PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-COLUMN                           PIC S1(36).")
  DataLineOrNoStatement ("       01  RDMS-SAV-COLUMN                       PIC S1(36).")
  DataLineOrNoStatement ("       01  RDMS-FLAG                             PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-FLAG-THREAD                      PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-RESULT. ")
  DataLineOrNoStatement ("             05 RDMS-ERROR-LINE OCCURS 4         PIC X(80). ")
  DataLineOrNoStatement ("       01  RDMS-COM.")
  DataLineOrNoStatement ("             05 RLIN            OCCURS 36        PIC X(40). ")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   ")
DataLineOrNoStatement ("           OPEN INPUT TAPEIN.   ")
DataLineOrNoStatement ("           OPEN  OUTPUT  TAPEOUT.   ")
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           CALL 'RSA`$INIT'. ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'BEGIN THREAD FOR APPLICATION UDSSRC READ;',   ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 1 TO RDMS-FLAG-THREAD.  ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'USE DEFAULT QUALIFIER " + ($schname) + ";',   ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'USE DEFAULT VERSION PRODUCTION ;',")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           MOVE 'RECAP'     TO NM-PGM-APL   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'BATCH'     TO NM-NOM-ENV   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO CD-DBG-PRG   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'EUW002'    TO NM-NOM-COP   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'SERVICE1'  TO NM-NOM-DEM   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE SPACES      TO WS-PTR-ENE   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE 'R'         TO FL-PLT-SGN   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE '2'         TO FL-TRD-SGN   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO MT-ENE-SGN   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE '1'         TO CD-FMT-MON-SRT  OF EUW002.   ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO FL-IMP-PNT      OF EUW002.   ")
  DataLineOrNoStatement ("           MOVE 'N'         TO FL-000          OF EUW002.   ")
}
DataLineOrNoStatement ("           MOVE SPACES TO RECOUT.   ")
If ((CompareTypeSafe (GetSgsValue ("INPUT")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE INPUT MANQUANTE' UPON PRINTER.")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("OUTPUT")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE OUTPUT MANQUANTE' UPON PRINTER.   ")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE FIELDIN MANQUANTE' UPON PRINTER.  ")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE FIELDOUT MANQUANTE' UPON PRINTER. ")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("TOTIN")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE TOTIN MANQUANTE' UPON PRINTER.")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("TOTOUT")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE TOTOUT MANQUANTE' UPON PRINTER.   ")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           DISPLAY 'CARTE INDIC MANQUANTE' UPON PRINTER.")
  DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
  DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
  DataLineOrNoStatement ("           STOP RUN.")
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("ASCIIFD")) "EqualTo" 0)) {
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
      DataLineOrNoStatement ("           DISPLAY 'CARTE COMPILATEUR ABSENTE' UPON PRINTER.")
      DataLineOrNoStatement ("           PERFORM RAPPEL.  ")
      DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
      DataLineOrNoStatement ("           STOP RUN.")
    }
  }
}
DataLineOrNoStatement ("       LECT.")
DataLineOrNoStatement ("           MOVE W-INDIC TO W-INDIC-OLD. ")
DataLineOrNoStatement ("           READ  TAPEIN  AT  END MOVE 1 TO TESTFIN  GO TO  RUPTURE. ")
DataLineOrNoStatement ("           ADD 1 TO NB-LUS. ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  DataLineOrNoStatement ("           IF TOTAL" + ($I) + " NUMERIC ")
  DataLineOrNoStatement ("           ADD TOTAL" + ($I) + " TO TOTAL-LU" + ($I))
  DataLineOrNoStatement ("           ELSE ")
  DataLineOrNoStatement ("           EXAMINE TOTAL" + ($I) + " REPLACING ALL SPACES BY ZERO   ")
  DataLineOrNoStatement ("           ADD TOTAL" + ($I) + " TO TOTAL-LU" + ($I) + ".   ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
  DataLineOrNoStatement ("           MOVE  LIND" + ($I) + "  TO  IND" + ($I) + "  OF  W-INDIC.")
}
DataLineOrNoStatement ("           IF PREMIER =  0 MOVE 1 TO PREMIER GO TO EGALITE. ")
DataLineOrNoStatement ("           IF W-INDIC-OLD GREATER THAN W-INDIC GO TO ERR-SEQ.   ")
DataLineOrNoStatement ("           IF W-INDIC NOT EQUAL TO W-INDIC-OLD GO TO RUPTURE.   ")
DataLineOrNoStatement ("           GO TO EGALITE.   ")
DataLineOrNoStatement ("       RUPTURE. ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  DataLineOrNoStatement ("           MOVE TOTAL-OUT" + ($I) + " TO TOTAL-O" + ($I) + ".   ")
  DataLineOrNoStatement ("           MOVE ZEROES TO TOTAL-OUT" + ($I) + ".")
}
DataLineOrNoStatement ("           WRITE RECOUT.")
DataLineOrNoStatement ("           MOVE SPACES TO RECOUT.   ")
DataLineOrNoStatement ("           ADD 1 TO NB-ECR. ")
DataLineOrNoStatement ("           IF TESTFIN = 1 GO TO FINW.   ")
DataLineOrNoStatement ("           GO TO EGALITE.   ")
DataLineOrNoStatement ("       ERR-SEQ. ")
DataLineOrNoStatement ("           DISPLAY '**ANCIEN INDIC** ' W-INDIC-OLD  ")
DataLineOrNoStatement ("           DISPLAY '**NOUVEL INDIC** ' W-INDIC. ")
DataLineOrNoStatement ("           DISPLAY '**ERREUR DE SEQUENCE** '.   ")
DataLineOrNoStatement ("           CLOSE TAPEIN TAPEOUT.")
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'END THREAD ;',")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG-THREAD.  ")
}
DataLineOrNoStatement ("           CALL 'ABORT'.")
DataLineOrNoStatement ("       EGALITE. ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
  DataLineOrNoStatement ("           MOVE ZONE" + ($I) + " TO ZONO" + ($I) + ".   ")
  If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
    For ([Int32]$JLH = 2; $JLH -le (GetSgsValue ("Y2K,1")); $JLH++) { 
      $JJJ = (GetSgsValue ("Y2K,1,$JLH,2"))
      If ((CompareTypeSafe $JJJ "EqualTo" $I)) {
        DataLineOrNoStatement ("           IF SIECLE-" + ($I) + " = '20'")
        DataLineOrNoStatement ("              MOVE ZONE" + ($I) + " TO TEST-SIECLE  ")
        DataLineOrNoStatement ("              IF TEST-SIECLE = '0' MOVE ';' TO ANNEE-" + ($I) + "   ")
        DataLineOrNoStatement ("              ELSE  ")
        DataLineOrNoStatement ("              IF TEST-SIECLE = '1' MOVE '_' TO ANNEE-" + ($I) + "   ")
        DataLineOrNoStatement ("              ELSE  ")
        DataLineOrNoStatement ("              IF TEST-SIECLE = '2' MOVE '|' TO ANNEE-" + ($I) + "   ")
        DataLineOrNoStatement ("              ELSE  ")
        DataLineOrNoStatement ("              IF TEST-SIECLE = '3' MOVE '~' TO ANNEE-" + ($I) + ".  ")
      }
    }
  }
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  DataLineOrNoStatement ("           ADD TOTAL" + ($I) + " TO TOTAL-OUT" + ($I) + " MONT" + ($I) + ". ")
}
DataLineOrNoStatement ("           GO TO LECT.  ")
DataLineOrNoStatement ("       FINW.")
DataLineOrNoStatement ("           EXAMINE NB-LUS REPLACING LEADING ZEROES BY SPACES.   ")
DataLineOrNoStatement ("           EXAMINE NB-ECR REPLACING LEADING ZEROES BY SPACES.   ")
DataLineOrNoStatement ("           DISPLAY  '*RECAP  FIN*'  UPON  PRINTER.  ")
DataLineOrNoStatement ("           DISPLAY  '*NB-ENREG-LUS ='  NB-LUS  UPON  PRINTER.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTIN,1")); $I++) { 
  $NEURO = 0
  DataLineOrNoStatement ("           EXAMINE TOTAL-LU" + ($I) + " REPLACING LEADING ZEROES BY SPACES. ")
  If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
    DataLineOrNoStatement ("           DISPLAY TOTAL-LU" + ($I) + " UPON PRINTER.   ")
  } else {
    If ((CompareTypeSafe (GetSgsValue ("NEURO")) "GreaterThan" 0)) {
      For ([Int32]$Z = 1; $Z -le (GetSgsValue ("$NEURO,1")); $Z++) { 
        If ((CompareTypeSafe (GetSgsValue ("$NEURO,1,$Z,1")) "EqualTo" $I)) {
          $NEURO = 1
        }
      }
    }
    If ((CompareTypeSafe $NEURO "GreaterThan" 0)) {
      DataLineOrNoStatement ("           DISPLAY TOTAL-LU" + ($I) + " UPON PRINTER.   ")
    } else {
      DataLineOrNoStatement ("           MOVE 17     TO MT-ENE-CHI OF EUW002. ")
      DataLineOrNoStatement ("           MOVE 25     TO LG-MAX-MON-SRT OF EUW002. ")
      DataLineOrNoStatement ("           MOVE TOTAL-LU" + ($I) + " TO MT-ENE OF EUW002.   ")
      DataLineOrNoStatement ("           MOVE EUW002       TO VL-CHP-TSF  OF WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           CALL 'EUU003'     USING WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           MOVE VL-CHP-TSF   OF WS-CMT-PGM TO EUW002.   ")
      DataLineOrNoStatement ("           DISPLAY MT-SRT    OF EUW002 UPON PRINTER.")
    }
  }
}
DataLineOrNoStatement ("           DISPLAY  '*NB-ENREG-ECR ='  NB-ECR  UPON  PRINTER.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("TOTOUT,1")); $I++) { 
  $NEURO = 0
  DataLineOrNoStatement ("           EXAMINE MONT" + ($I) + " REPLACING LEADING ZEROES BY SPACES. ")
  If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
    DataLineOrNoStatement ("           DISPLAY MONT" + ($I) + " UPON PRINTER.   ")
  } else {
    If ((CompareTypeSafe (GetSgsValue ("NEURO")) "GreaterThan" 0)) {
      For ([Int32]$Z = 1; $Z -le (GetSgsValue ("$NEURO,1")); $Z++) { 
        If ((CompareTypeSafe (GetSgsValue ("$NEURO,1,$Z,1")) "EqualTo" $I)) {
          $NEURO = 1
        }
      }
    }
    If ((CompareTypeSafe $NEURO "GreaterThan" 0)) {
      DataLineOrNoStatement ("           DISPLAY MONT" + ($I) + " UPON PRINTER.   ")
    } else {
      DataLineOrNoStatement ("           MOVE 17     TO MT-ENE-CHI OF EUW002. ")
      DataLineOrNoStatement ("           MOVE 25     TO LG-MAX-MON-SRT OF EUW002. ")
      DataLineOrNoStatement ("           MOVE MONT" + ($I) + " TO MT-ENE OF EUW002.   ")
      DataLineOrNoStatement ("           MOVE EUW002       TO VL-CHP-TSF  OF WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           CALL 'EUU003'     USING WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           MOVE VL-CHP-TSF   OF WS-CMT-PGM TO EUW002.   ")
      DataLineOrNoStatement ("           DISPLAY MT-SRT    OF EUW002 UPON PRINTER.")
    }
  }
}
DataLineOrNoStatement ("           CLOSE  TAPEIN.   ")
DataLineOrNoStatement ("           CLOSE  TAPEOUT.  ")
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'END THREAD ;',")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG-THREAD.  ")
}
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       RAPPEL.  ")
DataLineOrNoStatement ("           DISPLAY 'RELISEZ ATTENTIVEMENT MODE D EMPLOI DE RECAP'   ")
DataLineOrNoStatement ("           UPON PRINTER.")
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 0)) {
  DataLineOrNoStatement ("       RDMS-ERROR-PAR.  ")
  DataLineOrNoStatement ("           DISPLAY '*** ERROR RDMS ***' UPON PRINTER.   ")
  DataLineOrNoStatement ("           DISPLAY 'COLUMN = ' RDMS-COLUMN UPON PRINTER.")
  DataLineOrNoStatement ("           DISPLAY 'STATUS = ' RDMS-STATUS UPON PRINTER.")
  DataLineOrNoStatement ("           PERFORM TRAIT-RDMS.  ")
  DataLineOrNoStatement ("           GO TO RDMS-ERROR-EX. ")
  DataLineOrNoStatement ("       TRAIT-RDMS.  ")
  DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           PERFORM VISU-RDMS-COM VARYING RDMS-IND FROM 1 BY 1   ")
  DataLineOrNoStatement ("               UNTIL RDMS-IND > 36. ")
  DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           PERFORM TRAIT-RDMS-ERROR ")
  DataLineOrNoStatement ("               UNTIL RDMS-FLAG NOT = ZEROS. ")
  DataLineOrNoStatement ("       TRAIT-RDMS-ERROR.")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'GETERROR INTO `$P1, `$P2, `$P3, `$P4 ;',  ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN,  ")
  DataLineOrNoStatement ("             RDMS-ERROR-LINE (1), RDMS-ERROR-LINE (2),  ")
  DataLineOrNoStatement ("             RDMS-ERROR-LINE (3), RDMS-ERROR-LINE (4).  ")
  DataLineOrNoStatement ("           PERFORM VISU-RDMS-ERROR  ")
  DataLineOrNoStatement ("             VARYING RDMS-IND FROM 1 BY 1   ")
  DataLineOrNoStatement ("             UNTIL RDMS-IND > 4.")
  DataLineOrNoStatement ("       VISU-RDMS-ERROR. ")
  DataLineOrNoStatement ("           IF RDMS-ERROR-LINE (RDMS-IND) NOT = SPACE")
  DataLineOrNoStatement ("                DISPLAY RDMS-ERROR-LINE (RDMS-IND) UPON PRINTER ")
  DataLineOrNoStatement ("           ELSE MOVE 1 TO RDMS-FLAG.")
  DataLineOrNoStatement ("       VISU-RDMS-COM.   ")
  DataLineOrNoStatement ("           IF RLIN (RDMS-IND) NOT = SPACES  ")
  DataLineOrNoStatement ("                DISPLAY RLIN (RDMS-IND) UPON PRINTER.   ")
  DataLineOrNoStatement ("       RDMS-ERROR-EX.   ")
}
If ((CompareTypeSafe (GetSgsValue ("CFH")) "EqualTo" 1)) {
  # @MAP N     ASSURFED*UTILIT.MAP,TPF$.RECAP   
  Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILIT\MAP")
  Hdg "N"
  Fin
} else {
  # @MAP N                             ,TPF$.RECAP  
  Call-ExternalProgram "MAP" "N" (",TPF`$\RECAP")
  # Orphaned data line: IBANK,XU C$DML
  # Orphaned data line: IBANK,M  I$1,022000
  # Orphaned data line: IN       TPF$.
  # Orphaned data line: IN SYS$LIB$*ACOB-DML.CBEP$$ACOB/FULL-LIB-CB
  # Orphaned data line: IN SYS$LIB$*RSA.RDMR-ACOBDAT
  # Orphaned data line: IN SYS$LIB$*RSA.CBEP$$RSA
  # Orphaned data line: DBANK,MUC    D$1
  # Orphaned data line: FORM         I$1
  # Orphaned data line: LIB          PRD*REL.
  # Orphaned data line: LIB          SYS*REL.
  Fin
}
