# Converted from SSG source: SCAN_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filunasc {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILUNASC") {
    Return
  }

  $FIL4 = ($Parameters[0] - 1)
  If ($FIL4) {
    DataLineOrNoStatement ("           03  FILLER         PIC X(" + ($FIL4) + ").   ")
  }
}
Function Define_fildeuasc {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILDEUASC") {
    Return
  }

  $FIL5 = ($Parameters[0] - ($Parameters[1] - ($Parameters[2] + 1)))
  If ($FIL5) {
    DataLineOrNoStatement ("           03  FILLER           PIC X(" + ($FIL5) + "). ")
  }
}
Function Define_fillset {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLSET") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
}
Function Define_fildeu {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILDEU") {
    Return
  }

  $FILCT2 = ($Parameters[0] - ($Parameters[1] - ($Parameters[2] + 1)))
}
Function Define_fillrem {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLREM") {
    Return
  }

  $FILLCTR = (($Parameters[0] + 99) - ($Parameters[1] - $Parameters[2]))
}
Fin
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB IB     TPF$.NAME$,.   
  Call-ExternalProgram "ACOB" "I, B" ("TPF`$\NAME`$")
  Fin
} else {
  If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
    # @ACOB IBT       TPF$.NAME$,.
    Call-ExternalProgram "ACOB" "I, B, T" ("TPF`$\NAME`$")
    Fin
  } else {
    # @ACOB IBT       TPF$.NAME$,.
    Call-ExternalProgram "ACOB" "I, B, T" ("TPF`$\NAME`$")
    Fin
  }
}
#  
# longueur forc{e @ 4  
$YLG = 4
For ([Int32]$A = 1; $A -le (GetSgsValue ("Y2K")); $A++) { 
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,1,1")) "EqualTo" "IF")) {
    #  
    # --> initialisation nouvelle carte IF 
    #  
    $PAR = "IF"
    $Z1 = (GetSgsValue ("Y2K,$A,2,4"))
    $Z2 = (GetSgsValue ("Y2K,$A,2,2"))
    $Z4 = ($Z2 - 1)
    For ([Int32]$Z3 = 1; $Z3 -le $Z4; $Z3++) { 
      If ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$Z3")) "GreaterThan" 1)) {
        $PAR = $PAR + " " + (GetSgsValue ("IF,$Z1,Z3,1")) + "," + (GetSgsValue ("IF,$Z1,Z3,2"))
      } else {
        $PAR = $PAR + " " + (GetSgsValue ("IF,$Z1,Z3,1"))
      }
    }
    # boucle sur le nombre de champs de la carte Y2K   
    For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,$A")); $B++) { 
      # initialisations  
      $Z1 = (GetSgsValue ("Y2K,$A,$B,4"))
      $Z2 = (GetSgsValue ("Y2K,$A,$B,2"))
      $YCH = 2
      If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,2")) "GreaterThan" 0)) {
        $YCH = (GetSgsValue ("Y2K,$A,B,2"))
      }
      $YPOS = 1
      If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,1")) "GreaterThan" 0)) {
        $YPOS = (GetSgsValue ("Y2K,$A,B,1"))
      }
      #  
      #boucle @ partir du premier champ @ traiter --> dernier champ carte IF 
      #  @ traiter -1.   
      #  
      If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
        $V4 = (GetSgsValue ("Y2K,$A"))
      } else {
        $V4 = ($B + 1)
      }
      If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
        $SOIF = (GetSgsValue ("IF,$Z1"))
      } else {
        $V3 = (GetSgsValue ("Y2K,$A,$V4,2"))
        $SOIF = ($V3 - 1)
      }
      #  
      For ([Int32]$BCL = $Z2; $BCL -le $SOIF; $BCL++) { 
        If ((CompareTypeSafe $BCL "EqualTo" (GetSgsValue ("Y2K,$A,$B,2")))) {
          #  
          #traitement du champ r{f{renc{ par une carte Y2K   
          #  
          $SIE = ($YPOS + 2)
          $SI3 = ($YPOS + 3)
          If ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL,1,SUBSTR$,$YPOS,2")) "LessThan" 20)) {
            $YAN = (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$SIE,2"))
          } elseif ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL,1,SUBSTR$,$YPOS,3")) "EqualTo" 200)) {
            $YAN = "(" + (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$SI3,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL,1,SUBSTR$,$YPOS,3")) "EqualTo" 201)) {
            $YAN = "_" + (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$SI3,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL,1,SUBSTR$,$YPOS,3")) "EqualTo" 202)) {
            $YAN = "|" + (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$SI3,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL,1,SUBSTR$,$YPOS,3")) "EqualTo" 203)) {
            $YAN = "~" + (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$SI3,1"))
          }
          $YLS = ($YPOS - 1)
          If ((CompareTypeSafe $YPOS "EqualTo" 1)) {
            $YTR = $YAN
          } else {
            $YTR = (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,1,$YLS")) + " " + $YAN
          }
          $YLS = ($YLG + $YPOS)
          $YLG1 = ((GetSgsValue ("IF,$Z1,$BCL,1,LEN$")) - ($YLS + 1))
          If ((CompareTypeSafe $YLG1 "GreaterThan" 0)) {
            $YTR = $YTR + " " + (GetSgsValue ("IF,$Z1,BCL,1,SUBSTR$,$YLS,YLG1"))
          }
          $PAR = $PAR + " " + $YTR
        } else {
          If ((CompareTypeSafe (GetSgsValue ("IF,$Z1,$BCL")) "GreaterThan" 1)) {
            $PAR = $PAR + " " + (GetSgsValue ("IF,$Z1,BCL,1")) + "," + (GetSgsValue ("IF,$Z1,BCL,2"))
          } else {
            $PAR = $PAR + " " + (GetSgsValue ("IF,$Z1,BCL,1"))
          }
        }
        # fin loop BCL 
      }
      # fin loop B   
    }
    AddTo-SgsList $PAR
    # fin carte IF 
  }
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,1,1")) "EqualTo" "NOCONT")) {
    If ((CompareTypeSafe (GetSgsValue ("NOCONT,1,1")) "GreaterThan" 1)) {
      #  
      # --> initialisation nouvelle carte NOCONT 
      #  
      $PAR = "NOCONT"
      $Z2 = (GetSgsValue ("Y2K,$A,2,2"))
      $Z4 = ($Z2 - 1)
      For ([Int32]$Z3 = 1; $Z3 -le $Z4; $Z3++) { 
        $PAR = $PAR + " " + (GetSgsValue ("NOCONT,1,$Z3,1")) + "," + (GetSgsValue ("NOCONT,1,$Z3,2")) + "," + (GetSgsValue ("NOCONT,1,$Z3,3"))
      }
      # boucle sur le nombre de champs de la carte Y2K   
      For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,$A")); $B++) { 
        # initialisations  
        $Z2 = (GetSgsValue ("Y2K,$A,$B,2"))
        $YCH = 1
        If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,2")) "GreaterThan" 0)) {
          $YCH = (GetSgsValue ("Y2K,$A,B,2"))
        }
        $YPOS = 1
        If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,1")) "GreaterThan" 0)) {
          $YPOS = (GetSgsValue ("Y2K,$A,B,1"))
        }
        #  
        #boucle @ partir du premier champ @ traiter --> dernier champ carte
        #  NOCONT @ traiter -1.
        #  
        If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
          $V4 = (GetSgsValue ("Y2K,$A"))
        } else {
          $V4 = ($B + 1)
        }
        If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
          $SOIF = (GetSgsValue ("NOCONT,1"))
        } else {
          $V3 = (GetSgsValue ("Y2K,$A,$V4,2"))
          $SOIF = ($V3 - 1)
        }
        #  
        For ([Int32]$BCL = $Z2; $BCL -le $SOIF; $BCL++) { 
          If ((CompareTypeSafe $BCL "EqualTo" (GetSgsValue ("Y2K,$A,$B,2")))) {
            #  
            #traitement du champ r{f{renc{ par une carte Y2K   
            #  
            $SIE = ($YPOS + 2)
            $SI3 = ($YPOS + 3)
            If ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YPOS,2")) "LessThan" 20)) {
              $YAN = (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$SIE,2"))
            } elseif ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 200)) {
              $YAN = "(" + (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 201)) {
              $YAN = "_" + (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 202)) {
              $YAN = "|(" + (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 203)) {
              $YAN = "~" + (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$SI3,1"))
            }
            $YLS = ($YPOS - 1)
            If ((CompareTypeSafe $YPOS "EqualTo" 1)) {
              $YTR = $YAN
            } else {
              $YTR = (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,1,$YLS")) + $YAN
            }
            $YLS = ($YLG + $YPOS)
            $YLG1 = ((GetSgsValue ("NOCONT,1,$BCL,3,LEN$")) - ($YLS + 1))
            If ((CompareTypeSafe $YLG1 "GreaterThan" 0)) {
              $YTR = $YTR + " " + (GetSgsValue ("NOCONT,1,$BCL,3,SUBSTR$,$YLS,YLG1"))
            }
            $PAR = $PAR + " " + (GetSgsValue ("NOCONT,1,$BCL,1")) + "," + (GetSgsValue ("NOCONT,1,$BCL,2")) + "," + $YTR
          } else {
            $PAR = $PAR + " " + (GetSgsValue ("NOCONT,1,$BCL,1")) + "," + (GetSgsValue ("NOCONT,1,$BCL,2")) + "," + (GetSgsValue ("NOCONT,1,$BCL,3"))
          }
          # fin loop BCL 
        }
        # fin loop B   
      }
      AddTo-SgsList $PAR
      # fin carte NOCONT 
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,1,1")) "EqualTo" "INDIC")) {
    $MAXINDIC = (GetSgsValue ("INDIC"))
    For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC")); $I++) { 
      #  
      # --> initialisation nouvelle carte INDIC  
      #  
      $PAR = "INDIC"
      $Z2 = (GetSgsValue ("Y2K,$A,2,2"))
      $Z4 = ($Z2 - 1)
      For ([Int32]$Z3 = 1; $Z3 -le $Z4; $Z3++) { 
        $PAR = $PAR + " " + (GetSgsValue ("INDIC,$I,Z3,1")) + "," + (GetSgsValue ("INDIC,$I,Z3,2")) + "," + (GetSgsValue ("INDIC,$I,Z3,3"))
      }
      # boucle sur le nombre de champs de la carte Y2K   
      For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,$A")); $B++) { 
        # initialisations  
        $Z2 = (GetSgsValue ("Y2K,$A,$B,2"))
        $YCH = 1
        If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,2")) "GreaterThan" 0)) {
          $YCH = (GetSgsValue ("Y2K,$A,B,2"))
        }
        $YPOS = 1
        If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,$B,1")) "GreaterThan" 0)) {
          $YPOS = (GetSgsValue ("Y2K,$A,B,1"))
        }
        #  
        #boucle @ partir du premier champ @ traiter --> dernier champ carte
        #  INDIC @ traiter -1. 
        #  
        If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
          $V4 = (GetSgsValue ("Y2K,$A"))
        } else {
          $V4 = ($B + 1)
        }
        If ((CompareTypeSafe $B "EqualTo" (GetSgsValue ("Y2K,$A")))) {
          $SOIF = (GetSgsValue ("INDIC,$I"))
        } else {
          $V3 = (GetSgsValue ("Y2K,$A,$V4,2"))
          $SOIF = ($V3 - 1)
        }
        #  
        For ([Int32]$BCL = $Z2; $BCL -le $SOIF; $BCL++) { 
          If ((CompareTypeSafe $BCL "EqualTo" (GetSgsValue ("Y2K,$A,$B,2")))) {
            #  
            #traitement du champ r{f{renc{ par une carte Y2K   
            #  
            $SIE = ($YPOS + 2)
            $SI3 = ($YPOS + 3)
            If ((CompareTypeSafe (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YPOS,2")) "LessThan" 20)) {
              $YAN = (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$SIE,2"))
            } elseif ((CompareTypeSafe (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 200)) {
              $YAN = "(" + (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 201)) {
              $YAN = "_" + (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 202)) {
              $YAN = "|(" + (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$SI3,1"))
            } elseif ((CompareTypeSafe (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YPOS,3")) "EqualTo" 203)) {
              $YAN = "~" + (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$SI3,1"))
            }
            $YLS = ($YPOS - 1)
            If ((CompareTypeSafe $YPOS "EqualTo" 1)) {
              $YTR = $YAN
            } else {
              $YTR = (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,1,$YLS")) + $YAN
            }
            $YLS = ($YLG + $YPOS)
            $YLG1 = ((GetSgsValue ("INDIC,$I,BCL,3,LEN$")) - ($YLS + 1))
            If ((CompareTypeSafe $YLG1 "GreaterThan" 0)) {
              $YTR = $YTR + " " + (GetSgsValue ("INDIC,$I,BCL,3,SUBSTR$,$YLS,YLG1"))
            }
            $PAR = $PAR + " " + (GetSgsValue ("INDIC,$I,BCL,1")) + "," + (GetSgsValue ("INDIC,$I,BCL,2")) + "," + $YTR
          } else {
            $PAR = $PAR + " " + (GetSgsValue ("INDIC,$I,BCL,1")) + "," + (GetSgsValue ("INDIC,$I,BCL,2")) + "," + (GetSgsValue ("INDIC,$I,BCL,3"))
          }
          # fin loop BCL 
        }
        # fin loop B   
      }
      AddTo-SgsList $PAR
      # fin loop I   
    }
    # fin carte INDIC  
  }
  # fin loop A   
}
#  
#  Delete anciennes cartes @ modifier. 
#  
$IFOK = 0
For ([Int32]$F = 1; $F -le (GetSgsValue ("Y2K")); $F++) { 
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$F,1,1")) "EqualTo" "IF")) {
    $F1 = ((GetSgsValue ("Y2K,$F,2,4")) - $IFOK)
    RemoveFrom-SgsList "IF" $F1 1
    $IFOK = ($IFOK + 1)
  } elseif ((CompareTypeSafe (GetSgsValue ("Y2K,$F,1,1")) "EqualTo" "NOCONT")) {
    RemoveFrom-SgsList "NOCONT" 1 1
  } elseif ((CompareTypeSafe (GetSgsValue ("Y2K,$F,1,1")) "EqualTo" "INDIC")) {
    RemoveFrom-SgsList "INDIC" 1 $MAXINDIC
  }
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. SCAN.")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY P. ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER.  UNIVAC-1100-60EIS. ")
DataLineOrNoStatement ("       OBJECT-COMPUTER.  UNIVAC-1100-60EIS. ")
DataLineOrNoStatement ("       SPECIAL-NAMES.  PRINTER IS LISTE.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN   ")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("                              UNISERVO " + ((GetSgsValue ("INPUT,1,1,1"))) + ".   ")
} else {
  DataLineOrNoStatement ("                              DISC " + ((GetSgsValue ("INPUT,1,1,1"))) + ".   ")
}
DataLineOrNoStatement ("           SELECT  PRT  ASSIGN  TO  PRINTER.")
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  TAPEIN   ")
If ((CompareTypeSafe (GetSgsValue ("OMITTED")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("                   LABEL RECORD IS OMITTED  ")
} else {
  DataLineOrNoStatement ("                   LABEL RECORD IS STANDARD ")
}
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "  RECORDS")
DataLineOrNoStatement ("           RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,1,2"))) + "  CHARACTERS")
DataLineOrNoStatement ("           DATA RECORD IS REC-IN.   ")
DataLineOrNoStatement ("       01  REC-IN             PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + "). ")
DataLineOrNoStatement ("       FD  PRT      LABEL RECORD IS OMITTED  DATA RECORD IS PRT-LINE.   ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  PRT-LINE          PIC X(100)          USAGE  DISPLAY-1.  ")
} else {
  DataLineOrNoStatement ("       01  PRT-LINE           PIC X(100).   ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       01  ZONE-LECTURE PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("       01  ZONE-LECTURE" + ($I) + " REDEFINES ZONE-LECTURE. ")
    DEFINE_FILUNASC ((GetSgsValue ("INDIC,1,$I,1")))
    DataLineOrNoStatement ("               03 INDIC" + ($I) + " PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
    DEFINE_FILDEUASC ((GetSgsValue ("INPUT,1,1,2"))) ((GetSgsValue ("INDIC,1,$I,1"))) ((GetSgsValue ("INDIC,1,$I,2")))
  }
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  W-INDIC. ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           02 IND" + ($I) + " PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + "). ")
  }
  DataLineOrNoStatement ("       01  W-INDIC-1.   ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           02 IND-1" + ($I) + " PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
  }
}
DataLineOrNoStatement ("       01  REC-AREA.")
$AA = 0
For ([Int32]$A = 1; $A -le (GetSgsValue ("INPUT,1,1,2")); $A += 100) { 
  DataLineOrNoStatement ("           03  PRINT-LINE-" + ($A) + "             PIC X(100).  ")
  $AA = $A
}
If ((CompareTypeSafe (GetSgsValue ("IF")) "GreaterThan" 0)) {
  For ([Int32]$RD = 1; $RD -le (GetSgsValue ("IF")); $RD++) { 
    If ((CompareTypeSafe (GetSgsValue ("IF,$RD,1,1")) "EqualTo" "OR")) {
      $IFPTR = 2
    } else {
      $IFPTR = 1
    }
    If ((CompareTypeSafe -not (GetSgsValue ("IF,$RD,$IFPTR,1")) "EqualTo" "R ;")) {
      DataLineOrNoStatement (" AND  NOT  " + ((GetSgsValue ("IF,$RD,$IFPTR,1"))) + "  = RECORD")
      DataLineOrNoStatement ("       01  REC-AREA-REDEFINES-" + ($RD) + "  REDEFINES  REC-AREA.   ")
      DEFINE_FILLSET ((GetSgsValue ("IF,$RD,$IFPTR,1")))
      If ($FILLCTR) {
        DataLineOrNoStatement ("           03  FILLER         PIC X(" + ($FILLCTR) + ").")
      }
      DataLineOrNoStatement ("           03  FIELD-" + ($RD) + "         PIC X(" + ((GetSgsValue ("IF,$RD,$IFPTR,2"))) + ").  ")
      DEFINE_FILLREM ($AA) ($FILLCTR) ((GetSgsValue ("IF,$RD,$IFPTR,2")))
      If ($FILLCTR) {
        DataLineOrNoStatement ("           03  FILLER         PIC X(" + ($FILLCTR) + ").")
      }
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("NOCONT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("NOCONT,1,1")) "GreaterThan" 1)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("NOCONT,1")); $I++) { 
      DataLineOrNoStatement ("       01  AREARU" + ($I) + " REDEFINES REC-AREA.   ")
      DEFINE_FILLSET ((GetSgsValue ("NOCONT,1,$I,1")))
      If ($FILLCTR) {
        DataLineOrNoStatement ("           03  FILLER      PIC X(" + ($FILLCTR) + ").   ")
      }
      DataLineOrNoStatement ("           03  FILTSTRU" + ($I) + "   PIC X(" + ((GetSgsValue ("NOCONT,1,$I,2"))) + ").")
      DEFINE_FILDEU ((GetSgsValue ("INPUT,1,1,2"))) ((GetSgsValue ("NOCONT,1,$I,1"))) ((GetSgsValue ("NOCONT,1,$I,2")))
      If ($FILCT2) {
        DataLineOrNoStatement ("           03  FILLER      PIC X(" + ($FILCT2) + ").")
      }
    }
    DataLineOrNoStatement ("       01  TSTFINA. ")
    For ([Int32]$K = 1; $K -le (GetSgsValue ("NOCONT,1")); $K++) { 
      DataLineOrNoStatement ("           03  TSTFINA" + ($K) + "      PIC X(" + ((GetSgsValue ("NOCONT,1,$K,2"))) + ")   ")
      If ((CompareTypeSafe (GetSgsValue ("NOCONT,1,$K,3")) "EqualTo" "BLANC")) {
        DataLineOrNoStatement ("               VALUE SPACES.")
      } else {
        DataLineOrNoStatement ("               VALUE '" + ((GetSgsValue ("NOCONT,1,$K,3"))) + "'.  ")
      }
    }
    DataLineOrNoStatement ("       01  MOTST.   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("NOCONT,1")); $I++) { 
      DataLineOrNoStatement ("           03  MOTST" + ($I) + "    PIC X(" + ((GetSgsValue ("NOCONT,1,$I,2"))) + ").  ")
    }
  } else {
    DataLineOrNoStatement ("       01  TSTFINB      PIC S9(7) VALUE " + ((GetSgsValue ("NOCONT,1,1,1"))) + ". ")
  }
}
DataLineOrNoStatement ("       01  SKIP                         PIC  9(10)  COMP VALUE 0.   ")
DataLineOrNoStatement ("       01  LINE-CNT            PIC 9(10) COMP    VALUE 66.  ")
DataLineOrNoStatement ("       01  REC-IN-CT                    PIC  9(10)  COMP VALUE 0.   ")
DataLineOrNoStatement ("       01  REC-FOUND-CT                 PIC 9(10) COMP VALUE 0. ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  H-LINE   USAGE DISPLAY-1.")
} else {
  DataLineOrNoStatement ("       01  H-LINE.  ")
}
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
DataLineOrNoStatement ("           03 FILLER    PIC X(10) VALUE '1234567890'.   ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  CT-LINE                               USAGE  DISPLAY-1.  ")
} else {
  DataLineOrNoStatement ("       01  CT-LINE. ")
}
DataLineOrNoStatement ("           03 FILLER       PIC XX  VALUE '**'.  ")
DataLineOrNoStatement ("           03 CT-CT        PIC ZZZZZZ9. ")
DataLineOrNoStatement ("           03 FILLER        PIC XX   VALUE '**'.")
DataLineOrNoStatement ("           03 FILLER          PIC X(121) VALUE SPACES.  ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  F-LINE  USAGE DISPLAY-1. ")
} else {
  DataLineOrNoStatement ("       01  F-LINE.  ")
}
DataLineOrNoStatement ("           03 FILLER        PIC XX  VALUE '**'. ")
DataLineOrNoStatement ("           03 F-CT        PIC ZZZZZZ9.  ")
DataLineOrNoStatement ("           03 FILLER         PIC XX   VALUE '**'.   ")
DataLineOrNoStatement ("           03 FILLER          PIC X(08) VALUE '........'.   ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '2.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '3.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '4.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '5.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '6.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '7.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '8.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '9.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '0.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '1.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(10) VALUE '2.........'. ")
DataLineOrNoStatement ("           03 FILLER          PIC X(03) VALUE '3..'.")
DataLineOrNoStatement ("       01  FIVE-CT PIC 9(10) COMP VALUE 6.  ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  M-LINE                                USAGE  DISPLAY-1.  ")
} else {
  DataLineOrNoStatement ("       01  M-LINE.  ")
}
DataLineOrNoStatement ("           03  FILLER         PIC X(20) ")
DataLineOrNoStatement ("               VALUE '** END SCAN **      '.")
DataLineOrNoStatement ("           03  FILLER         PIC X(37) ")
DataLineOrNoStatement ("               VALUE  'RECORDS READ FROM " + ((GetSgsValue ("INPUT,1,1,1"))) + " = '. ")
DataLineOrNoStatement ("           03  M-CT           PIC Z(10)9.   ")
DataLineOrNoStatement ("           03  FILLER         PIC X(19) ")
DataLineOrNoStatement ("               VALUE  ' RECORD MATCHING = '.")
DataLineOrNoStatement ("           03  FN-CT          PIC Z(10)9.   ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       OPEN-FILES SECTION.  ")
DataLineOrNoStatement ("       FIRST-READ.  ")
DataLineOrNoStatement ("           OPEN INPUT  TAPEIN.  OPEN OUTPUT  PRT.   ")
DataLineOrNoStatement ("       LR. READ  TAPEIN  INTO  REC-AREA  AT END  GO TO END-OUT. ")
DataLineOrNoStatement ("           ADD 1 TO REC-IN-CT.  ")
If ((CompareTypeSafe (GetSgsValue ("IF")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       TEST-FIELDS. ")
  $FIELDCT = 0
  $ANDIND = 0
  For ([Int32]$TS = 1; $TS -le (GetSgsValue ("IF")); $TS++) { 
    If ((CompareTypeSafe (GetSgsValue ("IF,$TS,$FIELDCT,1")) "EqualTo" "AND")) {
      $ANDIND = 1
    } else {
      If ((CompareTypeSafe (GetSgsValue ("IF,$TS,$FIELDCT,1")) "EqualTo" "OR")) {
        $ANDIND = 1
      } else {
        DataLineOrNoStatement ("                   GO TO FOUND-REC. ")
        $ANDIND = 0
      }
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("NOCONT")) "GreaterThan" 0)) {
    If ((CompareTypeSafe (GetSgsValue ("NOCONT,1,1")) "GreaterThan" 1)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("NOCONT,1")); $I++) { 
        DataLineOrNoStatement ("           MOVE FILTSTRU" + ($I) + " TO MOTST" + ($I) + ".  ")
      }
      DataLineOrNoStatement ("              INSPECT TSTFINA REPLACING ALL '(' BY ';'. ")
      DataLineOrNoStatement ("              IF MOTST NOT < TSTFINA GO TO END-OUT. ")
    } else {
      DataLineOrNoStatement ("           IF REC-IN-CT NOT < TSTFINB GO TO END-OUT.")
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           GO TO SUITE-RECHERCHE.   ")
  } else {
    DataLineOrNoStatement ("           GO TO LR.")
  }
}
DataLineOrNoStatement ("       SUITE-RECHERCHE. ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE REC-AREA TO ZONE-LECTURE.   ")
  For ([Int32]$N = 1; $N -le (GetSgsValue ("INDIC")); $N++) { 
    For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,$N")); $I++) { 
      DataLineOrNoStatement ("           MOVE INDIC" + ($I) + " TO IND" + ($I))
      If ((CompareTypeSafe (GetSgsValue ("INDIC,$N,$I,3")) "EqualTo" "BLANC")) {
        DataLineOrNoStatement ("           MOVE SPACES TO IND-1" + ($I) + ".")
      } else {
        DataLineOrNoStatement ("           MOVE '" + ((GetSgsValue ("INDIC,$N,I,3"))) + "' TO IND-1" + ($I) + ".   ")
      }
    }
    DataLineOrNoStatement ("           INSPECT W-INDIC-1 REPLACING ALL '(' BY ';'.  ")
    DataLineOrNoStatement ("           IF W-INDIC = W-INDIC-1 GO TO FOUND-REC.  ")
  }
  DataLineOrNoStatement ("           GO TO LR.")
}
DataLineOrNoStatement ("       FOUND-REC.   ")
DataLineOrNoStatement ("           ADD  1  TO  REC-FOUND-CT.")
DataLineOrNoStatement ("           MOVE ZERO  TO  LINE-CNT. ")
DataLineOrNoStatement ("           ADD 1 TO FIVE-CT.")
DataLineOrNoStatement ("           IF FIVE-CT > 9 MOVE REC-IN-CT TO F-CT")
DataLineOrNoStatement ("             WRITE PRT-LINE FROM F-LINE AFTER 1 MOVE 1 TO FIVE-CT   ")
DataLineOrNoStatement ("            ELSE   MOVE REC-IN-CT TO CT-CT  ")
DataLineOrNoStatement ("             WRITE PRT-LINE FROM CT-LINE AFTER 1.   ")
DataLineOrNoStatement ("           ADD 1 TO LINE-CNT.   ")
DataLineOrNoStatement ("           MOVE  1  TO  SKIP.   ")
For ([Int32]$A = 1; $A -le (GetSgsValue ("INPUT,1,1,2")); $A += 100) { 
  DataLineOrNoStatement ("           WRITE  PRT-LINE  FROM  PRINT-LINE-" + ($A) + "  AFTER ADVANCING SKIP.")
  DataLineOrNoStatement ("           ADD 1 TO LINE-CNT.   ")
  DataLineOrNoStatement ("           MOVE 1 TO SKIP.  ")
}
DataLineOrNoStatement ("           MOVE SPACES  TO REC-AREA.")
DataLineOrNoStatement ("           MOVE  1  TO  SKIP.     GO  TO  LR.   ")
DataLineOrNoStatement ("       END-OUT. ")
DataLineOrNoStatement ("           MOVE  REC-IN-CT  TO  M-CT.   ")
DataLineOrNoStatement ("           MOVE REC-FOUND-CT  TO  FN-CT.")
DataLineOrNoStatement ("           WRITE PRT-LINE  FROM  M-LINE AFTER ADVANCING 10 LINES.   ")
DataLineOrNoStatement ("           CLOSE  TAPEIN  PRT.  ")
DataLineOrNoStatement ("           STOP RUN.")
# @MAP N         ASSURFED*UTILITASCII.MAP,TPF$.SCAN   
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
Hdg "N"
Fin
