# Converted from SSG source: TAPELD_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - (1 + "CADR"))
  If ($FILLCTR) {
    DataLineOrNoStatement ("           06 FILLER PIC  X(" + ($FILLCTR) + ").")
  }
}
Function Define_fil1 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL1") {
    Return
  }

  $FILLCTR = (($Parameters[0] + 1) - ($Parameters[1] - $Parameters[2]))
  If ($FILLCTR) {
    DataLineOrNoStatement ("               08 FIS" + ($I) + " PIC  X(" + ($FILLCTR) + ").   ")
  }
}
Function Define_fil2 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL2") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("               08 FIA" + ($I) + " PIC  X(" + ($FILLCTR) + ").   ")
  }
}
Function Define_fil3 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL3") {
    Return
  }

  $FILLCTR = ($Parameters[0] + 2)
}
Function Define_sejp3 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SEJP3") {
    Return
  }

  $J = ($Parameters[0] + 3)
}
Function Define_sw {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SW") {
    Return
  }

  $SW = $Parameters[0]
}
Function Define_inter1 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_INTER1") {
    Return
  }

  $I1 = $Parameters[0]
}
Function Define_cadr {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_CADR") {
    Return
  }

  $CADR = ($CADR + 2)
}
Function Define_interm {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_INTERM") {
    Return
  }

  $INTER = $Parameters[0]
}
$Rgv_CASE = 1
AddTo-SgsList "SCHEMA DEV DBREP"
AddTo-SgsList "SCHEMA TST AFLINC"
AddTo-SgsList "SCHEMA TEMPBEF EU1"
AddTo-SgsList "SCHEMA TEMPEUR EU2"
$SCHNAME = "aflinc"
For ([Int32]$ASCH = 1; $ASCH -le (GetSgsValue ("SCHEMA")); $ASCH++) { 
  Log-Message ((GetSgsValue ("info$,1,3,1")) + " = " + (GetSgsValue ("schema,$asch,1,1"))) '([LogMessageType]::Information)'
  If ((CompareTypeSafe (GetSgsValue ("info$,1,3,1")) "EqualTo" (GetSgsValue ("schema,$ASCH,1,1")))) {
    $SCHNAME = (GetSgsValue ("schema,$asch,2,1"))
    Exit
  }
}
Log-Message ("schema = " + $schname) '([LogMessageType]::Information)'
$CADR = 0
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB IPEC    .CFH-COPY,.CFH-COPY   
  Call-ExternalProgram "ACOB" "I, P, E, C" ("\CFH-COPY")
  Fin
} else {
  # @ACOB IPEC    .CFH-COPY,.CFH-COPY   
  Call-ExternalProgram "ACOB" "I, P, E, C" ("\CFH-COPY")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. 'CFH-COPY'.  ")
DataLineOrNoStatement ("       AUTHOR. MICHEL.  ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       SPECIAL-NAMES.   ")
DataLineOrNoStatement ("           DECIMAL-POINT IS COMMA.  ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN  TO  CARD-READER. ")
} else {
  DataLineOrNoStatement ("           SELECT  TAPEIN  ASSIGN  TO  DISC " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
}
If (((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "CARDPUNCH") -or (CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER"))) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
    DataLineOrNoStatement ("           SELECT   TAPEOUT  ASSIGN  TO  PRINTER.   ")
  } else {
    DataLineOrNoStatement ("           SELECT  TAPEOUT  ASSIGN  TO  CARD-PUNCH. ")
  }
} else {
  DataLineOrNoStatement ("           SELECT  TAPEOUT  ASSIGN  TO  DISC " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".")
}
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           SELECT PRINTOUT ASSIGN TO PRINTER.   ")
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("       FD  PRINTOUT ")
    DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
    DataLineOrNoStatement ("           DATA RECORD IS LISTE.")
    DataLineOrNoStatement ("       01  LISTE PIC X(132).")
  }
}
DataLineOrNoStatement ("       FD  TAPEIN   ")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("           REC1" + ($I) + " ")
    }
    DataLineOrNoStatement ("           RECIN.   ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECIN.   ")
  }
  DataLineOrNoStatement ("       01  RECIN  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").")
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC1" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDIN,1,$I,1")))
      DataLineOrNoStatement ("           06 ZONE" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").  ")
    }
  }
} else {
  DataLineOrNoStatement ("           LABEL  RECORD  STANDARD  ")
  DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "  RECORDS")
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      DataLineOrNoStatement ("           REC1" + ($I) + " ")
    }
    DataLineOrNoStatement ("           RECIN.   ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECIN.   ")
  }
  If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
      If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
        DataLineOrNoStatement ("       01     REC1" + ($I) + "   DISP-1.")
      } else {
        DataLineOrNoStatement ("       01     REC1" + ($I) + ". ")
      }
      DEFINE_FILER ((GetSgsValue ("FIELDIN,1,$I,1")))
      If ((CompareTypeSafe (GetSgsValue ("FIELDIN,1,$I")) "GreaterThan" 2)) {
        DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC  9(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ")V9(" + ((GetSgsValue ("FIELDIN,1,$I,3"))) + ").")
      } else {
        $SW = 0
        If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
          For ([Int32]$A = 2; $A -le (GetSgsValue ("Y2K,1")); $A++) { 
            DEFINE_INTER1 ((GetSgsValue ("Y2K,1,$A,2")))
            If ((CompareTypeSafe $I "EqualTo" $I1)) {
              DataLineOrNoStatement ("           06  ZONE" + ($I) + ".")
              DEFINE_FIL2 ((GetSgsValue ("Y2K,1,$A,1")))
              DataLineOrNoStatement ("               08 ZTI-" + ($I) + "             PIC X(" + ((GetSgsValue ("Y2K,1,$A,3"))) + ").  ")
              DEFINE_FIL1 ((GetSgsValue ("FIELDIN,1,$I1,2"))) ((GetSgsValue ("Y2K,1,$A,3"))) ((GetSgsValue ("Y2K,1,$A,1")))
              DEFINE_SW ((GetSgsValue ("Y2K,1,$A,1")))
            }
          }
        }
        If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
          For ([Int32]$B = 2; $B -le (GetSgsValue ("EURO,1")); $B++) { 
            DEFINE_INTER1 ((GetSgsValue ("EURO,1,$B,1")))
            If ((CompareTypeSafe $I "EqualTo" $I1)) {
              DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC S9(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").   ")
              DEFINE_SW ((GetSgsValue ("EURO,1,$B,1")))
            }
          }
        }
        If ($SW) {
        } else {
          DataLineOrNoStatement ("           06  ZONE" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIELDIN,1,$I,2"))) + ").   ")
        }
      }
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
    DataLineOrNoStatement ("       01  RECIN   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ")  DISP-1.   ")
  } else {
    DataLineOrNoStatement ("       01  RECIN   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
  }
}
DataLineOrNoStatement ("       FD  TAPEOUT  ")
If (((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "CARDPUNCH") -or (CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER"))) {
  DataLineOrNoStatement ("           LABEL  RECORD OMITTED")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("           REC2" + ($I) + " ")
    }
    If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
        DataLineOrNoStatement ("           REC3" + ($I) + " ")
      }
    }
    DataLineOrNoStatement ("           RECOUT.  ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECOUT.  ")
  }
  DataLineOrNoStatement ("       01  RECOUT  PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC2" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
      If ((CompareTypeSafe (GetSgsValue ("FIELDOUT,1,$I")) "GreaterThan" 2)) {
        DataLineOrNoStatement ("           06 ZONO" + ($I) + " PIC 9(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "),9(" + ((GetSgsValue ("FIELDOUT,1,$I,3"))) + "). ")
      } else {
        $SW = 0
        If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
          For ([Int32]$A = 2; $A -le (GetSgsValue ("Y2K,1")); $A++) { 
            DEFINE_INTER1 ((GetSgsValue ("Y2K,1,$A,2")))
            If ((CompareTypeSafe $I "EqualTo" $I1)) {
              DataLineOrNoStatement ("           06  ZONO" + ($I) + ".")
              DEFINE_FIL2 ((GetSgsValue ("Y2K,1,$A,1")))
              DEFINE_FIL3 ((GetSgsValue ("Y2K,1,$A,3")))
              DataLineOrNoStatement ("               08 ZTI-" + ($I) + "             PIC X(" + ($FILLCTR) + ").   ")
              DEFINE_FIL1 ((GetSgsValue ("FIELDIN,1,$I1,2"))) ((GetSgsValue ("Y2K,1,$A,3"))) ((GetSgsValue ("Y2K,1,$A,1")))
              DEFINE_SW ((GetSgsValue ("Y2K,1,$A,1")))
            }
          }
        }
        If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
          For ([Int32]$B = 2; $B -le (GetSgsValue ("EURO,1")); $B++) { 
            DEFINE_INTER1 ((GetSgsValue ("EURO,1,$B,1")))
            If ((CompareTypeSafe $I "EqualTo" $I1)) {
              DEFINE_CADR
              DEFINE_INTERM ((GetSgsValue ("EURO,1,$B,1")))
              DEFINE_FIL3 ((GetSgsValue ("FIELDIN,1,$INTER,2")))
              DataLineOrNoStatement ("           06  ZONO" + ($I) + " PIC X(" + ($FILLCTR) + ").  ")
              DEFINE_SW ((GetSgsValue ("EURO,1,$B,1")))
            }
          }
        }
        If ($SW) {
        } else {
          DataLineOrNoStatement ("           06 ZONO" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "). ")
        }
      }
    }
  }
  $CADR = 0
  If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC3" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIXE,1,$I,1")))
      DataLineOrNoStatement ("           06 FIXDATA" + ($I) + " PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ").  ")
    }
  }
} else {
  DataLineOrNoStatement ("           LABEL  RECORD STANDARD   ")
  DataLineOrNoStatement ("           BLOCK  CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + "  RECORDS  ")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           DATA RECORD IS   ")
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("           REC2" + ($I) + " ")
    }
    If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
      For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
        DataLineOrNoStatement ("           REC3" + ($I) + " ")
      }
    }
    DataLineOrNoStatement ("           RECOUT.  ")
  } else {
    DataLineOrNoStatement ("           DATA RECORD RECOUT.  ")
  }
  DataLineOrNoStatement ("       01  RECOUT   PIC   X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
  If ((CompareTypeSafe (GetSgsValue ("FIELDOUT")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDOUT,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC2" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIELDOUT,1,$I,1")))
      If ((CompareTypeSafe (GetSgsValue ("FIELDOUT,1,$I")) "EqualTo" 3)) {
        DataLineOrNoStatement ("           06  ZONO" + ($I) + "  PIC 9(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "),9(" + ((GetSgsValue ("FIELDOUT,1,$I,3"))) + ").   ")
      } else {
        DataLineOrNoStatement ("           06 ZONO" + ($I) + " PIC X(" + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + "). ")
      }
    }
  }
  If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
    For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
      DataLineOrNoStatement ("       01  REC3" + ($I) + ".")
      DEFINE_FILER ((GetSgsValue ("FIXE,1,$I,1")))
      DataLineOrNoStatement ("           06 FIXDATA" + ($I) + " PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ").  ")
    }
  }
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  NB-LUS   PIC  S9(10)  COMP  VALUE 0. ")
DataLineOrNoStatement ("       77  LNCTR  PIC  S9(2)  VALUE 58. ")
If ((GetSgsValue ("MAXCOPY"))) {
  DataLineOrNoStatement ("       01  COPY-LIMIT         PIC 9(10) VALUE " + ((GetSgsValue ("MAXCOPY,1,1,1"))) + ".  ")
}
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  DataLineOrNoStatement ("       01  TITLE-LINE         USAGE DISP-1. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(4) VALUE 'H,,,'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10)  VALUE '1234567890'.")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(5)  VALUE SPACES.   ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(12) VALUE '" + ((GetSgsValue ("INPUT,1,1,1"))) + "'.  ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(13) VALUE ' TO PRINTER '.   ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  DataLineOrNoStatement ("           03  FILLER         PIC X(10) VALUE '1234567890'. ")
  # '.  
  DataLineOrNoStatement ("           03  FILLER         PIC X(5)  VALUE '12")
}
If ((CompareTypeSafe (GetSgsValue ("SUPCOM")) "EqualTo" 0)) {
} else {
  DataLineOrNoStatement ("       01  RECW.")
  DataLineOrNoStatement ("           02 RECW1   PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + "). ")
  DataLineOrNoStatement ("           02 RECW2  REDEFINES RECW1.   ")
  DataLineOrNoStatement ("               03  RECW3  OCCURS " + ((GetSgsValue ("INPUT,1,1,2"))) + ". ")
  DataLineOrNoStatement ("                    04  RECW4  PICTURE X.   ")
}
If ((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
    DataLineOrNoStatement ("       01  TAB1" + ($I) + ".")
    If (((CompareTypeSafe -not (GetSgsValue ("FIXE,1,$I")) "GreaterThan" 0) -or (CompareTypeSafe (GetSgsValue ("FIXE,1,$I,3")) "EqualTo" "SPACES ;"))) {
      DataLineOrNoStatement ("               OR  " + ((GetSgsValue ("FIXE,1,$I,3"))) + "  =  SPACE   ")
      DataLineOrNoStatement ("           06  FIXED" + ($I) + "  PIC  X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ")  VALUE SPACES.   ")
    } else {
      DataLineOrNoStatement ("           06 FIXED" + ($I) + "  PIC X(" + ((GetSgsValue ("FIXE,1,$I,2"))) + ") VALUE " + ((GetSgsValue ("FIXE,1,$I,3"))) + ".")
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("FIXE,1,1,3")) "EqualTo" "NUM")) {
  DataLineOrNoStatement ("       01  COUNT.   ")
  DataLineOrNoStatement ("           03 COUNTING PIC S9(" + ((GetSgsValue ("FIXE,1,1,2"))) + ")  VALUE 0.   ")
  DataLineOrNoStatement ("           03 COUNTER PIC S9(" + ((GetSgsValue ("FIXE,1,1,2"))) + ") VALUE " + ((GetSgsValue ("FIXE,1,1,4"))) + ".  ")
}
DataLineOrNoStatement ("       01   SWITCHES.   ")
DataLineOrNoStatement ("           03  REC-SKIPPED  PIC  S9(6) VALUE ZEROES.")
If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  CDTOAF.  ")
  DataLineOrNoStatement ("           03  CDTOAF-PRM-ENE.  ")
  DataLineOrNoStatement ("               05  CDTOAF-DT-ENE.   ")
  DataLineOrNoStatement ("                   07  CDTOAF-AA-ENE.   ")
  DataLineOrNoStatement ("                       09  CDTOAF-A1-ENE       PIC X(01).   ")
  DataLineOrNoStatement ("                       09  CDTOAF-A2-ENE       PIC X(01).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-MM-ENE           PIC X(02).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-JJ-ENE           PIC X(02).   ")
  DataLineOrNoStatement ("           03  CDTOAF-PRM-SRT.  ")
  DataLineOrNoStatement ("               05  CDTOAF-DT-SRT-9             PIC 9(08).   ")
  DataLineOrNoStatement ("               05  CDTOAF-DT-SRT REDEFINES CDTOAF-DT-SRT-9. ")
  DataLineOrNoStatement ("                   07  CDTOAF-SSAA-SRT         PIC X(04).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-SSAA-SRT-RDF REDEFINES CDTOAF-SSAA-SRT.   ")
  DataLineOrNoStatement ("                      09  CDTOAF-SS-SRT        PIC X(02).   ")
  DataLineOrNoStatement ("                      09  CDTOAF-AA-SRT.")
  DataLineOrNoStatement ("                          11  CDTOAF-A1-SRT    PIC X(01).   ")
  DataLineOrNoStatement ("                          11  CDTOAF-A2-SRT    PIC X(01).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-MM-SRT           PIC X(02).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-JJ-SRT           PIC X(02).   ")
  DataLineOrNoStatement ("               05  CDTOAF-DTE-SRT REDEFINES CDTOAF-DT-SRT-9.")
  DataLineOrNoStatement ("                   07  CDTOAF-SSS-SRT          PIC X(02).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-DT6-SRT          PIC X(06).   ")
  DataLineOrNoStatement ("               05  CDTOAF-DTE2-SRT REDEFINES CDTOAF-DT-SRT-9.   ")
  DataLineOrNoStatement ("                   07  CDTOAF-SS2-SRT          PIC X(02).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-AAMM-SRT         PIC X(04).   ")
  DataLineOrNoStatement ("                   07  CDTOAF-JJ2-SRT          PIC X(02).   ")
}
If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  EUW002.  ")
  DataLineOrNoStatement ("           03  WS-PTR-ENE.  ")
  DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-ENE.  ")
  DataLineOrNoStatement ("                   07  MT-ENE              PIC S9(17).  ")
  DataLineOrNoStatement ("                   07  MT-ENE-SGN          PIC X(01).   ")
  DataLineOrNoStatement ("                   07  MT-ENE-CHI          PIC 9(02).   ")
  DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-SRT.  ")
  DataLineOrNoStatement ("                   07  LG-MAX-MON-SRT      PIC 9(03).   ")
  DataLineOrNoStatement ("                   07  CD-FMT-MON-SRT      PIC X(01).   ")
  DataLineOrNoStatement ("                   07  WS-PTR-FAC-MON-SRT.  ")
  DataLineOrNoStatement ("                       09  FL-IMP-APO      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-EUR      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-BEF      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-PLT-SGN      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-TRD-SGN      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-SGN-FIX      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-SGN-VUE      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-CAD-PRC      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-CAD-CNV      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-IMP-PNT      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FL-000          PIC X(01).   ")
  DataLineOrNoStatement ("                       09  CD-DET-MON      PIC X(01).   ")
  DataLineOrNoStatement ("                       09  FILLER          PIC X(19).   ")
  DataLineOrNoStatement ("           03  WS-PTR-SRT.  ")
  DataLineOrNoStatement ("               05  WS-MON-SRT-001.  ")
  DataLineOrNoStatement ("                   07  MT-SRT              PIC X(100).  ")
  DataLineOrNoStatement ("               05  WS-MON-SRT-002.  ")
  DataLineOrNoStatement ("                   07  MT-SRT-PRC          PIC X(50).   ")
  DataLineOrNoStatement ("                   07  MT-SRT-CNV          PIC X(50).   ")
  DataLineOrNoStatement ("                   07  TL-PTH-GCH          PIC X(01).   ")
  DataLineOrNoStatement ("                   07  TL-PTH-DRT          PIC X(01).   ")
  DataLineOrNoStatement ("               05  LG-MON-SRT              PIC 9(02).   ")
  DataLineOrNoStatement ("               05  LB-DVI-PRC              PIC X(03).   ")
  DataLineOrNoStatement ("               05  LB-DVI-CNV              PIC X(03).   ")
  DataLineOrNoStatement ("           03  WS-PTR-ENE-SRT.  ")
  DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
  DataLineOrNoStatement ("           03  WS-IFN-EUR.  ")
  DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
  DataLineOrNoStatement ("       01  WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           03  NM-PGM-APL               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-ENV               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-COP               PIC X(08).  ")
  DataLineOrNoStatement ("           03  NM-NOM-DEM               PIC X(08).  ")
  DataLineOrNoStatement ("           03  VL-CDE-RET               PIC S9(04). ")
  DataLineOrNoStatement ("           03  VL-MOT-CDE               PIC S9(04). ")
  DataLineOrNoStatement ("           03  LB-MSG-RET               PIC X(30).  ")
  DataLineOrNoStatement ("           03  CD-DBG-PRG               PIC X(1).   ")
  DataLineOrNoStatement ("           03  FILLER                   PIC X(7).   ")
  DataLineOrNoStatement ("           03  VL-CHP-TSF               PIC X(3922).")
  DataLineOrNoStatement ("       01  RDMS-QUALIFIER                        PIC X(12). ")
  DataLineOrNoStatement ("       01  RDMS-IND                              PIC 9(2).  ")
  DataLineOrNoStatement ("       01  RDMS-STATUS                           PIC 9999  VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-SAV-STATUS                       PIC 9999  VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-ROLLB                            PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-COLUMN                           PIC S1(36).")
  DataLineOrNoStatement ("       01  RDMS-SAV-COLUMN                       PIC S1(36).")
  DataLineOrNoStatement ("       01  RDMS-FLAG                             PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-FLAG-THREAD                      PIC 9     VALUE 0. ")
  DataLineOrNoStatement ("       01  RDMS-RESULT. ")
  DataLineOrNoStatement ("             05 RDMS-ERROR-LINE OCCURS 4         PIC X(80). ")
  DataLineOrNoStatement ("       01  RDMS-COM.")
  DataLineOrNoStatement ("             05 RLIN            OCCURS 36        PIC X(40). ")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   ")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           OPEN OUTPUT  PRINTOUT.   ")
  }
}
DataLineOrNoStatement ("           OPEN INPUT TAPEIN.   ")
DataLineOrNoStatement ("           OPEN  OUTPUT  TAPEOUT.   ")
If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           CALL 'RSA`$INIT'. ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'BEGIN THREAD FOR APPLICATION UDSSRC READ;',   ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 1 TO RDMS-FLAG-THREAD.  ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'USE DEFAULT QUALIFIER " + ($schname) + ";',   ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'USE DEFAULT VERSION PRODUCTION ;',")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           MOVE 'TAPELD'    TO NM-PGM-APL   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'BATCH'     TO NM-NOM-ENV   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO CD-DBG-PRG   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'EUW002'    TO NM-NOM-COP   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE 'SERVICE1'  TO NM-NOM-DEM   OF WS-CMT-PGM.  ")
  DataLineOrNoStatement ("           MOVE SPACES      TO WS-PTR-ENE   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE 'L'         TO FL-PLT-SGN   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO MT-ENE-SGN   OF EUW002.  ")
  DataLineOrNoStatement ("           MOVE '1'         TO CD-FMT-MON-SRT  OF EUW002.   ")
  DataLineOrNoStatement ("           MOVE 'Y'         TO FL-IMP-APO      OF EUW002.   ")
  DataLineOrNoStatement ("           MOVE 'N'         TO FL-000          OF EUW002.   ")
}
DataLineOrNoStatement ("       LECT.")
DataLineOrNoStatement ("           MOVE SPACES TO RECOUT.   ")
If (((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0) -and (CompareTypeSafe (GetSgsValue ("STITRE")) "GreaterThan" 0))) {
  DataLineOrNoStatement ("           IF  LNCTR  > 57  ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
    DataLineOrNoStatement ("           MOVE  FIXED" + ($I) + "   TO FIXDATA" + ($I) + " ")
  }
  DataLineOrNoStatement ("           WRITE  RECOUT  AFTER  PAGE   ")
  DataLineOrNoStatement ("           MOVE SPACES TO  RECOUT   ")
  DataLineOrNoStatement ("           MOVE 5 TO LNCTR. ")
}
DataLineOrNoStatement ("           READ  TAPEIN  AT  END  GO TO  FINW.  ")
If ((CompareTypeSafe (GetSgsValue ("SUPCOM")) "EqualTo" 0)) {
} else {
  DataLineOrNoStatement ("           MOVE  RECIN  TO RECW.")
  DataLineOrNoStatement ("           IF  RECW4 (7) = '*' GO TO LECT.  ")
}
If ((CompareTypeSafe (GetSgsValue ("REPSIM")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       REPSIM.  ")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
} else {
  DataLineOrNoStatement ("           MOVE RECIN TO RECOUT.")
}
If ((CompareTypeSafe (GetSgsValue ("FIELDIN")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIELDIN,1")); $I++) { 
    $SW = 0
    DataLineOrNoStatement ("           MOVE                ZONE" + ($I) + " TO ZONO" + ($I) + ".")
    If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
      For ([Int32]$A = 2; $A -le (GetSgsValue ("Y2K,1")); $A++) { 
        DEFINE_INTER1 ((GetSgsValue ("Y2K,1,$A,2")))
        If ((CompareTypeSafe $I "EqualTo" $I1)) {
          DataLineOrNoStatement ("           MOVE CORRESPONDING ZONE" + ($I) + " TO ZONO" + ($I) + ". ")
          DataLineOrNoStatement ("           MOVE SPACES               TO CDTOAF. ")
          DataLineOrNoStatement ("           MOVE ZTI-" + ($I) + " OF ZONE" + ($I) + " TO CDTOAF-AA-ENE.  ")
          DataLineOrNoStatement ("           MOVE 01                   TO CDTOAF-MM-ENE   ")
          DataLineOrNoStatement ("                                        CDTOAF-JJ-ENE.  ")
          DataLineOrNoStatement ("           CALL 'CDTOAF'    USING CDTOAF.   ")
          DataLineOrNoStatement ("           MOVE CDTOAF-SSAA-SRT  TO ZTI-" + ($I) + " OF ZONO" + ($I) + ".   ")
        }
      }
    }
    If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
      For ([Int32]$A = 2; $A -le (GetSgsValue ("EURO,1")); $A++) { 
        DEFINE_INTER1 ((GetSgsValue ("EURO,1,$A,1")))
        If ((CompareTypeSafe $I "EqualTo" $I1)) {
          DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("FIELDIN,1,$I,2"))) + " TO MT-ENE-CHI OF EUW002.")
          DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("FIELDOUT,1,$I,2"))) + " TO LG-MAX-MON-SRT OF EUW002.   ")
          DataLineOrNoStatement ("           ADD   2               TO LG-MAX-MON-SRT OF EUW002.   ")
          DataLineOrNoStatement ("           MOVE ZONE" + ($I) + "         TO MT-ENE         OF EUW002.   ")
          DataLineOrNoStatement ("           MOVE EUW002           TO VL-CHP-TSF OF WS-CMT-PGM.   ")
          DataLineOrNoStatement ("           CALL 'EUU003'    USING WS-CMT-PGM.   ")
          DataLineOrNoStatement ("           MOVE VL-CHP-TSF OF WS-CMT-PGM TO EUW002. ")
          DataLineOrNoStatement ("           MOVE MT-SRT OF EUW002         TO ZONO" + ($I) + ".   ")
        }
      }
    }
  }
}
If (((CompareTypeSafe (GetSgsValue ("FIXE")) "GreaterThan" 0) -and (CompareTypeSafe -not (GetSgsValue ("STITRE")) "GreaterThan" 0))) {
  If ((CompareTypeSafe (GetSgsValue ("FIXE,1,1,3")) "EqualTo" "NUM")) {
    DataLineOrNoStatement ("           ADD COUNTER TO COUNTING. ")
    DataLineOrNoStatement ("           MOVE COUNTING TO FIXED" + ((GetSgsValue ("*1"))) + ".  ")
  }
  For ([Int32]$I = 1; $I -le (GetSgsValue ("FIXE,1")); $I++) { 
    If ((CompareTypeSafe (GetSgsValue ("FIXE,1,$I,3")) "EqualTo" "ZONE")) {
      DataLineOrNoStatement ("           ENTER  SST60  SUBROUTINE REFERENCING '-' FIXDATA" + ($I) + ".")
    } else {
      DataLineOrNoStatement ("           MOVE                  FIXED" + ($I) + " TO FIXDATA" + ($I) + ".  ")
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           WRITE LISTE  FROM RECOUT.")
  }
}
DataLineOrNoStatement ("           ADD 1  TO NB-LUS.")
DataLineOrNoStatement ("           ADD 1  TO LNCTR. ")
If ((CompareTypeSafe (GetSgsValue ("STARTFIELD")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  ZONE2  <  " + ((GetSgsValue ("STARTFIELD,1,1,1"))) + " ")
  DataLineOrNoStatement ("           ADD 1  TO REC-SKIPPED")
  DataLineOrNoStatement ("           GO TO LECT.  ")
}
If ((CompareTypeSafe (GetSgsValue ("STARTREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  NB-LUS  <  " + ((GetSgsValue ("STARTREC,1,1,1"))) + "  ")
  DataLineOrNoStatement ("           ADD 1  TO REC-SKIPPED")
  DataLineOrNoStatement ("           GO TO LECT.  ")
}
DataLineOrNoStatement ("           WRITE RECOUT.")
If ((GetSgsValue ("MAXCOPY"))) {
  DataLineOrNoStatement ("           IF  NB-LUS  NOT <  COPY-LIMIT  GO TO FINW.   ")
}
If ((CompareTypeSafe (GetSgsValue ("REPSIM")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  NB-LUS  =  " + ((GetSgsValue ("REPSIM,1,1,1"))))
  DataLineOrNoStatement ("           ADD 1  TO LNCTR. ")
  DataLineOrNoStatement ("           GO TO FINW   ")
  DataLineOrNoStatement ("           ELSE  GO TO REPSIM.  ")
}
DataLineOrNoStatement ("           GO TO LECT.  ")
DataLineOrNoStatement ("       FINW.")
DataLineOrNoStatement ("           DISPLAY  '*CFH-COPY  FIN*'  UPON  PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY  '*NB-ENREG-LUS ='  NB-LUS  UPON  PRINTER.   ")
DataLineOrNoStatement ("           CLOSE  TAPEIN.   ")
DataLineOrNoStatement ("           CLOSE  TAPEOUT.  ")
DataLineOrNoStatement ("           DISPLAY  REC-SKIPPED  UPON  PRINTER. ")
If ((CompareTypeSafe (GetSgsValue ("PRINT")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("           CLOSE PRINTOUT.  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'END THREAD ;',")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
  DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
  DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG-THREAD.  ")
}
DataLineOrNoStatement ("           STOP RUN.")
If ((CompareTypeSafe (GetSgsValue ("EURO")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       RDMS-ERROR-PAR.  ")
  DataLineOrNoStatement ("           DISPLAY '*** ERROR RDMS ***' UPON PRINTER.   ")
  DataLineOrNoStatement ("           DISPLAY 'COLUMN = ' RDMS-COLUMN UPON PRINTER.")
  DataLineOrNoStatement ("           DISPLAY 'STATUS = ' RDMS-STATUS UPON PRINTER.")
  DataLineOrNoStatement ("           PERFORM TRAIT-RDMS.  ")
  DataLineOrNoStatement ("           GO TO RDMS-ERROR-EX. ")
  DataLineOrNoStatement ("       TRAIT-RDMS.  ")
  DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           PERFORM VISU-RDMS-COM VARYING RDMS-IND FROM 1 BY 1   ")
  DataLineOrNoStatement ("               UNTIL RDMS-IND > 36. ")
  DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
  DataLineOrNoStatement ("           PERFORM TRAIT-RDMS-ERROR ")
  DataLineOrNoStatement ("               UNTIL RDMS-FLAG NOT = ZEROS. ")
  DataLineOrNoStatement ("       TRAIT-RDMS-ERROR.")
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("             'GETERROR INTO `$P1, `$P2, `$P3, `$P4 ;',  ")
  DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN,  ")
  DataLineOrNoStatement ("             RDMS-ERROR-LINE (1), RDMS-ERROR-LINE (2),  ")
  DataLineOrNoStatement ("             RDMS-ERROR-LINE (3), RDMS-ERROR-LINE (4).  ")
  DataLineOrNoStatement ("           PERFORM VISU-RDMS-ERROR  ")
  DataLineOrNoStatement ("             VARYING RDMS-IND FROM 1 BY 1   ")
  DataLineOrNoStatement ("             UNTIL RDMS-IND > 4.")
  DataLineOrNoStatement ("       VISU-RDMS-ERROR. ")
  DataLineOrNoStatement ("           IF RDMS-ERROR-LINE (RDMS-IND) NOT = SPACE")
  DataLineOrNoStatement ("                DISPLAY RDMS-ERROR-LINE (RDMS-IND) UPON PRINTER ")
  DataLineOrNoStatement ("           ELSE MOVE 1 TO RDMS-FLAG.")
  DataLineOrNoStatement ("       VISU-RDMS-COM.   ")
  DataLineOrNoStatement ("           IF RLIN (RDMS-IND) NOT = SPACES  ")
  DataLineOrNoStatement ("                DISPLAY RLIN (RDMS-IND) UPON PRINTER.   ")
  DataLineOrNoStatement ("       RDMS-ERROR-EX.   ")
}
# @MAP TPF$.CFH-COPY  
Call-ExternalProgram "MAP" "" ("TPF`$\CFH-COPY")
# Orphaned data line: IBANK,XU C$DML
# Orphaned data line: IBANK,M  I$1,022000
# Orphaned data line: IN       TPF$.
# Orphaned data line: IN SYS$LIB$*ACOB-DML.CBEP$$ACOB/FULL-LIB-CB
# Orphaned data line: IN SYS$LIB$*RSA.RDMR-ACOBDAT
# Orphaned data line: IN SYS$LIB$*RSA.CBEP$$RSA
# Orphaned data line: DBANK,MUC    D$1
# Orphaned data line: FORM         I$1
# Orphaned data line: LIB          PRD*REL.
# Orphaned data line: LIB          SYS*REL.
Fin
