# Converted from SSG source: UNLOADIS_MULTI
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("           02  FILLER  PIC  X(" + ($FILLCTR) + ").  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB I     .UNLOADIS,.UNLOADIS 
  Call-ExternalProgram "ACOB" "I" ("\UNLOADIS")
  Fin
} else {
  # @ACOB IT    .UNLOADIS,.UNLOADIS 
  Call-ExternalProgram "ACOB" "I, T" ("\UNLOADIS")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. UNLOADIS.")
# 
DataLineOrNoStatement ("       AUTHOR.     H A N S E")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNISYS-1100.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNISYS-1100.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT BDE  ASSIGN TO")
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("               INTERCHANGE " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".  ")
} else {
  DataLineOrNoStatement ("               DISC " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ". ")
}
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           SELECT DISQ ASSIGN TO A-SHARED-FILE " + ((GetSgsValue ("INPUT,1,1,1"))))
} else {
  DataLineOrNoStatement ("           SELECT DISQ ASSIGN TO DISC  " + ((GetSgsValue ("INPUT,1,1,1"))))
}
DataLineOrNoStatement ("           RESERVE 20 AREAS ")
DataLineOrNoStatement ("           ORGANIZATION IS INDEXED  ")
DataLineOrNoStatement ("           ACCESS  MODE IS SEQUENTIAL   ")
DataLineOrNoStatement ("           RECORD KEY IS CLEF   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEG ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEH ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEI ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  BDE  ")
If ((CompareTypeSafe (GetSgsValue ("OMITTED")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
} else {
  DataLineOrNoStatement ("           LABEL RECORD STANDARD")
}
DataLineOrNoStatement ("             BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + "   RECORDS")
DataLineOrNoStatement ("           RECORD CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " CHARACTERS")
DataLineOrNoStatement ("           DATA RECORD IS  ZBDE.")
DataLineOrNoStatement ("       01  ZBDE    PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
DataLineOrNoStatement ("       FD  DISQ ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
} else {
  DataLineOrNoStatement ("           LABEL RECORD STANDARD")
}
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + " RECORDS ")
DataLineOrNoStatement ("           RECORD  CONTAINS " + ((GetSgsValue ("INPUT,1,1,2"))) + " CHARACTERS")
DataLineOrNoStatement ("           DATA RECORD IS ZDISQ CLEFA CLEFB CLEFC CLEFD.")
DataLineOrNoStatement ("       01  ZDISQ   PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
DataLineOrNoStatement ("       01  CLEFA.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").  ")
}
DataLineOrNoStatement ("           02 CLEF   PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").  ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,3")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
DataLineOrNoStatement ("       01  CLEFB.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,2,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEG   PIC X(" + ((GetSgsValue ("KEYIS,2,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,2,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").  ")
}
DataLineOrNoStatement ("       01  CLEFC.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,3,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEH   PIC X(" + ((GetSgsValue ("KEYIS,3,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,3,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").  ")
}
DataLineOrNoStatement ("       01  CLEFD.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,4,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEI   PIC X(" + ((GetSgsValue ("KEYIS,4,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,4,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").  ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  CTR                PIC 9(10) COMP VALUE 0.   ")
If ((CompareTypeSafe (GetSgsValue ("MAXREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       77  MAXBDE             PIC 9(10) COMP VALUE " + ((GetSgsValue ("MAXREC,1,1,1"))) + ".  ")
} else {
  DataLineOrNoStatement ("       77  MAXBDE             PIC 9(10) COMP VALUE 99999999.")
}
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  RDMS-STATUS        PIC 9(4). ")
  DataLineOrNoStatement ("       01  INFO-COLUMN        PIC S1(36).   ")
}
DataLineOrNoStatement ("       01  WREC.")
DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("INPUT,1,1,2"))) + "). ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("                 'BEGIN THREAD FOR UDSSRC READ UDSMSG; '")
  DataLineOrNoStatement ("                 RDMS-STATUS, INFO-COLUMN.  ")
}
DataLineOrNoStatement ("           OPEN  OUTPUT BDE.")
DataLineOrNoStatement ("           OPEN  INPUT  DISQ.   ")
DataLineOrNoStatement ("           MOVE LOW-VALUES TO CLEF. ")
DataLineOrNoStatement ("       LECT.")
DataLineOrNoStatement ("           READ  DISQ  INTO  WREC  AT END GO TO FINB.   ")
DataLineOrNoStatement ("           ADD  1  TO  CTR. ")
DataLineOrNoStatement ("           WRITE ZBDE FROM WREC.")
DataLineOrNoStatement ("           MOVE SPACES TO WREC. ")
DataLineOrNoStatement ("           IF CTR = MAXBDE   GO TO FINB.")
DataLineOrNoStatement ("           GO TO LECT.  ")
DataLineOrNoStatement ("       FINB.")
DataLineOrNoStatement ("           DISPLAY 'NB.RECORDS ECRITS : '  CTR  UPON PRINTER.   ")
DataLineOrNoStatement ("           CLOSE  DISQ. ")
DataLineOrNoStatement ("           CLOSE  BDE.  ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("                 'END THREAD ; '")
  DataLineOrNoStatement ("                 RDMS-STATUS, INFO-COLUMN.  ")
}
DataLineOrNoStatement ("           STOP RUN.")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  # @MAP N     ,TPF$.UNLOADIS   
  Call-ExternalProgram "MAP" "N" (",TPF`$\UNLOADIS")
  # Orphaned data line: IBANK,UX  C$DML
  # Orphaned data line: IBANK,MRC I1,025000
  # Orphaned data line: IN  TPF$.
  # Orphaned data line: IN  SYS$LIB$*RSA.RDMR-ACOBDAT
  # Orphaned data line: IN  SYS$LIB$*ACOB-DML.CBEP$$ACOB/FULL-LIB-CB
  # Orphaned data line: IN  SYS$LIB$*SFSLIB.CBEP$$SFS
  # Orphaned data line: DBANK,MU  D1,0164000
  # Orphaned data line: IN  TPF$.
  # Orphaned data line: IN  SYS$LIB$*RSA.RDMR-ACOBDAT
  # Orphaned data line: IN  SYS$LIB$*RSA.CBEP$$RSA
  # Orphaned data line: IN  SYS$LIB$*SFSLIB.CBEP$$SFS
  # Orphaned data line: LIB SYS$LIB$*ACOB.
  # Orphaned data line: LIB SYS$LIB$*SORT.
  # Orphaned data line: END
  Fin
} else {
  # @MAP N    ASSURFED*UTILITASCII.MAP,TPF$.UNLOADIS
  Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
  Fin
}
Hdg "N"
Fin
