# Converted from SSG source: ARCHISEPARE
# Generated by SsgConverter
param([string[]]$Parameters)

$A = ((GetSgsValue ("rsz,1,1,1")) - (GetSgsValue ("key,1,2,2")))
$B = ($a - (GetSgsValue ("key,1,2,1")))
$C = (32 + (GetSgsValue ("rsz,1,1,1")))
$D = (GetSgsValue ("rsz,1,1,1"))
# @ucob is .archisepare,.archisepare  
Call-ExternalProgram "ucob" "I, S" ("\archisepare")
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: ***                  -- ARCHISEPARE --                         ***
# Orphaned data line: ***            Separe les enregistrements a archiver           ***
# Orphaned data line: ***                   et a ne pas archiver                     ***
# Orphaned data line: ***                        == UCS ==                           ***
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: * Type     :                                                     *
# Orphaned data line: * Analyste :                                 (INITIALES)         *
# Orphaned data line: * Auteur   : NEGA  NEGA SERGE                (INITIALES  NM PN)  *
# Orphaned data line: * Ecrit le : 17 avril 2001                   (dd/mm/ccyy)        *
# Orphaned data line: * Release  :                                 (99)                *
# Orphaned data line: * Version  :                                 (999)               *
# Orphaned data line: *----------------------------------------------------------------*
# Orphaned data line: * Modifications :                                                *
# Orphaned data line: * Qui ?  Quand ?     Quoi ?                             Projet/Ph*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: * _____  __/__/____  _________________________________  ______/__*
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: *                       DESCRIPTION                              *
# Orphaned data line: *                       ===========                              *
# Orphaned data line: *                                                                *
# Orphaned data line: *    INPUT : chercheuse : numero de sinistres a archiver         *
# Orphaned data line: *    INPUT : ficunload : unload de la table a archiver           *
# Orphaned data line: *    OUTPUT: ficarchi : enregistrements a archiver               *
# Orphaned data line: *    OUTPUT: ficnarchi : enregistrements a ne pas archiver       *
# Orphaned data line: ***------------------------------------------------------------***
# Orphaned data line: Identification division.
# Orphaned data line: *========================*
# Orphaned data line: program-id.  ARCHISEPARE.
# Orphaned data line: Environment division.
# Orphaned data line: *====================*
# Orphaned data line: Configuration section.
# Orphaned data line: *----------------------*
# Orphaned data line: source-computer.  unisys-2200.
# Orphaned data line: object-computer.  unisys-2200 MEMORY 3 MODULES.
# Orphaned data line: special-names.
# Orphaned data line: printer       printer
# Orphaned data line: decimal-point comma.
# Orphaned data line: Input-output section.
# Orphaned data line: *---------------------*
# Orphaned data line: file-control.
# Orphaned data line: select chercheuse assign to disc     [filein,1,1,1].
# Orphaned data line: select ficunload assign to disc      [filein,1,2,1].
# Orphaned data line: select ficarchi assign to disc       [fileout,1,1,1].
# Orphaned data line: select ficnarchi assign to disc      [fileout,1,2,1].
# Orphaned data line: i-o-control.
# Orphaned data line: Data division.
# Orphaned data line: *==============*
# Orphaned data line: File section.
# Orphaned data line: *-------------*
# Orphaned data line: * Fichier chercheuse
# Orphaned data line: FD  chercheuse.
# Orphaned data line: 1  cle-chercheuse        pic 9([key,1,1,2]).
# Orphaned data line: *Unload de la table a archiver
# Orphaned data line: FD  ficunload.
Fin
If ((CompareTypeSafe (GetSgsValue ("key,1,2,1")) "EqualTo" 0)) {
  DataLineOrNoStatement ("        1  ligne-unload.")
  DataLineOrNoStatement ("           3 cle-unload          pic 9(" + ((GetSgsValue ("key,1,2,2"))) + ").")
  DataLineOrNoStatement ("           3 filler              pic x(" + ($a) + ").   ")
} elseif ((CompareTypeSafe (GetSgsValue ("key,1,2,1")) "EqualTo" $a)) {
  DataLineOrNoStatement ("        1  ligne-unload.")
  DataLineOrNoStatement ("           3 filler              pic x(" + ($a) + ").   ")
  DataLineOrNoStatement ("           3 cle-unload          pic 9(" + ((GetSgsValue ("key,1,2,2"))) + ").")
} else {
  DataLineOrNoStatement ("        1  ligne-unload.")
  DataLineOrNoStatement ("           3 filler              pic x(" + ((GetSgsValue ("key,1,2,1"))) + ").")
  DataLineOrNoStatement ("           3 cle-unload          pic 9(" + ((GetSgsValue ("key,1,2,2"))) + ").")
  DataLineOrNoStatement ("           3 filler              pic x(" + ($b) + ").   ")
}
DataLineOrNoStatement ("      * Fichier enregistrements a archiver  ")
DataLineOrNoStatement ("       FD  ficarchi.")
DataLineOrNoStatement ("        1  ligne-archi           pic x(" + ($c) + ").   ")
DataLineOrNoStatement ("      * Fichier enregistrement a ne pas archiver")
DataLineOrNoStatement ("       FD  ficnarchi.   ")
DataLineOrNoStatement ("        1  ligne-narchi          pic x(" + ($d) + ").   ")
DataLineOrNoStatement ("       Working-storage section. ")
DataLineOrNoStatement ("      *------------------------*")
DataLineOrNoStatement ("         1 ligne-type4. ")
DataLineOrNoStatement ("           3 cd-don                    pic x value `"4`". ")
DataLineOrNoStatement ("           3 cd-ach                    pic x.   ")
DataLineOrNoStatement ("           3 tl-cle                    pic 9(" + ((GetSgsValue ("key,1,2,2"))) + ").  ")
DataLineOrNoStatement ("           3 tl-don                    pic x(" + ((GetSgsValue ("rsz,1,1,1"))) + ").  ")
DataLineOrNoStatement ("         1 ligne-type9. ")
DataLineOrNoStatement ("           3 cd-don9                   pic x value `"9`". ")
DataLineOrNoStatement ("           3 nm-bas9                   pic x(6).")
DataLineOrNoStatement ("           3 nm-tab9                   pic x(30).   ")
DataLineOrNoStatement ("           3 dt-ach9                   pic x(8).")
DataLineOrNoStatement ("           3 cptach1                   pic s9(11) sign leading separate.")
DataLineOrNoStatement ("           3 cptach2                   pic s9(11) sign leading separate.")
DataLineOrNoStatement ("         1 lecrchf                     pic 9 value 0.   ")
DataLineOrNoStatement ("           88 fin-lecrch               value 1. ")
DataLineOrNoStatement ("         1 lecunloadf                  pic 9 value 0.   ")
DataLineOrNoStatement ("           88 fin-lecunload            value 1. ")
DataLineOrNoStatement ("      *---------------- Pour le rapport ---------------------   ")
DataLineOrNoStatement ("        77 cptlu                       pic 9(7).")
DataLineOrNoStatement ("        77 cptarchi                    pic 9(7).")
DataLineOrNoStatement ("        77 cptnarchi                   pic 9(7).")
DataLineOrNoStatement ("        77 cptluf                      pic z(6)9.   ")
DataLineOrNoStatement ("        77 cptarchif                   pic z(6)9.   ")
DataLineOrNoStatement ("        77 cptnarchif                  pic z(6)9.   ")
DataLineOrNoStatement ("      *------------------------------------------------------   ")
DataLineOrNoStatement ("      *------------------ POUR LA DATE ---------------------")
DataLineOrNoStatement ("         1 date-i.  ")
DataLineOrNoStatement ("           3 annee-i                   pic 9(4).")
DataLineOrNoStatement ("           3 mois-i                    pic 99.  ")
DataLineOrNoStatement ("           3 jour-i                    pic 99.  ")
DataLineOrNoStatement ("         1 date-fr. ")
DataLineOrNoStatement ("           3 jour-fr                   pic 99.  ")
DataLineOrNoStatement ("           3     pic x value '/'.   ")
DataLineOrNoStatement ("           3 mois-fr                   pic 99.  ")
DataLineOrNoStatement ("           3     pic x value '/'.   ")
DataLineOrNoStatement ("           3 annee-fr                  pic 9(4).")
DataLineOrNoStatement ("      *------------------------------------------------------   ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("      *-------------------  ")
DataLineOrNoStatement ("         000-main.  ")
DataLineOrNoStatement ("           open input chercheuse ficunload  ")
DataLineOrNoStatement ("                output ficarchi ficnarchi   ")
DataLineOrNoStatement ("           perform 100-lec-chercheuse thru 100-exit ")
DataLineOrNoStatement ("           perform 101-lec-unload thru 101-exit ")
DataLineOrNoStatement ("           perform 102-separe thru 102-exit ")
DataLineOrNoStatement ("           perform 103-date thru 103-exit   ")
DataLineOrNoStatement ("           perform 104-rapport thru 104-exit")
DataLineOrNoStatement ("           close chercheuse ficunload   ")
DataLineOrNoStatement ("                 ficarchi ficnarchi ")
DataLineOrNoStatement ("           stop run ")
DataLineOrNoStatement ("      *---------- LECTURE DU NUMERO DE CHERCHEUSE -------------------   ")
DataLineOrNoStatement ("        100-lec-chercheuse. ")
DataLineOrNoStatement ("           read chercheuse  ")
DataLineOrNoStatement ("             at end ")
DataLineOrNoStatement ("               move 1 to lecrchf")
DataLineOrNoStatement ("           end-read ")
DataLineOrNoStatement ("        100-exit.   ")
DataLineOrNoStatement ("           exit.")
DataLineOrNoStatement ("      *------------ LECTURE D'UN ENREGISTREMENT UNLOAD -------- ")
DataLineOrNoStatement ("        101-lec-unload. ")
DataLineOrNoStatement ("           read ficunload   ")
DataLineOrNoStatement ("             at end ")
DataLineOrNoStatement ("               move 1 to lecunloadf ")
DataLineOrNoStatement ("             not at end ")
DataLineOrNoStatement ("               add 1 to cptlu   ")
DataLineOrNoStatement ("           end-read ")
DataLineOrNoStatement ("        101-exit.   ")
DataLineOrNoStatement ("           exit.")
DataLineOrNoStatement ("      *----- SEPARATION ENREGISTREMENT ARCHI ET NARCHI ---------")
DataLineOrNoStatement ("        102-separe. ")
DataLineOrNoStatement ("           perform until fin-lecunload  ")
DataLineOrNoStatement ("             if lecrchf not = 1 ")
DataLineOrNoStatement ("               evaluate true")
DataLineOrNoStatement ("      *L'enregistrement est a archiver  ")
DataLineOrNoStatement ("                 when cle-chercheuse = cle-unload   ")
DataLineOrNoStatement ("                   move `"A`" to cd-ach   ")
DataLineOrNoStatement ("                   move cle-unload to tl-cle")
DataLineOrNoStatement ("                   move ligne-unload to tl-don  ")
DataLineOrNoStatement ("                   write ligne-archi from ligne-type4   ")
DataLineOrNoStatement ("                   add 1 to cptarchi")
DataLineOrNoStatement ("                   perform 101-lec-unload thru 101-exit ")
DataLineOrNoStatement ("                   if cle-unload not = cle-chercheuse   ")
DataLineOrNoStatement ("                     perform 100-lec-chercheuse thru 100-exit   ")
DataLineOrNoStatement ("                   end-if   ")
DataLineOrNoStatement ("      *L'enregistrement ne doit pas etre archive")
DataLineOrNoStatement ("                 when cle-chercheuse > cle-unload   ")
DataLineOrNoStatement ("                   write ligne-narchi from ligne-unload ")
DataLineOrNoStatement ("                   add 1 to cptnarchi   ")
DataLineOrNoStatement ("                   perform 101-lec-unload thru 101-exit ")
DataLineOrNoStatement ("      *Decalage de cle  ")
DataLineOrNoStatement ("                 when cle-chercheuse < cle-unload   ")
DataLineOrNoStatement ("                   perform 100-lec-chercheuse   ")
DataLineOrNoStatement ("               end-evaluate ")
DataLineOrNoStatement ("             else   ")
DataLineOrNoStatement ("      *Si la chercheuse est vide, il faut ecrire les enregistrements")
DataLineOrNoStatement ("      *  qui restent dans le fichier d'unload   ")
DataLineOrNoStatement ("               write ligne-narchi from ligne-unload ")
DataLineOrNoStatement ("               add 1 to cptnarchi   ")
DataLineOrNoStatement ("               perform 101-lec-unload thru 101-exit ")
DataLineOrNoStatement ("             end-if ")
DataLineOrNoStatement ("           end-perform  ")
DataLineOrNoStatement ("      *Pour l'enregistrement de type9   ")
DataLineOrNoStatement ("           move `"" + ((GetSgsValue ("tname,1,1,1"))) + "`" to nm-bas9  ")
DataLineOrNoStatement ("           move `"" + ((GetSgsValue ("tname,1,1,2"))) + "`" to nm-tab9  ")
DataLineOrNoStatement ("           accept date-i from date yyyymmdd ")
DataLineOrNoStatement ("           move date-i to dt-ach9   ")
DataLineOrNoStatement ("           move cptarchi to cptach1 ")
DataLineOrNoStatement ("                            cptach2 ")
DataLineOrNoStatement ("           write ligne-archi from ligne-type9   ")
DataLineOrNoStatement ("        102-exit.   ")
DataLineOrNoStatement ("           exit.")
DataLineOrNoStatement ("      *---------------- DATE AU FORMAT FRANCAIS -------------   ")
DataLineOrNoStatement ("        103-date.   ")
DataLineOrNoStatement ("           move annee-i to annee-fr ")
DataLineOrNoStatement ("           move mois-i to mois-fr   ")
DataLineOrNoStatement ("           move jour-i to jour-fr   ")
DataLineOrNoStatement ("        103-exit.   ")
DataLineOrNoStatement ("           exit.")
DataLineOrNoStatement ("      *----------- DISPLAY DU RAPPORT ------------- ")
DataLineOrNoStatement ("        104-rapport.")
DataLineOrNoStatement ("           move cptlu to cptluf ")
DataLineOrNoStatement ("           move cptarchi to cptarchif   ")
DataLineOrNoStatement ("           move cptnarchi to cptnarchif ")
DataLineOrNoStatement ("           display `"Archisepare              Rapport             `"  ")
DataLineOrNoStatement ("             date-fr upon printer   ")
DataLineOrNoStatement ("           display `" `" upon printer ")
DataLineOrNoStatement ("           display `"Enregistrement lu : `" cptluf upon printer   ")
DataLineOrNoStatement ("           display `"Enregistrement ecrit dans " + ((GetSgsValue ("fileout,1,1,1"))) + " : `"   ")
DataLineOrNoStatement ("             cptarchif upon printer ")
DataLineOrNoStatement ("           display `"Enregistrement ecrit dans " + ((GetSgsValue ("fileout,1,2,1"))) + " : `"   ")
DataLineOrNoStatement ("             cptnarchif upon printer")
DataLineOrNoStatement ("        104-exit.   ")
DataLineOrNoStatement ("           exit.")
