**********************************************************
*                                                        *
* Configuration with application manager and more than   *
* one application servers                                *
*                                                        *
**********************************************************
USEAPPMANAGER=TRUE
USESPAREMANAGER=FALSE
APPMANAGER=TCP <Manager servername> <Listen Port>
SPAREMANAGER=TCP
APPSERVER=TCP


**********************************************************
*                                                        *
* Configuration with a single application server         *
* mostly development configuration                       *
*                                                        *
**********************************************************
# USEAPPMANAGER=FALSE
# USESPAREMANAGER=FALSE
# APPMANAGER=TCP 
# SPAREMANAGER=TCP
# APPSERVER=TCP <Application servername> <Listen Port>
