# Converted from SSG source: TABAN_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("               06 FILLER  PIC  X(" + ($FILLCTR) + ").   ")
  }
}
Function Define_fil1 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL1") {
    Return
  }

  $FILLCTR = (($Parameters[0] + 1) - ($Parameters[1] - $Parameters[2]))
  If ($FILLCTR) {
    DataLineOrNoStatement ("               06 FIS" + ($I) + " PIC  X(" + ($FILLCTR) + ").   ")
  }
}
Function Define_fil2 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL2") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("               06 FIA" + ($I) + " PIC  X(" + ($FILLCTR) + ").   ")
  }
}
Function Define_fil3 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FIL3") {
    Return
  }

  $FILLCTR = ($Parameters[0] + 2)
}
Function Define_sejp3 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SEJP3") {
    Return
  }

  $J = ($Parameters[0] + 3)
}
Function Define_sw {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SW") {
    Return
  }

  $SW = $Parameters[0]
}
Function Define_inter1 {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_INTER1") {
    Return
  }

  $I1 = $Parameters[0]
}
Function Define_addeuro {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_ADDEURO") {
    Return
  }

  $EURO = ($EURO + 1)
}
Function Define_ligne {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_LIGNE") {
    Return
  }

  $LIG = ($LIG + 4)
}
$Rgv_CASE = 1
AddTo-SgsList "SCHEMA DEV DBREP"
AddTo-SgsList "SCHEMA TST AFLINC"
AddTo-SgsList "SCHEMA ACP ACCEP"
$SCHNAME = "AFLINC"
For ([Int32]$ASCH = 1; $ASCH -le (GetSgsValue ("SCHEMA")); $ASCH++) { 
  Log-Message ((GetSgsValue ("info$,1,3,1")) + " = " + (GetSgsValue ("schema,$asch,1,1"))) '([LogMessageType]::Information)'
  If ((CompareTypeSafe (GetSgsValue ("info$,1,3,1")) "EqualTo" (GetSgsValue ("schema,$ASCH,1,1")))) {
    $SCHNAME = (GetSgsValue ("schema,$asch,2,1"))
    Exit
  }
}
Log-Message ("schema = " + $schname) '([LogMessageType]::Information)'
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
  # @ACOB I            .TABAN,.TABAN
  Call-ExternalProgram "ACOB" "I" ("\TABAN")
  Fin
} else {
  # @ACOB I      .TABAN,.TABAN  
  Call-ExternalProgram "ACOB" "I" ("\TABAN")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. 'TABAN'. ")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY PIERRE.")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER.     UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       OBJECT-COMPUTER.     UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       SPECIAL-NAMES.   ")
DataLineOrNoStatement ("           DECIMAL-POINT IS COMMA.  ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT   IMP   ASSIGN  TO  PRINTER.  ")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           SELECT  TAPE1  ASSIGN TO CARD-READER.")
} else {
  DataLineOrNoStatement ("           SELECT  TAPE1  ASSIGN  TO")
}
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("               UNISERVO " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
} else {
  DataLineOrNoStatement ("               DISC " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  IMP   LABEL RECORD  OMITTED  ")
DataLineOrNoStatement ("                    LINAGE IS 63")
DataLineOrNoStatement ("                    LINES AT TOP 6  ")
DataLineOrNoStatement ("                    LINES AT BOTTOM 3   ")
DataLineOrNoStatement ("                 DATA  RECORD  IS  LIGNE.   ")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
  DataLineOrNoStatement ("       01  LIGNE   PIC  X(132). ")
} else {
  DataLineOrNoStatement ("       01  LIGNE   PIC  X(132) DISP-1.  ")
}
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("       FD  TAPE1  LABEL RECORD OMITTED  ")
} else {
  DataLineOrNoStatement ("       FD  TAPE1  LABEL RECORD  STANDARD")
}
DataLineOrNoStatement ("                  BLOCK  CONTAINS  " + ((GetSgsValue ("INPUT,1,1,3"))) + "  RECORDS   ")
DataLineOrNoStatement ("             DATA RECORD IS RECE1  REC1.")
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
  DataLineOrNoStatement ("       01  RECE1  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ")  DISP-1.")
} else {
  DataLineOrNoStatement ("       01  RECE1  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
    DataLineOrNoStatement ("       01  REC" + ($I) + " DISP-1.  ")
  } else {
    DataLineOrNoStatement ("       01  REC" + ($I) + ". ")
  }
  DEFINE_FILER ((GetSgsValue ("KEYS,1,$I,1")))
  DataLineOrNoStatement ("              06 LMONT" + ($I) + "  PIC  S9(" + ((GetSgsValue ("KEYS,1,$I,2"))) + ").  ")
  DataLineOrNoStatement ("              06 RMONT" + ($I) + " REDEFINES LMONT" + ($I) + ". ")
  DataLineOrNoStatement ("                   07 TMONT" + ($I) + " PIC 9 OCCURS " + ((GetSgsValue ("KEYS,1,$I,2"))) + " TIMES INDEXED ")
  DataLineOrNoStatement ("                       BY KMONT" + ($I) + ".")
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
      DataLineOrNoStatement ("       01  INDICATIF" + ($I) + " DISP-1.")
    } else {
      DataLineOrNoStatement ("       01  INDICATIF" + ($I) + ".   ")
    }
    DEFINE_FILER ((GetSgsValue ("INDIC,1,$I,1")))
    DataLineOrNoStatement ("               06 LIND" + ($I) + "  PIC  X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "EqualTo" 0)) {
  DataLineOrNoStatement ("       01  CCART  PIC 9  DISP-1.")
} else {
  DataLineOrNoStatement ("       01  CCART  PIC 9.")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  NB-LUS   PIC   9(10) COMP VALUE  0.  ")
DataLineOrNoStatement ("       77  FIRS     PIC   9(10) COMP VALUE  0.  ")
DataLineOrNoStatement ("       01  ZONE-WORK.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           02 LMONT" + ($I) + " PIC SH9(18).")
  DataLineOrNoStatement ("           02 FILLER PIC X. ")
}
DataLineOrNoStatement ("       01  SUB-TOTAL.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           03  MONT" + ($I) + "    PIC  SH9(18)  VALUE 0.   ")
  DataLineOrNoStatement ("           03 FILLER PIC X. ")
}
DataLineOrNoStatement ("       01  TOTAL.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           03  MONT" + ($I) + "   PIC  SH9(18)  VALUE  0.   ")
  DataLineOrNoStatement ("           03 FILLER PIC X. ")
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  W-INDIC. ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           02  IND" + ($I) + "    PIC  X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").")
  }
  DataLineOrNoStatement ("       01  W-INDIC-OLD. ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    $SW = 0
    If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
      For ([Int32]$A = 2; $A -le (GetSgsValue ("Y2K,1")); $A++) { 
        DEFINE_INTER1 ((GetSgsValue ("Y2K,1,$A,2")))
        If ((CompareTypeSafe $I "EqualTo" $I1)) {
          DataLineOrNoStatement ("           02  IND" + ($I) + ". ")
          DEFINE_FIL2 ((GetSgsValue ("Y2K,1,$A,1")))
          DataLineOrNoStatement ("               06 ZTI-" + ($I) + "             PIC X(" + ((GetSgsValue ("Y2K,1,$A,3"))) + ").  ")
          DEFINE_FIL1 ((GetSgsValue ("INDIC,1,$I1,2"))) ((GetSgsValue ("Y2K,1,$A,3"))) ((GetSgsValue ("Y2K,1,$A,1")))
          DEFINE_SW ((GetSgsValue ("Y2K,1,$A,1")))
        }
      }
      If ($SW) {
      } else {
        DataLineOrNoStatement ("           02  IND" + ($I) + "  PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
      }
    } else {
      DataLineOrNoStatement ("           02  IND" + ($I) + "  PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
    }
  }
}
DataLineOrNoStatement ("       01  W-ZERO.  ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           03  MONT" + ($I) + "  PIC  SH9(18)  VALUE 0. ")
  DataLineOrNoStatement ("           03 FILLER PIC X. ")
}
DataLineOrNoStatement ("       01  TIT-TOTAL.   ")
DataLineOrNoStatement ("           02  FILLER  PIC  X(16)  VALUE  '***TABAN FIN ***'.   ")
DataLineOrNoStatement ("           02  FILLER  PIC  X(15)  VALUE  ' NB.ENREG.LUS= '.")
DataLineOrNoStatement ("           02  P-LUS   PIC  Z(8)9.  ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  TIT-RUPT1.   ")
  DataLineOrNoStatement ("           02  FILLI   PIC  X(14) VALUE '***RUPTURE*** '.   ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    $SW = 0
    If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
      For ([Int32]$A = 2; $A -le (GetSgsValue ("Y2K,1")); $A++) { 
        DEFINE_INTER1 ((GetSgsValue ("Y2K,1,$A,2")))
        If ((CompareTypeSafe $I "EqualTo" $I1)) {
          DataLineOrNoStatement ("           02  IND" + ($I) + ". ")
          DEFINE_FIL2 ((GetSgsValue ("Y2K,1,$A,1")))
          DEFINE_FIL3 ((GetSgsValue ("Y2K,1,$A,3")))
          DataLineOrNoStatement ("               06 DET" + ($I) + "             PIC X(" + ($FILLCTR) + ").")
          DEFINE_FIL1 ((GetSgsValue ("INDIC,1,$I1,2"))) ((GetSgsValue ("Y2K,1,$A,3"))) ((GetSgsValue ("Y2K,1,$A,1")))
          DEFINE_SW ((GetSgsValue ("Y2K,1,$A,1")))
        }
      }
      If ($SW) {
      } else {
        DataLineOrNoStatement ("           02  IND" + ($I) + "  PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
      }
    } else {
      DataLineOrNoStatement ("           02  IND" + ($I) + "  PIC X(" + ((GetSgsValue ("INDIC,1,$I,2"))) + ").   ")
    }
    DataLineOrNoStatement ("           02  FILLER   PIC  X   VALUE SPACE.   ")
  }
}
DataLineOrNoStatement ("       01  LIGNES-SUB.  ")
$J = 0
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I += 4) { 
  DataLineOrNoStatement ("           02  LIG-SUB" + ($I) + ". ")
  DataLineOrNoStatement ("             03 FA" + ($I) + "   PIC X(12)  VALUE '*SOUS-TOTAL*'.   ")
  DEFINE_SEJP3 ($I)
  For ([Int32]$K = $I; $K -le $J; $K++) { 
    DataLineOrNoStatement ("               03 FILLER  PIC  X(3)  VALUE  SPACES. ")
    DataLineOrNoStatement ("               03 MONT" + ($K) + "  PIC  X(25). ")
  }
}
DataLineOrNoStatement ("       01  ADETAIL. ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           03 DMONT" + ($I) + "  PIC SH9(18)  VALUE 0.  ")
  DataLineOrNoStatement ("           03 FILLER PIC X. ")
}
DataLineOrNoStatement ("       01  CDTOAF.  ")
DataLineOrNoStatement ("           03  CDTOAF-PRM-ENE.  ")
DataLineOrNoStatement ("               05  CDTOAF-DT-ENE.   ")
DataLineOrNoStatement ("                   07  CDTOAF-AA-ENE.   ")
DataLineOrNoStatement ("                       09  CDTOAF-A1-ENE       PIC X(01).   ")
DataLineOrNoStatement ("                       09  CDTOAF-A2-ENE       PIC X(01).   ")
DataLineOrNoStatement ("                   07  CDTOAF-MM-ENE           PIC X(02).   ")
DataLineOrNoStatement ("                   07  CDTOAF-JJ-ENE           PIC X(02).   ")
DataLineOrNoStatement ("           03  CDTOAF-PRM-SRT.  ")
DataLineOrNoStatement ("               05  CDTOAF-DT-SRT-9             PIC 9(08).   ")
DataLineOrNoStatement ("               05  CDTOAF-DT-SRT REDEFINES CDTOAF-DT-SRT-9. ")
DataLineOrNoStatement ("                   07  CDTOAF-SSAA-SRT         PIC X(04).   ")
DataLineOrNoStatement ("                   07  CDTOAF-SSAA-SRT-RDF REDEFINES CDTOAF-SSAA-SRT.   ")
DataLineOrNoStatement ("                      09  CDTOAF-SS-SRT        PIC X(02).   ")
DataLineOrNoStatement ("                      09  CDTOAF-AA-SRT.")
DataLineOrNoStatement ("                          11  CDTOAF-A1-SRT    PIC X(01).   ")
DataLineOrNoStatement ("                          11  CDTOAF-A2-SRT    PIC X(01).   ")
DataLineOrNoStatement ("                   07  CDTOAF-MM-SRT           PIC X(02).   ")
DataLineOrNoStatement ("                   07  CDTOAF-JJ-SRT           PIC X(02).   ")
DataLineOrNoStatement ("               05  CDTOAF-DTE-SRT REDEFINES CDTOAF-DT-SRT-9.")
DataLineOrNoStatement ("                   07  CDTOAF-SSS-SRT          PIC X(02).   ")
DataLineOrNoStatement ("                   07  CDTOAF-DT6-SRT          PIC X(06).   ")
DataLineOrNoStatement ("               05  CDTOAF-DTE2-SRT REDEFINES CDTOAF-DT-SRT-9.   ")
DataLineOrNoStatement ("                   07  CDTOAF-SS2-SRT          PIC X(02).   ")
DataLineOrNoStatement ("                   07  CDTOAF-AAMM-SRT         PIC X(04).   ")
DataLineOrNoStatement ("                   07  CDTOAF-JJ2-SRT          PIC X(02).   ")
DataLineOrNoStatement ("       01  EUW002.  ")
DataLineOrNoStatement ("           03  WS-PTR-ENE.  ")
DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-ENE.  ")
DataLineOrNoStatement ("                   07  MT-ENE              PIC S9(17).  ")
DataLineOrNoStatement ("                   07  MT-ENE-SGN          PIC X(01).   ")
DataLineOrNoStatement ("                   07  MT-ENE-CHI          PIC 9(02).   ")
DataLineOrNoStatement ("               05  WS-PTR-ENE-MON-SRT.  ")
DataLineOrNoStatement ("                   07  LG-MAX-MON-SRT      PIC 9(03).   ")
DataLineOrNoStatement ("                   07  CD-FMT-MON-SRT      PIC X(01).   ")
DataLineOrNoStatement ("                   07  WS-PTR-FAC-MON-SRT.  ")
DataLineOrNoStatement ("                       09  FL-IMP-APO      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-IMP-EUR      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-IMP-BEF      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-PLT-SGN      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-TRD-SGN      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-SGN-FIX      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-SGN-VUE      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-CAD-PRC      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-CAD-CNV      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-IMP-PNT      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FL-000          PIC X(01).   ")
DataLineOrNoStatement ("                       09  CD-DET-MON      PIC X(01).   ")
DataLineOrNoStatement ("                       09  FILLER          PIC X(19).   ")
DataLineOrNoStatement ("           03  WS-PTR-SRT.  ")
DataLineOrNoStatement ("               05  WS-MON-SRT-001.  ")
DataLineOrNoStatement ("                   07  MT-SRT              PIC X(100).  ")
DataLineOrNoStatement ("               05  WS-MON-SRT-002.  ")
DataLineOrNoStatement ("                   07  MT-SRT-PRC          PIC X(50).   ")
DataLineOrNoStatement ("                   07  MT-SRT-CNV          PIC X(50).   ")
DataLineOrNoStatement ("                   07  TL-PTH-GCH          PIC X(01).   ")
DataLineOrNoStatement ("                   07  TL-PTH-DRT          PIC X(01).   ")
DataLineOrNoStatement ("               05  LG-MON-SRT              PIC 9(02).   ")
DataLineOrNoStatement ("               05  LB-DVI-PRC              PIC X(03).   ")
DataLineOrNoStatement ("               05  LB-DVI-CNV              PIC X(03).   ")
DataLineOrNoStatement ("           03  WS-PTR-ENE-SRT.  ")
DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
DataLineOrNoStatement ("           03  WS-IFN-EUR.  ")
DataLineOrNoStatement ("               05  FILLER                  PIC X(10).   ")
DataLineOrNoStatement ("       01  WS-CMT-PGM.  ")
DataLineOrNoStatement ("           03  NM-PGM-APL               PIC X(08).  ")
DataLineOrNoStatement ("           03  NM-NOM-ENV               PIC X(08).  ")
DataLineOrNoStatement ("           03  NM-NOM-COP               PIC X(08).  ")
DataLineOrNoStatement ("           03  NM-NOM-DEM               PIC X(08).  ")
DataLineOrNoStatement ("           03  VL-CDE-RET               PIC S9(04). ")
DataLineOrNoStatement ("           03  VL-MOT-CDE               PIC S9(04). ")
DataLineOrNoStatement ("           03  LB-MSG-RET               PIC X(30).  ")
DataLineOrNoStatement ("           03  CD-DBG-PRG               PIC X(1).   ")
DataLineOrNoStatement ("           03  FILLER                   PIC X(7).   ")
DataLineOrNoStatement ("           03  VL-CHP-TSF               PIC X(3922).")
DataLineOrNoStatement ("       01  RDMS-QUALIFIER                        PIC X(12). ")
DataLineOrNoStatement ("       01  RDMS-IND                              PIC 9(2).  ")
DataLineOrNoStatement ("       01  RDMS-STATUS                           PIC 9999  VALUE 0. ")
DataLineOrNoStatement ("       01  RDMS-SAV-STATUS                       PIC 9999  VALUE 0. ")
DataLineOrNoStatement ("       01  RDMS-ROLLB                            PIC 9     VALUE 0. ")
DataLineOrNoStatement ("       01  RDMS-COLUMN                           PIC S1(36).")
DataLineOrNoStatement ("       01  RDMS-SAV-COLUMN                       PIC S1(36).")
DataLineOrNoStatement ("       01  RDMS-FLAG                             PIC 9     VALUE 0. ")
DataLineOrNoStatement ("       01  RDMS-FLAG-THREAD                      PIC 9     VALUE 0. ")
DataLineOrNoStatement ("       01  RDMS-RESULT. ")
DataLineOrNoStatement ("             05 RDMS-ERROR-LINE OCCURS 4         PIC X(80). ")
DataLineOrNoStatement ("       01  RDMS-COM.")
DataLineOrNoStatement ("             05 RLIN            OCCURS 36        PIC X(40). ")
DataLineOrNoStatement ("       01  ZONE-25                               PIC Z(18). ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEBUT.   OPEN INPUT TAPE1.   ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  LIGNES-SUB.")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I += 4) { 
  DataLineOrNoStatement ("           MOVE  '*SOUS-TOTAL*'  TO  FA" + ($I) + ".")
}
DataLineOrNoStatement ("           OPEN OUTPUT  IMP.")
DataLineOrNoStatement ("           CALL 'RSA`$INIT'. ")
DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
DataLineOrNoStatement ("             'BEGIN THREAD FOR APPLICATION UDSSRC READ;',   ")
DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
DataLineOrNoStatement ("           MOVE 1 TO RDMS-FLAG-THREAD.  ")
DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
DataLineOrNoStatement ("             'USE DEFAULT QUALIFIER " + ($schname) + ";',   ")
DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
DataLineOrNoStatement ("             'USE DEFAULT VERSION PRODUCTION ;',")
DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG. ")
DataLineOrNoStatement ("           MOVE 'TABAN'     TO NM-PGM-APL   OF WS-CMT-PGM.  ")
DataLineOrNoStatement ("           MOVE 'BATCH'     TO NM-NOM-ENV   OF WS-CMT-PGM.  ")
DataLineOrNoStatement ("           MOVE 'Y'         TO CD-DBG-PRG   OF WS-CMT-PGM.  ")
DataLineOrNoStatement ("           MOVE 'EUW002'    TO NM-NOM-COP   OF WS-CMT-PGM.  ")
DataLineOrNoStatement ("           MOVE 'SERVICE1'  TO NM-NOM-DEM   OF WS-CMT-PGM.  ")
DataLineOrNoStatement ("           MOVE SPACES      TO WS-PTR-ENE   OF EUW002.  ")
DataLineOrNoStatement ("           MOVE 'R'         TO FL-PLT-SGN   OF EUW002.  ")
DataLineOrNoStatement ("           MOVE '2'         TO FL-TRD-SGN   OF EUW002.  ")
DataLineOrNoStatement ("           MOVE 'Y'         TO MT-ENE-SGN   OF EUW002.  ")
DataLineOrNoStatement ("           MOVE '1'         TO CD-FMT-MON-SRT  OF EUW002.   ")
DataLineOrNoStatement ("           MOVE 'Y'         TO FL-IMP-PNT      OF EUW002.   ")
DataLineOrNoStatement ("           MOVE 'N'         TO FL-000          OF EUW002.   ")
DataLineOrNoStatement ("       LECT.  READ TAPE1  AT END GO TO FINBDE.  ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           IF LMONT" + ($I) + "  OF REC" + ($I) + " NUMERIC GO TO EXIT" + ($I) + ". ")
  DataLineOrNoStatement ("           IF LMONT" + ($I) + " OF REC" + ($I) + " = SPACES ")
  DataLineOrNoStatement ("           MOVE ZEROES TO LMONT" + ($I) + " OF REC" + ($I) + " GO TO EXIT" + ($I) + ".  ")
  DataLineOrNoStatement ("           PERFORM PMONT" + ($I) + " VARYING KMONT" + ($I) + " FROM 1 BY 1 UNTIL")
  DataLineOrNoStatement ("               KMONT" + ($I) + " = (" + ((GetSgsValue ("KEYS,1,$I,2"))) + " + 1).  ")
  DataLineOrNoStatement ("       EXIT" + ($I) + ".")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           MOVE CORRESPONDING REC" + ($I) + " TO ZONE-WORK. ")
}
If ((CompareTypeSafe (GetSgsValue ("CCARTE")) "EqualTo" 0)) {
} else {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("CCARTE,1")); $I++) { 
    DataLineOrNoStatement ("           IF CCART  EQUAL TO '" + ((GetSgsValue ("CCARTE,1,$I,1"))) + "'  GO TO CODEC.")
  }
  DataLineOrNoStatement ("           GO TO LECT.  ")
  DataLineOrNoStatement ("       CODEC.   ")
}
DataLineOrNoStatement ("           ADD  1  TO  NB-LUS.  ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("INDIC,1")); $I++) { 
    DataLineOrNoStatement ("           MOVE  LIND" + ($I) + "  TO  IND" + ($I) + "  OF  W-INDIC.")
  }
}
If ((CompareTypeSafe (GetSgsValue ("MAXREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           IF  NB-LUS > " + ((GetSgsValue ("MAXREC,1,1,1"))) + "  GO TO  FINMAX.  ")
}
DataLineOrNoStatement ("           IF  FIRS  =  0  MOVE  1  TO  FIRS  GO TO CONT1.  ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "EqualTo" 0)) {
    DataLineOrNoStatement ("           IF  W-INDIC-OLD  GREATER THAN W-INDIC  GO TO  ERR-SEQ.   ")
  }
  DataLineOrNoStatement ("           IF  W-INDIC  NOT EQUAL TO W-INDIC-OLD  GO TO RUPT.   ")
}
DataLineOrNoStatement ("       LECT2.   ")
If ((CompareTypeSafe (GetSgsValue ("UTYL2")) "GreaterThan" 0)) {
  For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
    DataLineOrNoStatement ("           IF  LMONT" + ($I) + " IS NEGATIVE")
    DataLineOrNoStatement ("           MULTIPLY -1 BY LMONT" + ($I) + ".")
    DataLineOrNoStatement ("           IF  CCART NOT NUMERIC")
    DataLineOrNoStatement ("           MULTIPLY -1  BY  LMONT" + ($I) + "   ")
    DataLineOrNoStatement ("           GO TO ENDUTYL" + ($I) + ".   ")
    DataLineOrNoStatement ("       ENDUTYL" + ($I) + ". ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("LISTE")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE 17     TO MT-ENE-CHI OF EUW002. ")
  DataLineOrNoStatement ("           MOVE 25     TO LG-MAX-MON-SRT OF EUW002. ")
  $EURO = 0
  $LIG = 1
  For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
    DataLineOrNoStatement ("           MOVE  LMONT" + ($I) + " OF REC" + ($I) + " TO DMONT" + ($I) + " OF ADETAIL.  ")
    DataLineOrNoStatement ("           MOVE DMONT" + ($I) + "   TO MT-ENE OF EUW002.")
    DataLineOrNoStatement ("           MOVE EUW002       TO VL-CHP-TSF  OF WS-CMT-PGM.  ")
    DataLineOrNoStatement ("           CALL 'EUU003'     USING WS-CMT-PGM.  ")
    DataLineOrNoStatement ("           MOVE VL-CHP-TSF   OF WS-CMT-PGM TO EUW002.   ")
    DataLineOrNoStatement ("           MOVE MT-SRT       OF EUW002 TO MONT" + ($I) + " OF LIGNES-SUB.   ")
    DEFINE_ADDEURO ($EURO)
    If ((CompareTypeSafe $EURO "EqualTo" 4)) {
      DataLineOrNoStatement ("           MOVE '*DETAIL*    ' TO FA" + ($LIG) + ". ")
      DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
      DataLineOrNoStatement ("           MOVE '*SOUS-TOTAL*' TO FA" + ($LIG) + ". ")
      $EURO = 0
      DEFINE_LIGNE ($LIG)
    }
  }
  If ((CompareTypeSafe $EURO "GreaterThan" 0)) {
    DataLineOrNoStatement ("           MOVE '*DETAIL*    ' TO FA" + ($LIG) + ". ")
    DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
    DataLineOrNoStatement ("           MOVE '*SOUS-TOTAL*' TO FA" + ($LIG) + ". ")
  }
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           ADD   LMONT" + ($I) + " OF ZONE-WORK TO  MONT" + ($I) + "  OF  SUB-TOTAL.")
}
DataLineOrNoStatement ("           GO TO LECT.  ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       RUPT.")
  DataLineOrNoStatement ("           PERFORM  IMP-INDIC-OLD.  ")
  DataLineOrNoStatement ("           PERFORM   IMP-SUB-TOTAL. ")
  DataLineOrNoStatement ("           ADD  CORRESPONDING  SUB-TOTAL   TO  TOTAL.   ")
}
DataLineOrNoStatement ("       CONT1.   ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("           MOVE  0  TO MONT" + ($I) + "   OF SUB-TOTAL. ")
}
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE  W-INDIC  TO  W-INDIC-OLD.  ")
}
DataLineOrNoStatement ("           GO TO LECT2. ")
If ((CompareTypeSafe (GetSgsValue ("MAXREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       FINMAX.  ")
  DataLineOrNoStatement ("           MOVE  'ATTENTION LIMITE DE TABULATION' TO LIGNE. ")
  DataLineOrNoStatement ("           WRITE  LIGNE  AFTER  2.  ")
  DataLineOrNoStatement ("           GO TO FINBDE.")
}
DataLineOrNoStatement ("       FINBDE.  ")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           PERFORM  RUPT.   ")
} else {
  DataLineOrNoStatement ("           ADD  CORRESPONDING  SUB-TOTAL  TO  TOTAL.")
}
DataLineOrNoStatement ("           PERFORM  IMP-TOTAL.  ")
DataLineOrNoStatement ("           MOVE  NB-LUS  TO   P-LUS.")
DataLineOrNoStatement ("           WRITE  LIGNE  FROM  TIT-TOTAL  AFTER  3. ")
DataLineOrNoStatement ("       FF. CLOSE  TAPE1.")
DataLineOrNoStatement ("           CLOSE  IMP.  ")
DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
DataLineOrNoStatement ("             'END THREAD ;',")
DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN.  ")
DataLineOrNoStatement ("           IF RDMS-STATUS NOT = 0 GO TO RDMS-ERROR-PAR. ")
DataLineOrNoStatement ("           MOVE 0 TO RDMS-FLAG-THREAD.  ")
DataLineOrNoStatement ("           STOP RUN.")
If ((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       IMP-INDIC-OLD.   ")
  DataLineOrNoStatement ("           MOVE CORRESPONDING  W-INDIC-OLD  TO TIT-RUPT1.   ")
  If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           PERFORM AN-2000 THRU AN-2000-EXIT")
  }
  DataLineOrNoStatement ("           WRITE LIGNE  FROM  TIT-RUPT1  AFTER  2.  ")
  DataLineOrNoStatement ("       IMP-SUB-TOTAL.   ")
  DataLineOrNoStatement ("           MOVE 17     TO MT-ENE-CHI OF EUW002. ")
  DataLineOrNoStatement ("           MOVE 25     TO LG-MAX-MON-SRT OF EUW002. ")
  $EURO = 0
  $LIG = 1
  For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
    $NEURO = 0
    If ((CompareTypeSafe (GetSgsValue ("NEURO")) "GreaterThan" 0)) {
      For ([Int32]$Z = 1; $Z -le (GetSgsValue ("$NEURO,1")); $Z++) { 
        If ((CompareTypeSafe (GetSgsValue ("$NEURO,1,$Z,1")) "EqualTo" $I)) {
          $NEURO = 1
        }
      }
    }
    If ((CompareTypeSafe $NEURO "GreaterThan" 0)) {
      DataLineOrNoStatement ("           MOVE MONT" + ($I) + "     OF SUB-TOTAL TO ZONE-25.   ")
      DataLineOrNoStatement ("           MOVE ZONE-25               TO MONT" + ($I) + " OF LIGNES-SUB.")
    } else {
      DataLineOrNoStatement ("           MOVE MONT" + ($I) + "     OF SUB-TOTAL TO MT-ENE OF EUW002.  ")
      DataLineOrNoStatement ("           MOVE EUW002       TO VL-CHP-TSF  OF WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           CALL 'EUU003'     USING WS-CMT-PGM.  ")
      DataLineOrNoStatement ("           MOVE VL-CHP-TSF   OF WS-CMT-PGM TO EUW002.   ")
      DataLineOrNoStatement ("           MOVE MT-SRT       OF EUW002 TO MONT" + ($I) + " OF LIGNES-SUB.   ")
    }
    DEFINE_ADDEURO ($EURO)
    If ((CompareTypeSafe $EURO "EqualTo" 4)) {
      DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
      $EURO = 0
      DEFINE_LIGNE ($LIG)
    }
  }
  If ((CompareTypeSafe $EURO "GreaterThan" 0)) {
    DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
  }
}
DataLineOrNoStatement ("       IMP-TOTAL.   ")
DataLineOrNoStatement ("           MOVE '*****TOTAL GENERAL *****'  TO  LIGNE.  ")
DataLineOrNoStatement ("            WRITE  LIGNE  AFTER PAGE.   ")
DataLineOrNoStatement ("           MOVE 17     TO MT-ENE-CHI OF EUW002. ")
DataLineOrNoStatement ("           MOVE 25     TO LG-MAX-MON-SRT OF EUW002. ")
$EURO = 0
$LIG = 1
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  $NEURO = 0
  If ((CompareTypeSafe (GetSgsValue ("NEURO")) "GreaterThan" 0)) {
    For ([Int32]$Z = 1; $Z -le (GetSgsValue ("$NEURO,1")); $Z++) { 
      If ((CompareTypeSafe (GetSgsValue ("$NEURO,1,$Z,1")) "EqualTo" $I)) {
        $NEURO = 1
      }
    }
  }
  If ((CompareTypeSafe $NEURO "GreaterThan" 0)) {
    DataLineOrNoStatement ("           MOVE MONT" + ($I) + "     OF TOTAL TO ZONE-25.   ")
    DataLineOrNoStatement ("           MOVE ZONE-25               TO MONT" + ($I) + " OF LIGNES-SUB.")
  } else {
    DataLineOrNoStatement ("           MOVE MONT" + ($I) + "     OF TOTAL TO MT-ENE OF EUW002.  ")
    DataLineOrNoStatement ("           MOVE EUW002       TO VL-CHP-TSF  OF WS-CMT-PGM.  ")
    DataLineOrNoStatement ("           CALL 'EUU003'     USING WS-CMT-PGM.  ")
    DataLineOrNoStatement ("           MOVE VL-CHP-TSF   OF WS-CMT-PGM TO EUW002.   ")
    DataLineOrNoStatement ("           MOVE MT-SRT       OF EUW002 TO MONT" + ($I) + " OF LIGNES-SUB.   ")
  }
  DEFINE_ADDEURO ($EURO)
  If ((CompareTypeSafe $EURO "EqualTo" 4)) {
    DataLineOrNoStatement ("           MOVE SPACES TO FA" + ($LIG) + ". ")
    DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
    $EURO = 0
    DEFINE_LIGNE ($LIG)
  }
}
If ((CompareTypeSafe $EURO "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE SPACES TO FA" + ($LIG) + ". ")
  DataLineOrNoStatement ("           WRITE  LIGNE  FROM  LIG-SUB" + ($LIG) + "  AFTER 1.  ")
}
If (((CompareTypeSafe (GetSgsValue ("INDIC")) "GreaterThan" 0) -and (CompareTypeSafe (GetSgsValue ("SEQERROR")) "EqualTo" 0))) {
  DataLineOrNoStatement ("       ERR-SEQ. ")
  DataLineOrNoStatement ("           MOVE      '*ANCIEN INDIC*'          TO  FILLI.   ")
  DataLineOrNoStatement ("           MOVE      '**ERREUR DE SEQUENCE**'  TO  LIGNE.   ")
  DataLineOrNoStatement ("           WRITE  LIGNE  AFTER  5.  ")
  DataLineOrNoStatement ("           PERFORM   IMP-INDIC-OLD. ")
  DataLineOrNoStatement ("           MOVE      '*NOUVEL INDIC*'     TO  FILLI.")
  DataLineOrNoStatement ("           MOVE  CORRESPONDING   W-INDIC  TO  W-INDIC-OLD.  ")
  DataLineOrNoStatement ("           PERFORM   IMP-INDIC-OLD. ")
  DataLineOrNoStatement ("           GO  TO  FF.  ")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("KEYS,1")); $I++) { 
  DataLineOrNoStatement ("       PMONT" + ($I) + ".   ")
  DataLineOrNoStatement ("           IF TMONT" + ($I) + " (KMONT" + ($I) + ") = SPACES MOVE ZEROES TO ")
  DataLineOrNoStatement ("               TMONT" + ($I) + " (KMONT" + ($I) + ").   ")
}
If ((CompareTypeSafe (GetSgsValue ("Y2K")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       AN-2000. ")
  For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,1")); $B++) { 
    DataLineOrNoStatement ("           MOVE SPACES TO CDTOAF")
    DataLineOrNoStatement ("           MOVE ZTI-" + ((GetSgsValue ("Y2K,1,$B,2"))) + " OF W-INDIC-OLD TO CDTOAF-AA-ENE ")
    DataLineOrNoStatement ("           MOVE 01     TO CDTOAF-MM-ENE ")
    DataLineOrNoStatement ("                          CDTOAF-JJ-ENE ")
    DataLineOrNoStatement ("           CALL 'CDTOAF'  USING CDTOAF. ")
    DataLineOrNoStatement ("           MOVE CDTOAF-SSAA-SRT TO DET" + ((GetSgsValue ("Y2K,1,$B,2"))) + ".  ")
  }
  DataLineOrNoStatement ("       AN-2000-EXIT.")
  DataLineOrNoStatement ("           EXIT.")
}
DataLineOrNoStatement ("       RDMS-ERROR-PAR.  ")
DataLineOrNoStatement ("           DISPLAY '*** ERROR RDMS ***' UPON PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY 'COLUMN = ' RDMS-COLUMN UPON PRINTER.")
DataLineOrNoStatement ("           DISPLAY 'STATUS = ' RDMS-STATUS UPON PRINTER.")
DataLineOrNoStatement ("           PERFORM TRAIT-RDMS.  ")
DataLineOrNoStatement ("           GO TO RDMS-ERROR-EX. ")
DataLineOrNoStatement ("       TRAIT-RDMS.  ")
DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
DataLineOrNoStatement ("           PERFORM VISU-RDMS-COM VARYING RDMS-IND FROM 1 BY 1   ")
DataLineOrNoStatement ("               UNTIL RDMS-IND > 36. ")
DataLineOrNoStatement ("           MOVE ZEROS TO RDMS-FLAG. ")
DataLineOrNoStatement ("           PERFORM TRAIT-RDMS-ERROR ")
DataLineOrNoStatement ("               UNTIL RDMS-FLAG NOT = ZEROS. ")
DataLineOrNoStatement ("       TRAIT-RDMS-ERROR.")
DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
DataLineOrNoStatement ("             'GETERROR INTO `$P1, `$P2, `$P3, `$P4 ;',  ")
DataLineOrNoStatement ("             RDMS-STATUS, RDMS-COLUMN,  ")
DataLineOrNoStatement ("             RDMS-ERROR-LINE (1), RDMS-ERROR-LINE (2),  ")
DataLineOrNoStatement ("             RDMS-ERROR-LINE (3), RDMS-ERROR-LINE (4).  ")
DataLineOrNoStatement ("           PERFORM VISU-RDMS-ERROR  ")
DataLineOrNoStatement ("             VARYING RDMS-IND FROM 1 BY 1   ")
DataLineOrNoStatement ("             UNTIL RDMS-IND > 4.")
DataLineOrNoStatement ("       VISU-RDMS-ERROR. ")
DataLineOrNoStatement ("           IF RDMS-ERROR-LINE (RDMS-IND) NOT = SPACE")
DataLineOrNoStatement ("                DISPLAY RDMS-ERROR-LINE (RDMS-IND) UPON PRINTER ")
DataLineOrNoStatement ("           ELSE MOVE 1 TO RDMS-FLAG.")
DataLineOrNoStatement ("       VISU-RDMS-COM.   ")
DataLineOrNoStatement ("           IF RLIN (RDMS-IND) NOT = SPACES  ")
DataLineOrNoStatement ("                DISPLAY RLIN (RDMS-IND) UPON PRINTER.   ")
DataLineOrNoStatement ("       RDMS-ERROR-EX.   ")
# @MAP s    ,TPF$.TABAN   
Call-ExternalProgram "MAP" "S" (",TPF`$\TABAN")
# Orphaned data line: IBANK,XU C$DML
# Orphaned data line: IBANK,M  I$1,022000
# Orphaned data line: IN       TPF$.
# Orphaned data line: IN SYS$LIB$*ACOB-DML.CBEP$$ACOB/FULL-LIB-CB
# Orphaned data line: IN SYS$LIB$*RSA.RDMR-ACOBDAT
# Orphaned data line: IN SYS$LIB$*RSA.CBEP$$RSA
# Orphaned data line: DBANK,MUC    D$1
# Orphaned data line: FORM         I$1
# Orphaned data line: LIB          PRD*REL.
# Orphaned data line: LIB          SYS*REL.
Hdg "N"
Fin
