# Converted from SSG source: CHABAN_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_calun {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_CALUN") {
    Return
  }

  $FILUN = ($Parameters[0] - 1)
  If ($FILUN) {
    DataLineOrNoStatement ("           03  FILLER                   PIC X(" + ($FILUN) + ").    ")
  }
}
Function Define_caldeu {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_CALDEU") {
    Return
  }

  $FILDEU = ($Parameters[0] - ($Parameters[1] - ($Parameters[2] + 1)))
  If ($FILDEU) {
    DataLineOrNoStatement ("           03  FILLER                   PIC X(" + ($FILDEU) + ").   ")
  }
}
Function Define_caltroi {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_CALTROI") {
    Return
  }

  $FILTROI = ($Parameters[0] - 1)
  DataLineOrNoStatement ("           MOVE " + ($FILTROI) + " TO NBFOIS.     ")
}
Function Define_calmax {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_CALMAX") {
    Return
  }

  $A = 0
  $B = 0
  $A = $Parameters[0] / 80
  $A = $Parameters[0] % 80
  If ($B) {
    $A = ($A + 1)
  }
  For ([Int32]$J = 1; $J -le $A; $J++) { 
    DataLineOrNoStatement ("           03  ZCAR" + ($J) + "      PIC X(80).   ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB I    TPF$.CHABANA,TPF$.CHABANB
  Call-ExternalProgram "ACOB" "I" ("TPF`$\CHABANA")
  Fin
} else {
  # @ACOB IT   TPF$.CHABANA,TPF$.CHABANB
  Call-ExternalProgram "ACOB" "I, T" ("TPF`$\CHABANA")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION.     ")
DataLineOrNoStatement ("       PROGRAM-ID.    CHABAN. ")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY. ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.  ")
DataLineOrNoStatement ("       CONFIGURATION SECTION. ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1106.")
DataLineOrNoStatement ("       SPECIAL-NAMES.   ")
DataLineOrNoStatement ("           PAGE IS SAUT.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.  ")
DataLineOrNoStatement ("       FILE-CONTROL.    ")
DataLineOrNoStatement ("           SELECT FIC ASSIGN TO DISC " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".  ")
DataLineOrNoStatement ("           SELECT CAR ASSIGN TO CARD-READER.    ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           SELECT PRI ASSIGN TO PRINTER.  ")
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.    ")
DataLineOrNoStatement ("       FD  FIC    ")
DataLineOrNoStatement ("           BLOCK " + ((GetSgsValue ("OUTPUT,1,1,3"))) + " RECORDS   ")
DataLineOrNoStatement ("           LABEL RECORD STANDARD    ")
DataLineOrNoStatement ("           DATA RECORD ZFIC.  ")
DataLineOrNoStatement ("       01  ZFIC               PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
DataLineOrNoStatement ("       FD  CAR    ")
DataLineOrNoStatement ("           LABEL RECORD OMITTED     ")
DataLineOrNoStatement ("           DATA RECORD ZIN.   ")
DataLineOrNoStatement ("       01  ZIN      PIC X(80).")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       FD  PRI    ")
  DataLineOrNoStatement ("           LABEL RECORD OMITTED     ")
  DataLineOrNoStatement ("           DATA RECORD ZPR.   ")
  DataLineOrNoStatement ("       01  ZPR                PIC X(100). ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION.     ")
DataLineOrNoStatement ("       01  COUNTERS  VALUE ALL ZEROES.    ")
DataLineOrNoStatement ("           03  CTOUT          PIC S9(7).  ")
DataLineOrNoStatement ("           03  CTFS           PIC S9(5).  ")
DataLineOrNoStatement ("           03  CTCAR          PIC S9(5).  ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  ZPRINT   VALUE SPACES.   ")
  For ([Int32]$N = 1; $N -le (GetSgsValue ("OUTPUT,1,1,2")); $N += 100) { 
    DataLineOrNoStatement ("           03  ZP" + ($N) + "         PIC X(100). ")
  }
}
DataLineOrNoStatement ("       01  ZOUT     VALUE SPACES.   ")
For ([Int32]$N = 1; $N -le (GetSgsValue ("OUTPUT,1,1,2")); $N += 80) { 
  DataLineOrNoStatement ("           03  ZT" + ($N) + "         PIC X(80).  ")
}
DataLineOrNoStatement ("       01  ZOUTR    REDEFINES ZOUT. ")
DataLineOrNoStatement ("           03  ZTR OCCURS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " PIC X. ")
For ([Int32]$I = 1; $I -le (GetSgsValue ("MOD")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("MOD,$I,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("       01  ZOU" + ($I) + " REDEFINES  ZOUT. ")
    DEFINE_CALUN ((GetSgsValue ("MOD,$I,1,1")))
    If ((CompareTypeSafe (GetSgsValue ("MOD,$I,1,3")) "EqualTo" $A)) {
      DataLineOrNoStatement ("           03  CHAMP" + ($I) + ".     ")
      DataLineOrNoStatement ("             05  CHMODA" + ($I) + " OCCURS " + ((GetSgsValue ("MOD,$I,1,2"))) + "    PIC X.    ")
    } else {
      DataLineOrNoStatement ("           03  CHMODN" + ($I) + "     PIC S9(" + ((GetSgsValue ("MOD,$I,1,2"))) + ").    ")
    }
    DEFINE_CALDEU ((GetSgsValue ("OUTPUT,1,1,2"))) ((GetSgsValue ("MOD,$I,1,1"))) ((GetSgsValue ("MOD,$I,1,2")))
  }
}
DataLineOrNoStatement ("       01  ZCAR.  ")
DEFINE_CALMAX ((GetSgsValue ("OUTPUT,1,1,2")))
DataLineOrNoStatement ("       01  ZCPOS REDEFINES ZCAR.    ")
DataLineOrNoStatement ("           03  ZCEM OCCURS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " PIC X.")
DataLineOrNoStatement ("       01  INDEKS.")
DataLineOrNoStatement ("           03  IED            PIC S9999 VALUE 1.")
DataLineOrNoStatement ("           03  IEF            PIC S9999 VALUE 1.")
DataLineOrNoStatement ("           03  IRD            PIC S9999 VALUE 1.")
DataLineOrNoStatement ("       01  ZTIT.  ")
DataLineOrNoStatement ("           03  FILLER      PIC X(4) VALUE ALL '*'.    ")
DataLineOrNoStatement ("           03  FILLER         PIC X(2) VALUE SPACES.  ")
DataLineOrNoStatement ("           03  FILLER         PIC X(16) VALUE 'RECORD NUMERO **'. ")
DataLineOrNoStatement ("           03  FILCT          PIC Z(7).   ")
DataLineOrNoStatement ("       01  CTSPEC             PIC S9(7) VALUE 0.")
DataLineOrNoStatement ("       01  CTTEST             PIC S9(7) VALUE 0.")
DataLineOrNoStatement ("       01  NBFOIS             PIC S9(7) VALUE 0.")
DataLineOrNoStatement ("       01  ZONE               PIC X VALUE SPACES.     ")
DataLineOrNoStatement ("       01  TABLE-ALPHA        PIC X(26) VALUE   ")
DataLineOrNoStatement ("                              'ABCDEFGHIJKLMNOPQRSTUVWXYZ'. ")
DataLineOrNoStatement ("       01  TABALPHA REDEFINES TABLE-ALPHA.")
DataLineOrNoStatement ("           03  ALPHA OCCURS 26  PIC X.    ")
DataLineOrNoStatement ("       01  VALEUR             PIC S9999 VALUE 0.")
DataLineOrNoStatement ("       01  VINSIX             PIC S99  VALUE 26.")
DataLineOrNoStatement ("       01  ZREP               PIC S9999 VALUE 0.")
DataLineOrNoStatement ("       01  DIX                PIC S99  VALUE 10.")
DataLineOrNoStatement ("       01  TABLE-NUM      PIC X(10) VALUE '0123456789'.     ")
DataLineOrNoStatement ("       01  TABNUM  REDEFINES TABLE-NUM.   ")
DataLineOrNoStatement ("           03  NUMER  OCCURS 10         PIC X.  ")
DataLineOrNoStatement ("       01  RETOUR        PIC X VALUE SPACE.     ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.    ")
DataLineOrNoStatement ("       P1.  ")
DataLineOrNoStatement ("           OPEN INPUT CAR OUTPUT FIC.     ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           OPEN OUTPUT PRI.   ")
  DataLineOrNoStatement ("           WRITE ZPR FROM ZP1 BEFORE SAUT.")
}
For ([Int32]$I = 1; $I -le (GetSgsValue ("NUMB")); $I++) { 
  If ((CompareTypeSafe (GetSgsValue ("NUMB,$I,1")) "GreaterThan" 1)) {
    DEFINE_CALTROI ((GetSgsValue ("NUMB,$I,1,2")))
    DataLineOrNoStatement ("            PERFORM PAR" + ($I) + " NBFOIS TIMES. ")
  }
  DataLineOrNoStatement ("       PAR" + ($I) + ".   ")
  DataLineOrNoStatement ("           ADD " + ((GetSgsValue ("NUMB,$I,1,1"))) + " TO CTSPEC.    ")
  If ((CompareTypeSafe (GetSgsValue ("FLDSEL,$I,1,1")) "EqualTo" 0)) {
    For ([Int32]$J = 1; $J -le (GetSgsValue ("OUTPUT,1,1,2")); $J += 80) { 
      DataLineOrNoStatement ("           READ CAR INTO ZT" + ($J) + " AT END GO TO STATIS.  ")
      DataLineOrNoStatement ("           ADD 1 TO CTCAR.    ")
    }
  } else {
    For ([Int32]$J = 1; $J -le (GetSgsValue ("NUMB,$I,1,1")); $J++) { 
      DataLineOrNoStatement ("           READ CAR INTO ZCAR" + ($J) + " AT END GO TO STATIS.")
      DataLineOrNoStatement ("           ADD 1 TO CTFS.     ")
    }
    For ([Int32]$K = 1; $K -le (GetSgsValue ("FLDSEL,$I")); $K++) { 
      DataLineOrNoStatement ("       PSEL" + ($I) + ($K) + ".    ")
      DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("FLDSEL,$I,$K,1"))) + " TO IED.    ")
      DataLineOrNoStatement ("           COMPUTE IEF = IED + (" + ((GetSgsValue ("FLDSEL,$I,$K,2"))) + " - 1).  ")
      DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("FLDSEL,$I,$K,3"))) + " TO IRD.    ")
      DataLineOrNoStatement ("           PERFORM PARAG THRU FIPARAG.    ")
    }
  }
  DataLineOrNoStatement ("           PERFORM ECRIOUT THRU FIECRIOUT.")
  If ((CompareTypeSafe (GetSgsValue ("MOD,$I,1,1")) "GreaterThan" 0)) {
    DEFINE_CALTROI ((GetSgsValue ("MOD,$I,1,5")))
    DataLineOrNoStatement ("           PERFORM PARMOD" + ($I) + " THRU FIPARMOD" + ($I) + " NBFOIS TIMES.     ")
    DataLineOrNoStatement ("       PARMOD" + ($I) + ".")
    If ((CompareTypeSafe (GetSgsValue ("MOD,$I,1,3")) "EqualTo" "N")) {
      DataLineOrNoStatement ("           ADD " + ((GetSgsValue ("MOD,$I,1,4"))) + " TO CHMODN" + ($I) + ". ")
    } else {
      DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("MOD,$I,1,2"))) + " TO IEF. ")
      DataLineOrNoStatement ("           MOVE " + ((GetSgsValue ("MOD,$I,1,4"))) + " TO VALEUR.    ")
      DataLineOrNoStatement ("       TT" + ($I) + ".    ")
      DataLineOrNoStatement ("           IF IEF = 0 MOVE ALL '*' TO CHAMP" + ($I) + " ")
      DataLineOrNoStatement ("                      GO TO FIPARMOD" + ($I) + ". ")
      DataLineOrNoStatement ("           MOVE CHMODA" + ($I) + " (IEF) TO ZONE. ")
      DataLineOrNoStatement ("           PERFORM RECHA THRU FIRECHA.    ")
      DataLineOrNoStatement ("           MOVE ZONE TO CHMODA" + ($I) + " (IEF). ")
      DataLineOrNoStatement ("           IF RETOUR = 'R' SUBTRACT 1 FROM IEF GO TO TT" + ($I) + ".")
    }
    DataLineOrNoStatement ("       FIPARMOD" + ($I) + ".    ")
    DataLineOrNoStatement ("           MOVE SPACE TO RETOUR.    ")
    DataLineOrNoStatement ("           PERFORM ECRIOUT THRU FIECRIOUT.")
  }
}
DataLineOrNoStatement ("       STATIS.    ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE SPACES TO ZPR.")
  DataLineOrNoStatement ("           WRITE ZPR BEFORE SAUT.   ")
}
DataLineOrNoStatement ("           DISPLAY 'STATISTIQUES DE CREATION' UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NOMBRE DE CARTES DONNEES LUES' UPON PRINTER.  ")
DataLineOrNoStatement ("           ADD CTFS CTCAR GIVING CTTEST.  ")
DataLineOrNoStatement ("           DISPLAY CTTEST UPON PRINTER.   ")
DataLineOrNoStatement ("           DISPLAY 'NOMBRE DE CARTES DONNEES POUR FS' CTFS  ")
DataLineOrNoStatement ("                                        UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NOMBRE DE CARTES DONNEES CREATION' CTCAR")
DataLineOrNoStatement ("                                        UPON PRINTER. ")
DataLineOrNoStatement ("           DISPLAY 'NOMBRE DE RECORDS CREES' CTOUT  UPON PRINTER. ")
DataLineOrNoStatement ("           IF CTSPEC = CTTEST ")
DataLineOrNoStatement ("                    DISPLAY 'FIN DU TRAVAIL,TOUT EST OK' UPON PRINTER   ")
DataLineOrNoStatement ("           ELSE DISPLAY 'VERIFIER OUTPUT' 'IL Y AVAIT TROP PEU DE CARTES")
DataLineOrNoStatement ("      -      ' DONNEES OU FS' UPON PRINTER.     ")
DataLineOrNoStatement ("       FIN. ")
DataLineOrNoStatement ("           CLOSE FIC CAR.     ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           CLOSE PRI.   ")
}
DataLineOrNoStatement ("           STOP RUN.    ")
DataLineOrNoStatement ("       ECRIOUT.   ")
DataLineOrNoStatement ("           WRITE ZFIC FROM ZOUT.    ")
DataLineOrNoStatement ("           ADD 1 TO CTOUT.    ")
If ((CompareTypeSafe (GetSgsValue ("LIST")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           MOVE ZOUT TO ZPRINT.     ")
  DataLineOrNoStatement ("           MOVE CTOUT TO FILCT.     ")
  DataLineOrNoStatement ("           WRITE ZPR FROM ZTIT BEFORE 1.  ")
  For ([Int32]$P = 1; $P -le (GetSgsValue ("OUTPUT,1,1,2")); $P += 100) { 
    DataLineOrNoStatement ("           WRITE ZPR FROM ZP" + ($P) + " BEFORE 1.")
  }
  DataLineOrNoStatement ("           MOVE ALL '*' TO ZPR.     ")
  DataLineOrNoStatement ("           WRITE ZPR BEFORE 1.")
}
DataLineOrNoStatement ("       FIECRIOUT. ")
DataLineOrNoStatement ("           EXIT.  ")
DataLineOrNoStatement ("       PARAG.     ")
DataLineOrNoStatement ("           MOVE ZCEM (IED) TO ZTR (IRD).  ")
DataLineOrNoStatement ("           ADD 1 TO IED IRD.  ")
DataLineOrNoStatement ("           IF IED NOT > IEF GO TO PARAG.  ")
DataLineOrNoStatement ("       FIPARAG.   ")
DataLineOrNoStatement ("           EXIT.  ")
DataLineOrNoStatement ("       RECHA.     ")
DataLineOrNoStatement ("           MOVE 0 TO IED.     ")
DataLineOrNoStatement ("       INC1.")
DataLineOrNoStatement ("           ADD 1 TO IED.")
DataLineOrNoStatement ("           IF ZONE = ALPHA (IED) GO TO CONT1.   ")
DataLineOrNoStatement ("           IF IED < 26 GO TO INC1.  ")
DataLineOrNoStatement ("           GO TO RECHN. ")
DataLineOrNoStatement ("       CONT1.     ")
DataLineOrNoStatement ("           SUBTRACT IED FROM VINSIX GIVING ZREP.")
DataLineOrNoStatement ("           IF ZREP NOT < VALEUR ADD VALEUR TO IED     ")
DataLineOrNoStatement ("                                MOVE ALPHA (IED) TO ZONE    ")
DataLineOrNoStatement ("                                MOVE SPACE TO RETOUR  ")
DataLineOrNoStatement ("                                GO TO FIRECHA.  ")
DataLineOrNoStatement ("           SUBTRACT ZREP FROM VALEUR GIVING IED.")
DataLineOrNoStatement ("           MOVE ALPHA (IED) TO ZONE.")
DataLineOrNoStatement ("           MOVE 'R' TO RETOUR.")
DataLineOrNoStatement ("           MOVE 1 TO VALEUR.  ")
DataLineOrNoStatement ("           GO TO FIRECHA.     ")
DataLineOrNoStatement ("       RECHN.     ")
DataLineOrNoStatement ("           MOVE 0 TO IED.     ")
DataLineOrNoStatement ("       INC2.")
DataLineOrNoStatement ("           ADD 1 TO IED.")
DataLineOrNoStatement ("           IF ZONE = NUMER (IED) GO TO CONT2.   ")
DataLineOrNoStatement ("           IF IED < 10 GO TO INC2.  ")
DataLineOrNoStatement ("           MOVE '*' TO ZONE.  ")
DataLineOrNoStatement ("           MOVE SPACE TO RETOUR.    ")
DataLineOrNoStatement ("           GO TO FIRECHA.     ")
DataLineOrNoStatement ("       CONT2.     ")
DataLineOrNoStatement ("           SUBTRACT IED FROM DIX GIVING ZREP.   ")
DataLineOrNoStatement ("           IF ZREP NOT < VALEUR ADD VALEUR TO IED     ")
DataLineOrNoStatement ("                                MOVE NUMER (IED) TO ZONE    ")
DataLineOrNoStatement ("                                MOVE SPACE TO RETOUR  ")
DataLineOrNoStatement (".                               GO TO FIRECHA.  ")
DataLineOrNoStatement ("           SUBTRACT ZREP FROM VALEUR GIVING IED.")
DataLineOrNoStatement ("           MOVE NUMER (IED) TO ZONE.")
DataLineOrNoStatement ("           MOVE 'R' TO RETOUR.")
DataLineOrNoStatement ("           MOVE 1 TO VALEUR.  ")
DataLineOrNoStatement ("           GO TO FIRECHA.     ")
DataLineOrNoStatement ("       FIRECHA.   ")
DataLineOrNoStatement ("           EXIT.  ")
# @MAP N  ASSURFED*UTILITASCII.MAP,TPF$.CHABAN    
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
Hdg "N"
Fin
