# Converted from SSG source: LOADIS_MULTI
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("           02  FILLER  PIC  X(" + ($FILLCTR) + ").  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB I     .LOADIS,.LOADIS 
  Call-ExternalProgram "ACOB" "I" ("\LOADIS")
  Fin
} else {
  # @ACOB IT    .LOADIS,.LOADIS 
  Call-ExternalProgram "ACOB" "I, T" ("\LOADIS")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. LOADIS.  ")
# 
DataLineOrNoStatement ("       AUTHOR.     H A N S E")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNISYS-1100.")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNISYS-1100.")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT BDE  ASSIGN TO")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("               UNISERVO " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
} else {
  DataLineOrNoStatement ("               DISC " + ((GetSgsValue ("INPUT,1,1,1"))) + ".  ")
}
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           SELECT DISQ ASSIGN TO A-SHARED-FILE " + ((GetSgsValue ("OUTPUT,1,1,1"))) + "   ")
} else {
  DataLineOrNoStatement ("           SELECT DISQ ASSIGN TO DISC  " + ((GetSgsValue ("OUTPUT,1,1,1"))) + "   ")
}
DataLineOrNoStatement ("           RESERVE 20 AREAS ")
DataLineOrNoStatement ("           ORGANIZATION IS INDEXED  ")
DataLineOrNoStatement ("           ACCESS  MODE IS SEQUENTIAL   ")
DataLineOrNoStatement ("           FILE STATUS  IS FS-DISQ  ")
DataLineOrNoStatement ("           RECORD KEY IS CLEF   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEG ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEH ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("           ALTERNATE RECORD KEY IS CLEI ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("                     WITH DUPLICATES")
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  BDE  ")
DataLineOrNoStatement ("           LABEL RECORD STANDARD")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + "   RECORDS   ")
DataLineOrNoStatement ("           RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,1,2"))) + " CHARACTERS ")
DataLineOrNoStatement ("           DATA RECORD IS  Z1.  ")
DataLineOrNoStatement ("       01  Z1      PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + ").   ")
DataLineOrNoStatement ("       FD  DISQ ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
} else {
  DataLineOrNoStatement ("           LABEL RECORD STANDARD")
}
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,4")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + " TO " + ((GetSgsValue ("OUTPUT,1,1,4"))) + " RECORDS  ")
} else {
  DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + " RECORDS")
}
DataLineOrNoStatement ("           RECORD  CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " CHARACTERS   ")
DataLineOrNoStatement ("           DATA RECORD IS ZDISQ CLEFA CLEFB CLEFC CLEFD.")
DataLineOrNoStatement ("       01  ZDISQ   PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
DataLineOrNoStatement ("       01  CLEFA.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").  ")
}
DataLineOrNoStatement ("           02 CLEF   PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").  ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,3")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
DataLineOrNoStatement ("       01  CLEFB.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,2,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEG   PIC X(" + ((GetSgsValue ("KEYIS,2,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,2,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + "). ")
}
DataLineOrNoStatement ("       01  CLEFC.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,3,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEH   PIC X(" + ((GetSgsValue ("KEYIS,3,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,3,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + "). ")
}
DataLineOrNoStatement ("       01  CLEFD.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,4,1,1"))) + ").  ")
  }
  DataLineOrNoStatement ("           02 CLEI   PIC X(" + ((GetSgsValue ("KEYIS,4,1,2"))) + ").  ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,4,1,3"))) + ").  ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + "). ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  CTR                PIC  9(10)  COMP  VALUE 0.")
DataLineOrNoStatement ("       01  FS-DISQ. ")
DataLineOrNoStatement ("           02 FS1-DISQ        PIC X.")
DataLineOrNoStatement ("           02 FS2-DISQ        PIC 99 COMP.  ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  RDMS-STATUS        PIC 9(4). ")
  DataLineOrNoStatement ("       01  INFO-COLUMN        PIC S1(36).   ")
}
DataLineOrNoStatement ("       01  WREC.")
DataLineOrNoStatement ("           02 FILLER          PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").   ")
DataLineOrNoStatement ("       01  WREC1 REDEFINES  WREC.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + "). ")
}
DataLineOrNoStatement ("           02 KEYA            PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + "). ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,3")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + "). ")
}
DataLineOrNoStatement ("       01  WREC2 REDEFINES WREC.")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,2,1,1"))) + "). ")
  }
  DataLineOrNoStatement ("           02 KEYB            PIC X(" + ((GetSgsValue ("KEYIS,2,1,2"))) + "). ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,2,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,2,1,3"))) + "). ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
}
DataLineOrNoStatement ("       01  WREC3 REDEFINES WREC.")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,3,1,1"))) + "). ")
  }
  DataLineOrNoStatement ("           02 KEYC            PIC X(" + ((GetSgsValue ("KEYIS,3,1,2"))) + "). ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,3,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,3,1,3"))) + "). ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
}
DataLineOrNoStatement ("       01  WREC4 REDEFINES WREC.")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,1")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,4,1,1"))) + "). ")
  }
  DataLineOrNoStatement ("           02 KEYD            PIC X(" + ((GetSgsValue ("KEYIS,4,1,2"))) + "). ")
  If ((CompareTypeSafe (GetSgsValue ("KEYIS,4,1,3")) "GreaterThan" 0)) {
    DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("KEYIS,4,1,3"))) + "). ")
  }
} else {
  DataLineOrNoStatement ("           02 FILLER          PIC X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("      ********************  ")
DataLineOrNoStatement ("      * ")
DataLineOrNoStatement ("       DECLARATIVES.")
DataLineOrNoStatement ("       ROLLBACK1 SECTION.   ")
DataLineOrNoStatement ("           USE AFTER STANDARD ERROR PROCEDURE ON DISQ.  ")
DataLineOrNoStatement ("       FILE1-ERROR. ")
DataLineOrNoStatement ("           DISPLAY 'FILE STATUS KEY 1 : ' FS1-DISQ UPON PRINTER.")
DataLineOrNoStatement ("           DISPLAY '            KEY 2 : ' FS2-DISQ UPON PRINTER.")
DataLineOrNoStatement ("           GO TO ERRDISQ.   ")
DataLineOrNoStatement ("       FILE1-ERROR-END. ")
DataLineOrNoStatement ("           EXIT.")
DataLineOrNoStatement ("      * ")
DataLineOrNoStatement ("       END DECLARATIVES.")
DataLineOrNoStatement ("       MAIN-PGM SECTION.")
DataLineOrNoStatement ("       DEBUT.   ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("                 'BEGIN THREAD FOR UDSSRC UPDATE(QUICKLOOKS) UDSMSG ;'  ")
  DataLineOrNoStatement ("                 RDMS-STATUS, INFO-COLUMN.  ")
}
DataLineOrNoStatement ("           OPEN  INPUT   BDE.   ")
DataLineOrNoStatement ("           OPEN  OUTPUT  DISQ.  ")
DataLineOrNoStatement ("       LECT.")
DataLineOrNoStatement ("           MOVE SPACES TO Z1.   ")
DataLineOrNoStatement ("           READ  BDE   INTO  WREC  AT END GO TO FINB.   ")
DataLineOrNoStatement ("       CONT.")
DataLineOrNoStatement ("           MOVE KEYA     TO  CLEF.  ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 1)) {
  DataLineOrNoStatement ("           MOVE KEYB     TO  CLEG.  ")
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 2)) {
  DataLineOrNoStatement ("           MOVE KEYC     TO  CLEH.  ")
}
If ((CompareTypeSafe (GetSgsValue ("KEYIS")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("           MOVE KEYD     TO  CLEI.  ")
}
DataLineOrNoStatement ("           ADD  1  TO  CTR. ")
DataLineOrNoStatement ("           WRITE ZDISQ FROM WREC INVALID KEY GO TO  ERRDISQ.")
DataLineOrNoStatement ("           MOVE SPACES TO WREC ZDISQ.   ")
DataLineOrNoStatement ("           GO TO LECT.  ")
DataLineOrNoStatement ("       FINB.")
DataLineOrNoStatement ("           DISPLAY 'NB.RECORDS ECRITS'  CTR  UPON PRINTER.  ")
DataLineOrNoStatement ("           CLOSE  DISQ. ")
DataLineOrNoStatement ("           CLOSE  BDE.  ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("                 'END THREAD ; '")
  DataLineOrNoStatement ("                 RDMS-STATUS, INFO-COLUMN.  ")
}
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       ERRDISQ. ")
DataLineOrNoStatement ("           DISPLAY 'IS.ERROR'  CLEF  UPON  PRINTER. ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           ENTER MASM 'ACOB`$RDMR' USING ")
  DataLineOrNoStatement ("                 'OMIT THREAD ; '   ")
  DataLineOrNoStatement ("                 RDMS-STATUS, INFO-COLUMN.  ")
}
DataLineOrNoStatement ("           ENTER ASM 'ABORT'.   ")
If ((CompareTypeSafe (GetSgsValue ("SFS")) "GreaterThan" 0)) {
  # @MAP N     ,TPF$.LOADIS 
  Call-ExternalProgram "MAP" "N" (",TPF`$\LOADIS")
  # Orphaned data line: IBANK,UX  C$DML
  # Orphaned data line: IBANK,MRC I1,025000
  # Orphaned data line: IN  TPF$.
  # Orphaned data line: IN  SYS$LIB$*RSA.RDMR-ACOBDAT
  # Orphaned data line: IN  SYS$LIB$*ACOB-DML.CBEP$$ACOB/FULL-LIB-CB
  # Orphaned data line: IN  SYS$LIB$*SFSLIB.CBEP$$SFS
  # Orphaned data line: DBANK,MU  D1,0164000
  # Orphaned data line: IN  TPF$.
  # Orphaned data line: IN  SYS$LIB$*RSA.RDMR-ACOBDAT
  # Orphaned data line: IN  SYS$LIB$*RSA.CBEP$$RSA
  # Orphaned data line: IN  SYS$LIB$*SFSLIB.CBEP$$SFS
  # Orphaned data line: LIB SYS$LIB$*ACOB.
  # Orphaned data line: LIB SYS$LIB$*SORT.
  # Orphaned data line: LIB PRD*REL.
  # Orphaned data line: END
  Fin
} else {
  # @MAP N    ASSURFED*UTILITASCII.MAP,TPF$.LOADIS  
  Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
  Fin
}
Hdg "N"
Fin
