# Converted from SSG source: UNLOADIS_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filer {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILER") {
    Return
  }

  $FILLCTR = ($Parameters[0] - 1)
  If ($FILLCTR) {
    DataLineOrNoStatement ("               06  FILLER  PIC  X(" + ($FILLCTR) + ").  ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  # @ACOB IPEC    .UNLOAD-ASCII,.UNLOAD-ASCII   
  Call-ExternalProgram "ACOB" "I, P, E, C" ("\UNLOAD-ASCII")
  Fin
} else {
  # @ACOB IPECT   .UNLOAD-ASCII,.UNLOAD-ASCII   
  Call-ExternalProgram "ACOB" "I, P, E, C, T" ("\UNLOAD-ASCII")
  Fin
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. UNLOAD-ASCII.")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY 13/05/82.  ")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
DataLineOrNoStatement ("           SELECT BDE  ASSIGN  TO   ")
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1")) "GreaterThan" 3)) {
  DataLineOrNoStatement ("               INTERCHANGE " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ".  ")
} else {
  DataLineOrNoStatement ("               DISC " + ((GetSgsValue ("OUTPUT,1,1,1"))) + ". ")
}
DataLineOrNoStatement ("           SELECT DISQ ASSIGN  TO  DISC  " + ((GetSgsValue ("INPUT,1,1,1"))) + "  ")
DataLineOrNoStatement ("              ORGANIZATION IS INDEXED   ")
DataLineOrNoStatement ("               RESERVE 5 AREAS  ")
DataLineOrNoStatement ("              ACCESS MODE IS SEQUENTIAL RECORD KEY IS  CLEF.")
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
DataLineOrNoStatement ("       FD  BDE  BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,3"))) + " RECORDS   ")
DataLineOrNoStatement ("               RECORD CONTAINS " + ((GetSgsValue ("OUTPUT,1,1,2"))) + " CHARACTERS")
If ((CompareTypeSafe (GetSgsValue ("OMITTED")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("                LABEL RECORD IS OMITTED ")
} else {
  DataLineOrNoStatement ("                LABEL RECORD IS STANDARD")
}
DataLineOrNoStatement ("                DATA RECORD IS  ZBDE.   ")
DataLineOrNoStatement ("       01  ZBDE    PIC  X(" + ((GetSgsValue ("OUTPUT,1,1,2"))) + ").  ")
DataLineOrNoStatement ("       FD  DISQ   LABEL RECORD IS STANDARD  ")
DataLineOrNoStatement ("           BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,1,3"))) + " RECORDS ")
DataLineOrNoStatement ("               RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,1,2"))) + " CHARACTERS ")
DataLineOrNoStatement ("                  DATA RECORD  IS ZDISQ.")
DataLineOrNoStatement ("       01  ZDISQ.   ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "EqualTo" 0)) {
  DataLineOrNoStatement ("           02 CLEF PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
} else {
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").  ")
  DataLineOrNoStatement ("           02 CLEF PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").")
  DataLineOrNoStatement ("           02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
DataLineOrNoStatement ("       77  CTR     PIC  9(10)  COMP  VALUE  0.  ")
DataLineOrNoStatement ("       77  REP     PIC  X.  ")
If ((CompareTypeSafe (GetSgsValue ("MAXREC")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       77  MAXBDE  PIC  9(10)  COMP  VALUE  " + ((GetSgsValue ("MAXREC,1,1,1"))) + ". ")
} else {
  DataLineOrNoStatement ("       77  MAXBDE  PIC  9(10)   COMP  VALUE   99999999. ")
}
DataLineOrNoStatement ("       01  MES1.")
DataLineOrNoStatement ("           02 FILLER  PIC X(19) VALUE 'NB.ARTICLES ECRITS='.")
DataLineOrNoStatement ("           02 CTR-1   PIC 9(7). ")
DataLineOrNoStatement ("       01  ZBUF.")
DataLineOrNoStatement ("              06 FILLER  PIC  X(" + ((GetSgsValue ("INPUT,1,1,2"))) + "). ")
DataLineOrNoStatement ("       01  ZBUF1      REDEFINES  ZBUF.  ")
If ((CompareTypeSafe (GetSgsValue ("KEYIS,1,1,1")) "EqualTo" 0)) {
  DataLineOrNoStatement ("               02 RKEY1 PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").   ")
  DataLineOrNoStatement ("               02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
} else {
  DataLineOrNoStatement ("               02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,1"))) + ").  ")
  DataLineOrNoStatement ("               02 RKEY1 PIC X(" + ((GetSgsValue ("KEYIS,1,1,2"))) + ").   ")
  DataLineOrNoStatement ("               02 FILLER PIC X(" + ((GetSgsValue ("KEYIS,1,1,3"))) + ").  ")
}
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       DEB. ")
DataLineOrNoStatement ("           OPEN OUTPUT  BDE.")
DataLineOrNoStatement ("           OPEN  INPUT   DISQ.  ")
DataLineOrNoStatement ("           MOVE LOW-VALUES    TO CLEF.  ")
DataLineOrNoStatement ("       DEBF.")
DataLineOrNoStatement ("           READ DISQ INTO ZBUF AT END GO TO FBDE.   ")
DataLineOrNoStatement ("           ADD  1  TO  CTR. ")
DataLineOrNoStatement ("           WRITE  ZBDE  FROM ZBUF.  ")
DataLineOrNoStatement ("           MOVE  CTR  TO  CTR-1.")
DataLineOrNoStatement ("           GO TO DEBF.  ")
DataLineOrNoStatement ("       CLOS.")
DataLineOrNoStatement ("           CLOSE  BDE.  ")
DataLineOrNoStatement ("           CLOSE  DISQ. ")
DataLineOrNoStatement ("           STOP  RUN.   ")
DataLineOrNoStatement ("       FBDE.")
DataLineOrNoStatement ("           DISPLAY  'FIN DE FICHIER' UPON  CONSOLE. ")
DataLineOrNoStatement ("           MOVE   CTR   TO CTR-1.   ")
DataLineOrNoStatement ("           DISPLAY  MES1   UPON  CONSOLE.   ")
DataLineOrNoStatement ("           GO TO  CLOS. ")
# @MAP N   *UTILITASCII.MAP,TPF$.UNLOADIS 
Call-ExternalProgram "MAP" "N" ("\UTILITASCII\MAP")
Hdg "N"
Fin
