using System.Reflection;
using System.Runtime.InteropServices;
using Asysco.Amt.Runtime.Support;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("[AMT Cobol, CobolProgram] COBOL PROGRAM")]
[assembly: AssemblyDescription("COBOL PROGRAM")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Avanade")]
[assembly: AssemblyProduct("NEW APPLICATION. \r\nGenerated by Amt development 8.0")]
[assembly: AssemblyCopyright("Copyright © Avanade")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("de5ebb9a-1c96-4b50-a44f-3b801591f00b")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers
// by using the '*' as shown below:
[assembly: AssemblyVersion("8.0.26125.0")]
[assembly: AssemblyFileVersion("2.2.0.0")]
[assembly: AssemblyInformationalVersion("8.0.26125.0")]

// Setting object information for the Amt object assembly.
[assembly: AmtAssemblyObjectInfo("Company.AFBUS_2200COBOL.BusinessLogic.Assurfed_Utilit_Cfh_Copy.Assurfed_Utilit_Cfh_Copy")]

