# Converted from SSG source: BABA_ASCII
# Generated by SsgConverter
param([string[]]$Parameters)

Function Define_filladd {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLADD") {
    Return
  }

  $FILLCTR = ($Parameters[0] + 1)
}
Function Define_fillsub {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_FILLSUB") {
    Return
  }

  $FILLCTR = (0 - $Parameters[0])
}
Function Define_limpara {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_LIMPARA") {
    Return
  }

  $PARALIM = ($Parameters[0] - 1)
}
Function Define_setstart {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SETSTART") {
    Return
  }

  $START = ($Parameters[0] + 1)
}
Function Define_setcval {
  Param(
    [String[]]$Parameters
  )

  If (Process-Skip "DEFINE_SETCVAL") {
    Return
  }

  $C = ($Parameters[0] + 1)
}
If ((CompareTypeSafe (GetSgsValue ("KEYS")) "EqualTo" 0)) {
  AddTo-SgsList "KEYS  ALL"
}
If ((CompareTypeSafe (GetSgsValue ("COND")) "GreaterThan" 0)) {
  $NOP = 0
} else {
  AddTo-SgsList (CompareTypeSafe "COND CTR" "LessThan" 99999999)
}
$Rgv_CASE = 1
# para y2k keys pos,num,lg 
# para def keys pos,1,4
$YPV = "<"
For ([Int32]$A = 1; $A -le (GetSgsValue ("Y2K")); $A++) { 
  If ((CompareTypeSafe (GetSgsValue ("Y2K,$A,1,1")) "EqualTo" "KEYS")) {
    $MAXY = (GetSgsValue ("KEYS"))
    For ([Int32]$C = 1; $C -le $MAXY; $C++) { 
      $PAR = "KEYS " + (GetSgsValue ("KEYS,$C,1,1")) + " "
      $NCHA = 2
      For ([Int32]$B = 2; $B -le (GetSgsValue ("Y2K,$A")); $B++) { 
        $YLG = 4
        If ((CompareTypeSafe (GetSgsValue ("y2k,$a,$B,3")) "GreaterThan" 0)) {
          $YLG = (GetSgsValue ("y2k,$a,b,3"))
        }
        $YCH = 2
        If ((CompareTypeSafe (GetSgsValue ("y2k,$a,$B,2")) "GreaterThan" 0)) {
          $YCH = (GetSgsValue ("y2k,$a,b,2"))
        }
        $YPOS = (GetSgsValue ("y2k,$a,$B,1"))
        $YNR = ($ych - 1)
        For ([Int32]$D = $NCHA; $D -le $YNR; $D++) { 
          $PAR = $par + " " + (GetSgsValue ("keys,$c,d,1")) + "," + (GetSgsValue ("keys,$c,d,2")) + "," + (GetSgsValue ("keys,$c,d,3")) + " "
          $NCHA = ($ncha + 1)
        }
        $YTR = (GetSgsValue ("keys,$c,ych,3,substr$,$ypos,ylg"))
        If ((CompareTypeSafe $ylg "EqualTo" 2)) {
          If ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 0)) {
            $YAN = "*" + (GetSgsValue ("*ytr,substr$,2,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 1)) {
            $YAN = "_" + (GetSgsValue ("*ytr,substr$,2,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 2)) {
            $YAN = "|" + (GetSgsValue ("*ytr,substr$,2,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,1")) "EqualTo" 3)) {
            $YAN = "~" + (GetSgsValue ("*ytr,substr$,2,1"))
          } else {
            $YAN = $ytr
          }
        } elseif ((CompareTypeSafe $ylg "EqualTo" 4)) {
          If ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 200)) {
            $YAN = $ypv + (GetSgsValue ("*ytr,substr$,4,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 201)) {
            $YAN = "_" + (GetSgsValue ("*ytr,substr$,4,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 202)) {
            $YAN = "|" + (GetSgsValue ("*ytr,substr$,4,1"))
          } elseif ((CompareTypeSafe (GetSgsValue ("$YTR,substr$,1,3")) "EqualTo" 203)) {
            $YAN = "~" + (GetSgsValue ("*ytr,substr$,4,1"))
          } else {
            $YAN = (GetSgsValue ("$YTR,substr$,3,2"))
          }
        }
        $YLS = ($ypos - 1)
        If ((CompareTypeSafe $yls "EqualTo" 0)) {
          $YTR = $yan
        } else {
          $YTR = (GetSgsValue ("keys,$c,ych,3,substr$,1,$yls")) + $yan
        }
        $YLS = ($ylg + $YPOS)
        $YLG1 = ((GetSgsValue ("keys,$C,$YCH,3,len$")) - ($yls + 1))
        If ((CompareTypeSafe $ylg1 "GreaterThan" 0)) {
          $YTR = $YTR + (GetSgsValue ("keys,$c,ych,3,substr$,$yls,ylg1"))
        }
        $PAR = $par + " " + (GetSgsValue ("keys,$c,ych,1")) + "," + (GetSgsValue ("keys,$c,ych,2")) + "," + $YTR
        $NCHA = ($ncha + 1)
      }
      For ([Int32]$D = $NCHA; $D -le (GetSgsValue ("KEYS,$C")); $D++) { 
        $PAR = $par + " " + (GetSgsValue ("keys,$c,d,1")) + "," + (GetSgsValue ("keys,$c,d,2")) + "," + (GetSgsValue ("keys,$c,d,3")) + " "
      }
      AddTo-SgsList $PAR
    }
    RemoveFrom-SgsList "KEYS" 1 $MAXY
  }
}
DataLineOrNoStatement ("       IDENTIFICATION DIVISION. ")
DataLineOrNoStatement ("       PROGRAM-ID. EXTRACT-" + ((GetSgsValue ("INPUT,1,1,1"))) + ".   ")
DataLineOrNoStatement ("       AUTHOR. BOURDEAUD HUY PIERRE.")
DataLineOrNoStatement ("       ENVIRONMENT DIVISION.")
DataLineOrNoStatement ("       CONFIGURATION SECTION.   ")
DataLineOrNoStatement ("       SOURCE-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       OBJECT-COMPUTER. UNIVAC-1100-60EIS.  ")
DataLineOrNoStatement ("       SPECIAL-NAMES.     PRINTER   IS   LISTE. ")
DataLineOrNoStatement ("       INPUT-OUTPUT SECTION.")
DataLineOrNoStatement ("       FILE-CONTROL.")
If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
  DataLineOrNoStatement ("           SELECT TAPEIN1 ASSIGN TO CARD-READER.")
} else {
  For ([Int32]$INPUTCT = 1; $INPUTCT -le (GetSgsValue ("INPUT,1")); $INPUTCT++) { 
    DataLineOrNoStatement ("           SELECT  TAPEIN" + ($INPUTCT) + "  ASSIGN  TO ")
    If ((CompareTypeSafe (GetSgsValue ("INPUT,1,$INPUTCT")) "GreaterThan" 3)) {
      DataLineOrNoStatement ("                              UNISERVO  " + ((GetSgsValue ("INPUT,1,$INPUTCT,1"))) + ".")
    } else {
      DataLineOrNoStatement ("                    DISC  " + ((GetSgsValue ("INPUT,1,$INPUTCT,1"))) + ".  ")
    }
  }
}
If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  DataLineOrNoStatement ("           SELECT TAPEOUT1 ASSIGN TO PRINTER.   ")
} else {
  For ([Int32]$OUTPUTCT = 1; $OUTPUTCT -le (GetSgsValue ("OUTPUT,1")); $OUTPUTCT++) { 
    DataLineOrNoStatement ("           SELECT  TAPEOUT" + ($OUTPUTCT) + "  ASSIGN  TO   ")
    If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,$OUTPUTCT")) "GreaterThan" 3)) {
      DataLineOrNoStatement ("                              UNISERVO  " + ((GetSgsValue ("OUTPUT,1,$OUTPUTCT,1"))) + ".  ")
    } else {
      DataLineOrNoStatement ("                    DISC  " + ((GetSgsValue ("OUTPUT,1,$OUTPUTCT,1"))) + ".")
    }
  }
}
DataLineOrNoStatement ("       DATA DIVISION.   ")
DataLineOrNoStatement ("       FILE SECTION.")
$FILLCTR = 0
For ([Int32]$IMP = 1; $IMP -le (GetSgsValue ("INPUT,1")); $IMP++) { 
  DataLineOrNoStatement ("       FD  TAPEIN" + ($IMP) + " ")
  If ((CompareTypeSafe (GetSgsValue ("INPUT,1,1,1")) "EqualTo" "CARDREADER")) {
    DataLineOrNoStatement ("           LABEL RECORD OMITTED ")
  } else {
    DataLineOrNoStatement ("                    LABEL RECORD IS STANDARD")
    DataLineOrNoStatement ("                   BLOCK CONTAINS " + ((GetSgsValue ("INPUT,1,$IMP,3"))) + " RECORDS   ")
  }
  DataLineOrNoStatement ("                   RECORD CONTAINS " + ((GetSgsValue ("INPUT,1,$IMP,2"))) + " CHARACTERS   ")
  DataLineOrNoStatement ("                    DATA RECORD  IS REC-IN-" + ($IMP) + ".  ")
  DataLineOrNoStatement ("       01  REC-IN-" + ($IMP) + ".   ")
  For ([Int32]$CH = 1; $CH -le (GetSgsValue ("INPUT,1,$IMP,2")); $CH++) { 
    For ([Int32]$COL = 2; $COL -le (GetSgsValue ("KEYS,1")); $COL++) { 
      If ((CompareTypeSafe ("VALUE OF" + (GetSgsValue ("KEYS,1,$COL,1"))) "EqualTo" $CH)) {
        If ($FILLCTR) {
          DataLineOrNoStatement ("           03  FILLER                   PIC  X(" + ($FILLCTR) + "). ")
        }
        DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($IMP) + "-FIELD-" + ($COL) + "   PIC  X(" + ((GetSgsValue ("KEYS,1,$COL,2"))) + ").   ")
        DEFINE_FILLSUB ((GetSgsValue ("KEYS,1,$COL,2")))
      }
    }
    DEFINE_FILLADD ($FILLCTR)
  }
  If ($FILLCTR) {
    DataLineOrNoStatement ("           03  FILLER                   PIC  X(" + ($FILLCTR) + "). ")
  }
}
For ([Int32]$OUTPCT = 1; $OUTPCT -le (GetSgsValue ("OUTPUT,1")); $OUTPCT++) { 
  DataLineOrNoStatement ("       FD  TAPEOUT" + ($OUTPCT) + " ")
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,1,1")) "EqualTo" "PRINTER")) {
  } else {
    DataLineOrNoStatement ("                    LABEL RECORD IS STANDARD")
    DataLineOrNoStatement ("                    BLOCK CONTAINS " + ((GetSgsValue ("OUTPUT,1,$OUTPCT,3"))) + " RECORDS  ")
  }
  DataLineOrNoStatement ("                    RECORD CONTAINS " + ((GetSgsValue ("OUTPUT,1,$OUTPCT,2"))) + " CHARACTERS  ")
  DataLineOrNoStatement ("                    DATA RECORD IS REC-OUT-" + ($OUTPCT) + ".   ")
  DataLineOrNoStatement ("       01  REC-OUT-" + ($OUTPCT) + "           PIC X(" + ((GetSgsValue ("OUTPUT,1,$OUTPCT,2"))) + ").  ")
}
DataLineOrNoStatement ("       WORKING-STORAGE SECTION. ")
For ([Int32]$INC = 1; $INC -le (GetSgsValue ("INPUT,1")); $INC++) { 
  DataLineOrNoStatement ("       77  TAPE-" + ($INC) + "-CT                PIC 9(10)  COMP VALUE 0.   ")
}
DataLineOrNoStatement ("       77  INPUT-CT                 PIC 9(10)  COMP  VALUE 0.   ")
For ([Int32]$OUTC = 1; $OUTC -le (GetSgsValue ("OUTPUT,1")); $OUTC++) { 
  DataLineOrNoStatement ("       77  TAPE-" + ($OUTC) + "-OUT-CT            PIC 9(10)  COMP  VALUE 0. ")
}
DataLineOrNoStatement ("       77  OUTPUT-CT                PIC 9(10)  COMP  VALUE 0.   ")
DataLineOrNoStatement ("       77  ELIMINATE-CT                 PIC 9(10)  COMP VALUE 0.")
For ([Int32]$RQS = 1; $RQS -le (GetSgsValue ("KEYS")); $RQS++) { 
  DataLineOrNoStatement ("       01  REQUIREMENTS-" + ($RQS) + ". ")
  For ([Int32]$REQ = 2; $REQ -le (GetSgsValue ("KEYS,$RQS")); $REQ++) { 
    If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI")) {
      DataLineOrNoStatement ("           03  REQ-ALT-" + ($RQS) + "-FLD-" + ($REQ) + "  PIC X(" + ((GetSgsValue ("KEYS,$RQS,REQ,2"))) + ").  ")
    } else {
      DataLineOrNoStatement ("           03  REQ-ALT-" + ($RQS) + "-FLD-" + ($REQ) + "          PIC X(" + ((GetSgsValue ("KEYS,$RQS,REQ,2"))) + ")   ")
      If ((CompareTypeSafe (GetSgsValue ("KEYS,$RQS,REQ,3")) "EqualTo" "BLANC")) {
        DataLineOrNoStatement ("               VALUE SPACE. ")
      } else {
        DataLineOrNoStatement ("               VALUE  '" + ((GetSgsValue ("KEYS,$RQS,REQ,3"))) + "'.   ")
      }
    }
  }
}
For ([Int32]$FL = 1; $FL -le (GetSgsValue ("INPUT,1")); $FL++) { 
  DataLineOrNoStatement ("       01  COMPARE-" + ($FL) + ".   ")
  For ([Int32]$CF = 2; $CF -le (GetSgsValue ("KEYS,1")); $CF++) { 
    DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($FL) + "-FIELD-" + ($CF) + "   PIC X(" + ((GetSgsValue ("KEYS,1,$CF,2"))) + ").   ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "GreaterThan" 0)) {
  If (((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YES") -or ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "OUI") -or ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YA") -or (CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI"))))) {
    For ([Int32]$FSQ = 1; $FSQ -le (GetSgsValue ("INPUT,1")); $FSQ++) { 
      DataLineOrNoStatement ("       01  FILE-" + ($FSQ) + "-SEQ-ERROR-CT     PIC 9(5)  COMP  VALUE 0.")
      DataLineOrNoStatement ("       01  SEQ-COMPARE-" + ($FSQ) + ".  ")
      For ([Int32]$SQ = 2; $SQ -le (GetSgsValue ("KEYS,1")); $SQ++) { 
        DataLineOrNoStatement ("           03  COMPARE-FILE-" + ($FSQ) + "-FIELD-" + ($SQ) + "    PIC X(" + ((GetSgsValue ("KEYS,1,$SQ,2"))) + "). ")
      }
    }
    DataLineOrNoStatement ("       01  ABORT-IND  PIC 9(5) COMP.")
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
      DataLineOrNoStatement ("       01  SEQ-ERR-LINE       USAGE  DISPLAY-1. ")
    } else {
      DataLineOrNoStatement ("       01  SEQ-ERR-LINE.")
    }
    DataLineOrNoStatement ("           03  SEQ-FNAME                PIC X(12).  ")
    DataLineOrNoStatement ("           03  FILLER                   PIC X(36)   ")
    DataLineOrNoStatement ("               VALUE  ' HAS SEQUENCE ERROR BETWEEN RECORD '.")
    DataLineOrNoStatement ("           03  SEQ-REC-1                PIC Z(11)9. ")
    DataLineOrNoStatement ("           03  FILLER                   PIC X(12)   ")
    DataLineOrNoStatement ("               VALUE  ' AND RECORD '.   ")
    DataLineOrNoStatement ("           03  SEQ-REC-2                PIC Z(11)9. ")
    DataLineOrNoStatement ("       01  SEQ-ERR-L2.  ")
    If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
      DataLineOrNoStatement ("                                                 USAGE   DISPLAY-1  ")
    }
    DataLineOrNoStatement ("           03  FILLER                   PIC X(9)")
    DataLineOrNoStatement ("               VALUE  'INDICATIF'.  ")
    DataLineOrNoStatement ("           03  SEQ-REC-L2               PIC Z(11)9. ")
    DataLineOrNoStatement ("           03  FILLER PIC X(6)  ")
    DataLineOrNoStatement ("               VALUE '  :-  '.  ")
    DataLineOrNoStatement ("           03  COMPARE-L2               PIC X(105). ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("ASCII")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("       01  DISPLAY-LINE                          USAGE  DISPLAY-1.  ")
} else {
  DataLineOrNoStatement ("       01  DISPLAY-LINE.")
}
DataLineOrNoStatement ("               03  DISP-MESSAGE        PIC X(24).   ")
DataLineOrNoStatement ("               03  DISP-FNAME          PIC X(12).   ")
DataLineOrNoStatement ("               03  DISP-CT             PIC Z(11)9.  ")
DataLineOrNoStatement ("               03  FILLER              PIC X(84)  VALUE SPACE.  ")
If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI")) {
  DataLineOrNoStatement ("       01  TESTA.   ")
  DataLineOrNoStatement ("           03  SWITCHA  PIC X.  ")
}
DataLineOrNoStatement ("       01  CTR PIC 9(18) COMP.  ")
DataLineOrNoStatement ("       PROCEDURE DIVISION.  ")
DataLineOrNoStatement ("       E-F-" + ((GetSgsValue ("INPUT,1,1,1"))) + " SECTION.   ")
DataLineOrNoStatement ("       DEBUT.   ")
For ([Int32]$OUTP = 1; $OUTP -le (GetSgsValue ("OUTPUT,1")); $OUTP++) { 
  DataLineOrNoStatement ("            OPEN OUTPUT TAPEOUT" + ($OUTP) + ". ")
}
DataLineOrNoStatement ("       OPEN-AND-FIRST-READ. ")
For ([Int32]$INP = 1; $INP -le (GetSgsValue ("INPUT,1")); $INP++) { 
  DataLineOrNoStatement ("           OPEN  INPUT  TAPEIN" + ($INP) + ". READ  TAPEIN" + ($INP))
  DataLineOrNoStatement ("             AT END  MOVE  HIGH-VALUE TO REC-IN-" + ($INP) + "  ")
  DataLineOrNoStatement ("             GO TO ENDING-ROUTINES. ")
  DataLineOrNoStatement ("           ADD 1 TO CTR.")
  DataLineOrNoStatement ("           MOVE  CORRESPONDING  REC-IN-" + ($INP) + "  TO  COMPARE-" + ($INP) + ".  ")
  DataLineOrNoStatement ("           ADD  1  TO  TAPE-" + ($INP) + "-CT.  ")
}
DataLineOrNoStatement ("           GO TO  SEPARATION.   ")
For ([Int32]$RD = 1; $RD -le (GetSgsValue ("INPUT,1")); $RD++) { 
  DataLineOrNoStatement ("       READ-FILE-" + ($RD) + ". ")
  DataLineOrNoStatement ("           READ  TAPEIN" + ($RD))
  DataLineOrNoStatement ("           AT END GO TO ENDING-ROUTINES.")
  DataLineOrNoStatement ("           ADD 1 TO CTR.")
  DataLineOrNoStatement ("           IF   ")
  For ([Int32]$I = 1; $I -le (GetSgsValue ("COND,1")); $I++) { 
    DataLineOrNoStatement ("           " + ((GetSgsValue ("COND,1,$I,1"))) + " ")
  }
  DataLineOrNoStatement ("           GO TO ECLATEMENT ")
  DataLineOrNoStatement ("           ELSE GO TO ENDING-ROUTINES.  ")
  DataLineOrNoStatement ("       ECLATEMENT.  ")
  If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "GreaterThan" 0)) {
    If (((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YES") -or ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "OUI") -or ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "YA") -or (CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI"))))) {
      DataLineOrNoStatement ("           MOVE CORRESPONDING  REC-IN-" + ($RD) + "  TO  SEQ-COMPARE-" + ($RD) + ". ")
      DataLineOrNoStatement ("           IF    SEQ-COMPARE-" + ($RD) + "  <   COMPARE-" + ($RD) + "   ")
      DataLineOrNoStatement ("                 GO  TO  ABORT-ROUTINES.")
      If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI")) {
        DataLineOrNoStatement ("           MOVE '0' TO SWITCHA. ")
        DataLineOrNoStatement ("           IF SEQ-COMPARE-" + ($RD) + " = COMPARE-" + ($RD) + " ")
        DataLineOrNoStatement ("           MOVE '1' TO SWITCHA. ")
      }
      DataLineOrNoStatement ("       MOVE-REC-" + ($RD) + ".  ")
    }
  }
  DataLineOrNoStatement ("           MOVE  CORRESPONDING  REC-IN-" + ($RD) + "   TO  COMPARE-" + ($RD) + ".   ")
  DataLineOrNoStatement ("           ADD 1 TO TAPE-" + ($RD) + "-CT.  ")
  DataLineOrNoStatement ("           GO  TO  REQUIREMENTS-TEST.   ")
}
For ([Int32]$WRIT = 1; $WRIT -le (GetSgsValue ("OUTPUT,1")); $WRIT++) { 
  DataLineOrNoStatement ("       WRITE-" + ($WRIT) + "-FROM-FILE-1.   ")
  DataLineOrNoStatement ("           WRITE  REC-OUT-" + ($WRIT) + "  FROM  REC-IN-1.  ")
  DataLineOrNoStatement ("           ADD  1  TO  TAPE-" + ($WRIT) + "-OUT-CT. ")
  DataLineOrNoStatement ("           GO  TO  READ-FILE-1. ")
}
DataLineOrNoStatement ("       SEPARATION SECTION.  ")
DataLineOrNoStatement ("       REQUIREMENTS-TEST.   ")
If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1,1")) "EqualTo" "MULTI")) {
  DataLineOrNoStatement ("           IF SWITCHA NOT = '1' ")
  DataLineOrNoStatement ("           GO TO WRITE-1-FROM-FILE-1.   ")
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1")) "GreaterThan" 1)) {
    DataLineOrNoStatement ("           GO TO WRITE-2-FROM-FILE-1.   ")
  } else {
    DataLineOrNoStatement ("           GO TO READ-FILE-1.   ")
  }
}
If ((CompareTypeSafe (GetSgsValue ("KEYS,1,1,1")) "EqualTo" "ALL")) {
  DataLineOrNoStatement ("           GO TO  WRITE-1-FROM-FILE-1.  ")
} else {
  If ((CompareTypeSafe (GetSgsValue ("KEYS,1,1,1")) "EqualTo" "R")) {
    For ([Int32]$TEST = 1; $TEST -le (GetSgsValue ("KEYS")); $TEST++) { 
      DataLineOrNoStatement ("           INSPECT REQUIREMENTS-" + ($TEST) + " ")
      DataLineOrNoStatement ("                   REPLACING ALL '<' BY ';' ")
      DataLineOrNoStatement ("           IF COMPARE-1 NOT = REQUIREMENTS-" + ($TEST) + " NEXT SENTENCE ELSE   ")
      DataLineOrNoStatement ("                              GO TO TOTOK.  ")
    }
    DataLineOrNoStatement ("           GO TO ALFRED.")
  } else {
    For ([Int32]$TEST = 1; $TEST -le (GetSgsValue ("KEYS")); $TEST++) { 
      DataLineOrNoStatement ("           INSPECT REQUIREMENTS-" + ($TEST) + " ")
      DataLineOrNoStatement ("                   REPLACING ALL '<' BY ';' ")
      DataLineOrNoStatement ("           IF COMPARE-1 NOT = REQUIREMENTS-" + ($TEST) + " NEXT SENTENCE ELSE   ")
      DataLineOrNoStatement ("                              GO TO ALFRED. ")
    }
  }
  DataLineOrNoStatement ("       TOTOK.   ")
  DataLineOrNoStatement ("           GO TO WRITE-1-FROM-FILE-1.   ")
  DataLineOrNoStatement ("       ALFRED.  ")
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1")) "GreaterThan" 1)) {
    DataLineOrNoStatement ("            GO TO WRITE-2-FROM-FILE-1.  ")
  } else {
    DataLineOrNoStatement ("            ADD 1 TO ELIMINATE-CT.  ")
    DataLineOrNoStatement ("           GO TO READ-FILE-1.   ")
  }
}
DataLineOrNoStatement ("       ENDING-ROUTINES SECTION. ")
DataLineOrNoStatement ("       PRINT-FILE-CTS.  ")
For ([Int32]$INP = 1; $INP -le (GetSgsValue ("INPUT,1")); $INP++) { 
  DataLineOrNoStatement ("           MOVE  '     RECORDS  READ FROM '  TO  DISP-MESSAGE.  ")
  DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("INPUT,1,$INP,1"))) + "'  TO  DISP-FNAME. ")
  DataLineOrNoStatement ("           MOVE  TAPE-" + ($INP) + "-CT  TO  DISP-CT.   ")
  DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
  DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
  DataLineOrNoStatement ("           ADD  TAPE-" + ($INP) + "-CT  TO  INPUT-CT.   ")
  DataLineOrNoStatement ("           CLOSE    TAPEIN" + ($INP) + ".   ")
}
DataLineOrNoStatement ("           MOVE  '   TOTAL RECORDS READ   '  TO  DISP-MESSAGE.  ")
DataLineOrNoStatement ("           MOVE  INPUT-CT  TO  DISP-CT. ")
DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
For ([Int32]$OUTP = 1; $OUTP -le (GetSgsValue ("OUTPUT,1")); $OUTP++) { 
  If ((CompareTypeSafe (GetSgsValue ("OUTPUT,1,$OUTP")) "GreaterThan" 3)) {
    DataLineOrNoStatement ("           MOVE ALL '" + ((GetSgsValue ("OUTPUT,1,$OUTP,4"))) + "'  TO  REC-OUT-" + ($OUTP) + ".   ")
    DataLineOrNoStatement ("           WRITE  REC-OUT-" + ($OUTP) + ".  ")
    DataLineOrNoStatement ("           ADD  1  TO  TAPE-" + ($OUTP) + "-OUT-CT. ")
  }
  DataLineOrNoStatement ("           MOVE  '    RECORDS WRITTEN TO  '  TO  DISP-MESSAGE.  ")
  DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("OUTPUT,1,$OUTP,1"))) + "'  TO  DISP-FNAME.   ")
  DataLineOrNoStatement ("           MOVE  TAPE-" + ($OUTP) + "-OUT-CT  TO  DISP-CT.  ")
  DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
  DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
  DataLineOrNoStatement ("           CLOSE    TAPEOUT" + ($OUTP) + ". ")
  DataLineOrNoStatement ("           ADD  TAPE-" + ($OUTP) + "-OUT-CT  TO  OUTPUT-CT. ")
}
DataLineOrNoStatement ("           MOVE  '   TOTAL RECORDS WRITTEN'  TO  DISP-MESSAGE.  ")
DataLineOrNoStatement ("           MOVE  OUTPUT-CT  TO  DISP-CT.")
DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
DataLineOrNoStatement ("           STOP RUN.")
DataLineOrNoStatement ("       ABORT-ROUTINES SECTION.  ")
DataLineOrNoStatement ("       SEQUENCE-ERRORS. ")
If ((CompareTypeSafe (GetSgsValue ("SEQERROR")) "GreaterThan" 0)) {
  DataLineOrNoStatement ("           GO  TO   ")
  For ([Int32]$FC = 1; $FC -le (GetSgsValue ("INPUT,1")); $FC++) { 
    DataLineOrNoStatement ("                    FILE-" + ($FC) + "-SEQ-ERROR                                   " + ($FC))
  }
  DataLineOrNoStatement ("              DEPENDING  ON  ABORT-IND  ")
  For ([Int32]$PARA = 1; $PARA -le (GetSgsValue ("INPUT,1")); $PARA++) { 
    DataLineOrNoStatement ("       FILE-" + ($PARA) + "-SEQ-ERROR.  ")
    DataLineOrNoStatement ("           MOVE  '" + ((GetSgsValue ("INPUT,1,$PARA,1"))) + "'  TO  SEQ-FNAME. ")
    DataLineOrNoStatement ("           SUBTRACT  1  FROM  TAPE-" + ($PARA) + "-CT  GIVING  SEQ-REC-1,   ")
    DataLineOrNoStatement ("                              SEQ-REC-L2.   ")
    DataLineOrNoStatement ("           MOVE  TAPE-" + ($PARA) + "-CT  TO  SEQ-REC-2.")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-LINE  TO  DISPLAY-LINE.")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  COMPARE-" + ($PARA) + "   TO   COMPARE-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-L2        TO   DISPLAY-LINE.   ")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  TAPE-" + ($PARA) + "-CT   TO   SEQ-REC-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-COMPARE-" + ($PARA) + "   TO   COMPARE-L2. ")
    DataLineOrNoStatement ("           MOVE  SEQ-ERR-L2         TO   DISPLAY-LINE.  ")
    DataLineOrNoStatement ("           DISPLAY  DISPLAY-LINE  UPON  LISTE.  ")
    DataLineOrNoStatement ("           MOVE  SPACES  TO  DISPLAY-LINE.  ")
    If ((CompareTypeSafe (GetSgsValue ("SEQERROR,1,1")) "GreaterThan" 1)) {
      DataLineOrNoStatement ("           ADD  1  TO  FILE-" + ($PARA) + "-SEQ-ERROR-CT.   ")
      DataLineOrNoStatement ("           IF  FILE-" + ($PARA) + "-SEQ-ERROR-CT  >  " + ((GetSgsValue ("SEQERROR,1,1,2"))) + "   ")
      DataLineOrNoStatement ("               CALL  'ABORT'.   ")
      DataLineOrNoStatement ("           GO  TO  MOVE-REC-" + ($PARA) + ".")
    } else {
      DataLineOrNoStatement ("           CALL  'ABORT'.   ")
    }
  }
}
DataLineOrNoStatement ("           STOP RUN.")
# @MAP N    ASSURFED*UTILITASCII.MAP,TPF$.BABA
Call-ExternalProgram "MAP" "N" ("ASSURFED\UTILITASCII\MAP")
SetC "" "0/t1"
Hdg "N"
Fin
