****************************************************************************************
*  This is the default lion.ini file for AMT Lion.                                     *
*  In this file the recommended parameters are prefilled.                              *
*  To see the meaning of all parameters, please look at the Lion manual                *
*  Configuration of LION (LION.ini file)                                               *
****************************************************************************************
BACKUPRUNTIME=False
BACKUPDIR=D:\AMT\Lion\Backup
SELECTEDAPPLICATIONS=
SELECTEDAPPPOOL=DefaultAppPool
SINGLEAPPPOOL=False
CONFIGUREAPPLICATIONSIIS=False
WEBSITEROOT=Default Web Site
VIRTUALFOLDER=AMT
URL=http://localhost/AMT
HELPURL=http://localhost/AMT/ControlCenter/Help
#HELPURL=http://help.myasysco.com/AMT%20Helpfiles%20for%20LION/default.aspx


[GENERAL]
#APPLICATIONTYPE=AMT Lion
DBSSYS=MSSQL
SERVERNAMEREPOSDB=<COMPUTERNAME>\MSSQL2014

***** The server and servicename of the LionDev Generator *****
LIONDEVNETSERVICENAME=LionDevNet_Generator
LIONDEVNETSERVERNAME=<COMPUTERNAME>
DBSNAME=<REPOSITORY_DB>

DBUSER=<DBUSER>
DBPSSW=<DBPASSW>

